import type { ChoiceQuestion, CourseLesson } from "./curriculum-v2";

const q = (prompt: string, options: string[], answer: string, explanation: string): ChoiceQuestion => ({ prompt, options, answer, explanation });

export const listeningBatch09: CourseLesson[] = [
  {id:"l69",skill:"listening",section:"Part 1",title:"社区艺术节志愿者登记",level:"基础",minutes:15,focus:"姓名、班次、岗位与集合地点",audioFile:"l69.mp3",speakers:"Coordinator + volunteer",text:"Coordinator: Riverside Arts Festival, how can I help? Volunteer: I would like to join the volunteer team for Saturday. Coordinator: Certainly. Can I take your name? Volunteer: Leo Matsuda, M-A-T-S-U-D-A. Coordinator: We have a morning shift from eight thirty until one, or an afternoon shift from twelve thirty until five. Volunteer: The afternoon shift suits me. Coordinator: Would you prefer the ticket counter or crowd guidance? Volunteer: Crowd guidance, please. Coordinator: Fine. Meet the crew beside the theatre's east entrance at twelve fifteen. Wear comfortable shoes, and we will provide a yellow vest.",questions:[q("Which shift does Leo choose?",["8:30 to 1:00","12:30 to 5:00","12:15 to 4:00"],"12:30 to 5:00","Leo 明确选择下午十二点半到五点。"),q("What job will Leo do?",["Sell food","Guide the crowd","Perform on stage"],"Guide the crowd","他选择 crowd guidance。"),q("Where should he meet the crew?",["At the west gate","Beside the east entrance","Inside the ticket office"],"Beside the east entrance","集合点在剧院东入口旁。"),q("What will the festival provide?",["A yellow vest","Comfortable shoes","A free album"],"A yellow vest","鞋要自己穿，主办方提供黄色背心。") ]},
  {id:"l70",skill:"listening",section:"Part 2",title:"极端天气下的图书馆服务",level:"进阶",minutes:16,focus:"关闭范围、替代服务与归还规则",audioFile:"l70.mp3",speakers:"Library manager",text:"Because severe rain has damaged the ground-floor electrical system, Central Library will remain closed until Thursday. The mobile library will stop outside the community arts centre from ten until four on Tuesday and Wednesday. It can accept returns, issue reserved books and help members use the online platform, but it cannot create new memberships. Items due during the closure will be renewed automatically, so no late charge will be added. The study room at North Branch has extended opening until eight in the evening. Please do not leave books outside Central Library, because the external return box is also out of service.",questions:[q("Why is Central Library closed?",["A staff festival","Electrical damage","A membership meeting"],"Electrical damage","暴雨损坏了一楼电气系统。"),q("Where will the mobile library stop?",["Outside the arts centre","At North Branch","Beside Central Library"],"Outside the arts centre","流动图书车停在社区艺术中心外。"),q("Which service is unavailable there?",["Book returns","New memberships","Reserved books"],"New memberships","可还书和取预约书，但不能新办会员。"),q("What happens to items due during the closure?",["They receive a fine","They are renewed automatically","They must be left outside"],"They are renewed automatically","系统自动续借且不收逾期费。") ]},
  {id:"l71",skill:"listening",section:"Part 3",title:"讨论员工压力调查方案",level:"进阶",minutes:18,focus:"样本、匿名性、问题设计与后续行动",audioFile:"l71.mp3",speakers:"HR officer + team representative",text:"HR officer: The latest staff survey shows increased stress on the night shift. Representative: The response rate was poor, though. Only twenty-four people completed it. HR officer: True. For the next survey, we should guarantee that answers are anonymous. Representative: And use specific questions. Asking whether work is difficult is too general. We could ask about workload, break length and supervisor support separately. HR officer: Good point. Let us also offer paper copies to staff who rarely use the online platform. Representative: What happens after the survey? HR officer: We will compare departments, then hold two small discussion groups before drafting recommendations. Representative: That makes the process more credible.",questions:[q("What weakness affected the latest survey?",["It had a low response rate","It was too expensive","It excluded night staff"],"It had a low response rate","只有二十四人完成，回应率低。"),q("What should be guaranteed next time?",["Higher salaries","Anonymous answers","Shorter shifts"],"Anonymous answers","人事人员提出保证匿名。"),q("Which additional format will be offered?",["Telephone interviews","Paper copies","A television debate"],"Paper copies","为少用线上平台的员工提供纸质版。"),q("What will happen before recommendations are drafted?",["Two discussion groups","A court hearing","A new election"],"Two discussion groups","先比较部门，再举行两个小组讨论。") ]},
  {id:"l72",skill:"listening",section:"Part 4",title:"海岸步道如何管理游客压力",level:"模考",minutes:19,focus:"问题、证据、措施与长期评估",audioFile:"l72.mp3",speakers:"Marine conservation lecturer",text:"The Blue Cape path has become one of the region's leading attractions. Visitor revenue supports local businesses, but heavy foot traffic has damaged vegetation near the cliff edge. The problem is not simply the total crowd. Most damage occurs at three viewpoints where people leave the marked path to take photographs. Rangers first considered a complete seasonal closure. Instead, they installed low barriers, moved signs to eye level and created two stronger viewing platforms. Independent monitoring found that off-path movement fell by sixty percent in the first year. The project also uses volunteer guides during the summer peak. Its ultimate success, however, depends on constant maintenance and whether visitors continue to respect the route after the guides leave.",questions:[q("Where does most damage occur?",["At three viewpoints","Inside local shops","Along the entire coast"],"At three viewpoints","主要损坏集中在三个观景点。"),q("Which proposal was not adopted?",["New viewing platforms","A complete seasonal closure","Low barriers"],"A complete seasonal closure","曾考虑完全季节性关闭，但改用了其他措施。"),q("What fell by sixty percent?",["Ticket revenue","Off-path movement","Volunteer numbers"],"Off-path movement","独立监测记录了离开步道行为下降六成。"),q("What is necessary for long-term success?",["Constant maintenance","A larger car park","Removing every sign"],"Constant maintenance","末段强调持续维护和游客守规。") ]},
];

export const readingBatch09: CourseLesson[] = [
  {id:"r69",skill:"reading",section:"Section 1",title:"健身中心会籍暂停规定",level:"基础",minutes:16,focus:"资格、期限、费用与证明",text:"MEMBERSHIP PAUSE\nMembers may pause an annual fitness membership because of illness, pregnancy, work travel or another serious change in circumstances. Submit the request before the pause begins, except in an emergency. The minimum pause is four weeks and the maximum is six months. A medical pause requires a letter confirming that exercise is not recommended; the letter does not need to state a diagnosis. One administration charge applies to each pause, but this is waived for pregnancy. During the paused period, entry cards will not work and booked classes will be cancelled. The membership end date will move forward by the exact length of the approved pause.",questions:[q("Which reason can support a pause?",["Pregnancy","Disliking a class","Buying new shoes"],"Pregnancy","通知明确列出怀孕。"),q("What is the minimum pause?",["One week","Four weeks","Six months"],"Four weeks","最短四周，最长六个月。"),q("What may the medical letter omit?",["The member's name","A diagnosis","A recommendation"],"A diagnosis","证明无需写出具体诊断。"),q("What happens to the membership end date?",["It stays unchanged","It moves by the approved period","It is cancelled permanently"],"It moves by the approved period","结束日期顺延获批暂停的准确时长。") ]},
  {id:"r70",skill:"reading",section:"Section 2",title:"配送车辆装载安全程序",level:"进阶",minutes:18,focus:"检查、重量、固定与事故报告",text:"SAFE LOADING PROCEDURE\nBefore loading, inspect the vehicle floor, doors and securing equipment. Report any fault and do not use damaged straps. Check the maximum weight for both the entire vehicle and each axle; a load can be unsafe even when the total remains below the vehicle limit. Place heavier items at the bottom and distribute weight evenly. Use separate restraints for objects that may move independently. The driver must complete a final walk-around, but every crew member remains responsible for reporting a concern. After a sudden stop or minor crash, park safely and inspect the load again before continuing. Record any movement or damage in the incident log.",questions:[q("What should happen to a damaged strap?",["It should not be used","It should secure light items","It should be hidden"],"It should not be used","程序要求报告故障并停用损坏绑带。"),q("Why must axle weight be checked?",["Total weight alone may hide an unsafe load","Every axle has the same limit","It reduces fuel receipts"],"Total weight alone may hide an unsafe load","总重未超也可能出现单轴不安全。"),q("Who is responsible for reporting concerns?",["Only the driver","Every crew member","Only the customer"],"Every crew member","司机终检，但全体成员都有报告责任。"),q("When must the load be inspected again?",["After a sudden stop","After every lunch break","Before receiving wages"],"After a sudden stop","急停或轻微碰撞后要重新检查。") ]},
  {id:"r71",skill:"reading",section:"Section 2",title:"网络诈骗受害者处置清单",level:"进阶",minutes:18,focus:"立即行动、证据、账户与报告",text:"IF YOU SUSPECT ONLINE FRAUD\nContact your bank immediately through the number on its official website or your card. Do not use a telephone number contained in the suspect message. Ask the bank to freeze affected cards or transfers and obtain a case reference. Change the password for the relevant account and for any other account using the same password. Keep the original message, payment receipt and screenshots; do not edit them. Report the incident to the national fraud service even if the amount is minor, because multiple reports can reveal a wider pattern. Be honest about any code or personal detail you shared. This information helps investigators and does not remove your right to request assistance.",questions:[q("Which bank number should be used?",["The number in the message","An official number","A random search result"],"An official number","必须用官网或银行卡上的正式号码。"),q("What should be obtained from the bank?",["A case reference","A new passport","A court sentence"],"A case reference","冻结相关交易后索取案件编号。"),q("Why report a minor loss?",["It may reveal a wider pattern","It guarantees immediate repayment","It removes every password"],"It may reveal a wider pattern","多份报告可能揭示更大规模诈骗。"),q("How should original evidence be kept?",["Edited for clarity","Unchanged","Posted publicly"],"Unchanged","原始信息、收据和截图不要编辑。") ]},
  {id:"r72",skill:"reading",section:"Section 3",title:"远程办公是否真正改变城市",level:"模考",minutes:23,focus:"主张、限制、群体差异与结论",text:"Predictions that remote work would empty city centres were too absolute. Office attendance has certainly fallen in many sectors, and some businesses that depended on the daily crowd have closed. Yet employment is not distributed evenly. Health care, construction, hospitality and numerous service jobs still require workers to be present. Even within office-based organisations, teams often choose a hybrid pattern rather than permanent home working.\n\nThe effects also extend beyond transport. Some employees gain time and flexibility, while others lack a quiet room, reliable internet or social contact. Employers may reduce floor space, but they must invest in secure digital platforms and develop fair ways to judge performance. A policy based only on personal preference can create division if senior staff receive more flexibility than new workers.\n\nCities are adapting rather than disappearing. Several have converted older offices into housing, although the process is difficult because building depth, windows and plumbing may be unsuitable. Public transport agencies are testing fares that reflect less typical travel times. Local centres have gained customers who previously bought lunch near a central office.\n\nThe ultimate outcome is therefore not a simple movement away from cities. Work is becoming more varied across time and place. The most valuable policies will recognise this diversity instead of assuming that one model suits the entire labour force.",questions:[q("Which prediction does the writer reject?",["All city centres would empty","Some commuting would fall","Hybrid work would exist"],"All city centres would empty","开头认为城市中心会完全空掉的预测过于绝对。"),q("What can create division at work?",["Fair performance measures","Unequal access to flexibility","Reliable online systems"],"Unequal access to flexibility","若高层比新人获得更多灵活性，会造成分化。"),q("Why is office conversion difficult?",["Buildings may be physically unsuitable","Housing is always illegal","Local centres have no customers"],"Buildings may be physically unsuitable","进深、窗户和管道可能不适合住宅。"),q("What does the writer recommend?",["One rule for every worker","Policies that recognise varied needs","Closing public transport"],"Policies that recognise varied needs","结论主张承认劳动者和工作模式的差异。") ]},
];

const task1Checklist = ["开头直接说明写信目的", "覆盖三个任务点并给出具体事实", "语气符合收信人关系", "至少 150 词并检查分段、时态和拼写"];
const task2Checklist = ["引言明确回应题目", "主体段有中心句、解释和例子", "比较、因果或让步关系清楚", "至少 250 词且结论不加入新观点"];
export const writingBatch09: CourseLesson[] = [
  {id:"w69",skill:"writing",section:"Task 1 · 正式信",title:"投诉健身会籍暂停处理错误",level:"进阶",minutes:26,focus:"说明申请、错误影响与要求更正",task:"You asked a fitness centre to pause your membership, but it continued to charge you. Write a letter to the manager. Write at least 150 words.",bullets:["describe when and why you requested the pause","explain the charges and their effect","request a refund and written confirmation of the new end date"],checklist:task1Checklist},
  {id:"w70",skill:"writing",section:"Task 1 · 私人信",title:"邀请朋友参加本地艺术节",level:"基础",minutes:25,focus:"活动介绍、推荐理由与见面安排",task:"A local arts festival will take place next month. Write a letter inviting a friend to attend with you. Write at least 150 words.",bullets:["describe the festival and the event you want to see","explain why your friend may enjoy it","suggest travel and meeting arrangements"],checklist:task1Checklist},
  {id:"w71",skill:"writing",section:"Task 2 · 双边讨论",title:"远程办公利大于弊吗",level:"模考",minutes:42,focus:"员工、雇主、城市与公平",task:"More people are working from home rather than travelling to a workplace. Do the advantages of this development outweigh the disadvantages? Write at least 250 words.",bullets:["compare flexibility and isolation","consider employer costs and performance","give a clear overall judgement"],checklist:task2Checklist},
  {id:"w72",skill:"writing",section:"Task 2 · 问题解决",title:"网络诈骗增加的原因与对策",level:"模考",minutes:42,focus:"成因、受害者保护与机构责任",task:"Online fraud is affecting a growing number of people. Why is this happening, and what can individuals, companies and governments do to reduce it? Write at least 250 words.",bullets:["explain technological and behavioural causes","propose realistic prevention and reporting measures","divide responsibility among relevant groups"],checklist:task2Checklist},
];

export const speakingBatch09: CourseLesson[] = [
  {id:"s69",skill:"speaking",section:"Part 1",title:"节日与现场活动",level:"基础",minutes:10,focus:"频率、偏好、原因与经历",prompts:["Do you often attend local festivals?","What kind of live performance do you enjoy?","Do you prefer a small event or a large crowd?","What makes an event memorable?"],keywords:["festival","perform","crowd","experience"]},
  {id:"s70",skill:"speaking",section:"Part 2",title:"一次有价值的志愿经历",level:"进阶",minutes:14,focus:"时间线、任务、困难与收获",task:"Describe a time when you helped at an event or in your community.",bullets:["what the activity was","what your particular role involved","what problem the group had to deal with","why the experience was valuable"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["join","deal with","effort","valuable"]},
  {id:"s71",skill:"speaking",section:"Part 3",title:"城市公共空间与大型人群",level:"模考",minutes:16,focus:"安全、收益、限制与政策选择",prompts:["Why do some public events draw massive crowds?","How can organisers improve crowd safety without destroying the atmosphere?","Should local revenue be used to support arts festivals?","How should residents influence decisions about major events?"],keywords:["draw","crowd","revenue","fair"]},
  {id:"s72",skill:"speaking",section:"Part 3",title:"技术、工作与人的判断",level:"模考",minutes:16,focus:"效率、公平、技能与长期影响",prompts:["Which workplace decisions can be based on data?","Why is human judgement still necessary?","How can employers help staff develop new skills?","Will technology create greater division or wider opportunity?"],keywords:["based","judge","develop","division"]},
];

export const curriculumBatch09: CourseLesson[] = [...listeningBatch09, ...readingBatch09, ...writingBatch09, ...speakingBatch09];
