import type { Skill } from "../product-types";

export type ChoiceQuestion = { prompt: string; options: string[]; answer: string; explanation: string };
export type CourseLesson = {
  id: string;
  skill: Skill;
  section: string;
  title: string;
  level: "基础" | "进阶" | "模考";
  minutes: number;
  focus: string;
  text?: string;
  questions?: ChoiceQuestion[];
  task?: string;
  bullets?: string[];
  checklist?: string[];
  prompts?: string[];
  keywords?: string[];
  audioFile?: string;
  speakers?: string;
};

const q = (prompt: string, options: string[], answer: string, explanation: string): ChoiceQuestion => ({ prompt, options, answer, explanation });

export const listeningLessons: CourseLesson[] = [
  {id:"l1",skill:"listening",section:"Part 1",title:"电话预约社区诊所",level:"基础",minutes:14,focus:"姓名、日期、时间、拼写",audioFile:"l1.mp3",speakers:"Receptionist + caller",
    text:"Receptionist: Good morning, Green Street Clinic. How can I help? Caller: I'd like to make an appointment with a doctor. Receptionist: Certainly. Could I take your name? Caller: Yes, it's Naran Bat — N-A-R-A-N, B-A-T. Receptionist: Thank you. Dr Evans is available on Thursday the eighteenth at ten thirty, or Friday at two fifteen. Caller: Thursday morning, please. Receptionist: Fine. Please arrive ten minutes early and bring photo identification.",
    questions:[q("On which day is the appointment?",["Thursday the 18th","Friday the 18th","Thursday the 28th"],"Thursday the 18th","对话先给两个选择，来电者最终选择 Thursday morning。"),q("What time is the appointment?",["10:13","10:30","2:15"],"10:30","注意 thirty 与 thirteen 的区别。"),q("How early should the caller arrive?",["5 minutes","10 minutes","15 minutes"],"10 minutes","结尾明确说 arrive ten minutes early。"),q("What must the caller bring?",["An insurance form","Photo identification","Cash"],"Photo identification","bring photo identification 是直接答案。")]},
  {id:"l2",skill:"listening",section:"Part 2",title:"图书馆欢迎介绍",level:"基础",minutes:15,focus:"地点、规则、时间表",audioFile:"l2.mp3",speakers:"Library guide",
    text:"Welcome to Westfield Library. The ground floor has returns and new books. Computers are on the first floor, beside the study room. Members may use a computer for one hour. The children's area closes at six, but the main library remains open until eight from Monday to Thursday. On Friday, the whole building closes at five thirty.",
    questions:[q("Where are the computers?",["Beside the ground-floor entrance","Beside the first-floor study room","Inside the children's area"],"Beside the first-floor study room","beside the study room 给出准确位置。"),q("How long may a member use a computer?",["30 minutes","One hour","Two hours"],"One hour","原文为 for one hour。"),q("What time does the main library close on Monday?",["5:30","6:00","8:00"],"8:00","儿童区六点关，但主馆周一至周四八点关。"),q("When does the whole building close on Friday?",["5:30","6:00","8:00"],"5:30","Friday 后给出 five thirty。")]},
  {id:"l3",skill:"listening",section:"Part 3",title:"两人讨论职业培训",level:"进阶",minutes:17,focus:"观点、决定、转折",audioFile:"l3.mp3",speakers:"Two trainees",
    text:"Mina: I first chose the customer service course because it was cheaper. Ken: But it clashes with your Friday shift. Mina: Exactly. So I've changed to workplace communication on Tuesday evenings. It costs twenty pounds more, but my manager says the company may pay half. Ken: That sounds useful. Are you still doing the online safety module? Mina: Yes. It's compulsory, and I must finish it before the end of May.",
    questions:[q("Which course has Mina finally chosen?",["Customer service","Workplace communication","Online safety"],"Workplace communication","changed to 表示最终决定。"),q("When is Mina's chosen course?",["Friday morning","Tuesday evening","Tuesday morning"],"Tuesday evening","原文为 on Tuesday evenings。"),q("How much might the company pay?",["The full cost","Half the cost","Twenty pounds"],"Half the cost","pay half 指支付一半。"),q("Why must Mina complete online safety?",["It is cheaper","Her manager recommended it","It is compulsory"],"It is compulsory","compulsory 表示必修。")]},
  {id:"l4",skill:"listening",section:"Part 4",title:"社区花园讲座",level:"进阶",minutes:19,focus:"因果、例子与笔记",audioFile:"l4.mp3",speakers:"Lecturer",
    text:"Community gardens do more than produce food. First, they turn unused land into shared space. Second, regular gardening can reduce stress and provide gentle exercise. Our survey found that most new members joined to meet neighbours, not to save money. However, water use remains a concern. The project therefore collects rainwater from the community hall roof and uses wood chips to keep moisture in the soil.",
    questions:[q("What is the first benefit mentioned?",["Cheaper food","Shared use of empty land","Paid employment"],"Shared use of empty land","turn unused land into shared space 对应答案。"),q("Why did most new members join?",["To save money","To meet neighbours","To get free food"],"To meet neighbours","not to save money 是干扰信息。"),q("Where is rainwater collected from?",["The garden path","The hall roof","A nearby river"],"The hall roof","原文明确说 community hall roof。"),q("Why are wood chips used?",["To attract insects","To keep soil moist","To mark paths"],"To keep soil moist","keep moisture in the soil。")]},
  {id:"l5",skill:"listening",section:"Part 1",title:"报名周末烹饪课",level:"基础",minutes:14,focus:"姓名拼写、费用、日期",audioFile:"l5.mp3",speakers:"Centre assistant + learner",
    text:"Assistant: Riverside Community Centre. How can I help? Learner: I'd like to join the weekend cooking course. Assistant: The next course begins on Saturday the ninth of October and runs for four weeks. It starts at eleven fifteen. Learner: That's fine. How much is it? Assistant: Forty-eight pounds, including ingredients. Could I take your surname? Learner: Yes, Dolgor — D-O-L-G-O-R. Assistant: Thank you. Please pay a twenty-pound deposit by Wednesday.",
    questions:[q("When does the course begin?",["Saturday 9 October","Sunday 9 October","Saturday 19 October"],"Saturday 9 October","注意 Saturday、ninth 和 October 三项信息。"),q("What time does each class start?",["10:15","11:15","11:50"],"11:15","eleven fifteen。"),q("What is included in the £48 fee?",["Equipment","Ingredients","A course book"],"Ingredients","including ingredients。"),q("How much is the deposit?",["£18","£20","£28"],"£20","结尾要求 twenty-pound deposit。")]},
  {id:"l6",skill:"listening",section:"Part 1",title:"报告公寓供暖故障",level:"基础",minutes:14,focus:"地址、故障、预约时段",audioFile:"l6.mp3",speakers:"Tenant + maintenance agent",
    text:"Agent: Northside Property Services. Tenant: Hello, the heating in my flat has stopped working. Agent: What's the address? Tenant: Flat 6, 42 Cedar Road. The radiators are cold, but the hot water is still working. Agent: When did the problem start? Tenant: Late on Monday evening. Agent: An engineer can visit tomorrow between one and three, or Thursday morning between eight and ten. Tenant: Tomorrow afternoon is better. Agent: Please make sure someone over eighteen is at home.",
    questions:[q("What is the flat number?",["4","6","42"],"6","42 是门牌号，Flat 6 才是公寓号。"),q("What is still working?",["The radiators","The hot water","The cooker"],"The hot water","but 后给出保留信息。"),q("When did the problem begin?",["Monday evening","Tuesday morning","Thursday morning"],"Monday evening","late on Monday evening。"),q("Which visit does the tenant choose?",["Tomorrow, 1–3 p.m.","Thursday, 8–10 a.m.","Tomorrow, 8–10 a.m."],"Tomorrow, 1–3 p.m.","Tomorrow afternoon is better。")]},
  {id:"l7",skill:"listening",section:"Part 1",title:"查询机场接送服务",level:"基础",minutes:14,focus:"航班号、人数、取车地点",audioFile:"l7.mp3",speakers:"Transport clerk + traveller",
    text:"Clerk: City Shuttle Bookings. Traveller: I need a transfer from the airport on the twenty-third of June. Clerk: What is your flight number? Traveller: BA two seven four. It lands at eighteen forty. There will be three adults and one child. Clerk: Our driver will meet you outside Exit B, beside the information desk. The total fare is sixty-five pounds, and a child seat is included. Traveller: Great. Please book it under the name Erdene.",
    questions:[q("What is the flight number?",["BA 247","BA 274","AB 274"],"BA 274","数字顺序是 two seven four。"),q("How many people are travelling?",["Three","Four","Five"],"Four","three adults and one child 共四人。"),q("Where will the driver wait?",["At Exit A","Outside Exit B","At the baggage desk"],"Outside Exit B","outside Exit B。"),q("What is included in the fare?",["Airport tax","A child seat","Extra luggage"],"A child seat","a child seat is included。")]},
  {id:"l8",skill:"listening",section:"Part 1",title:"申请健身中心会员",level:"基础",minutes:14,focus:"方案比较、个人信息、付款",audioFile:"l8.mp3",speakers:"Gym receptionist + applicant",
    text:"Receptionist: Harbour Fitness Centre. Applicant: I'd like to become a member. Receptionist: We have a monthly plan for thirty-six pounds or an annual plan for three hundred and sixty. The annual plan includes two free sessions with a trainer. Applicant: I'll take the monthly plan first. Receptionist: Fine. May I have your date of birth? Applicant: The fourteenth of February, nineteen ninety-two. Receptionist: You can pay by card today. The membership will begin on Monday.",
    questions:[q("How much is the monthly plan?",["£30","£36","£360"],"£36","thirty-six pounds。"),q("What is included in the annual plan?",["Two trainer sessions","Free swimming lessons","A family membership"],"Two trainer sessions","two free sessions with a trainer。"),q("Which plan does the applicant choose?",["Monthly","Annual","Family"],"Monthly","I'll take the monthly plan first。"),q("When will the membership start?",["Today","Monday","14 February"],"Monday","结尾明确说 begin on Monday。")]},
  {id:"l9",skill:"listening",section:"Part 2",title:"新员工仓库安全说明",level:"基础",minutes:16,focus:"规则、位置、紧急流程",audioFile:"l9.mp3",speakers:"Safety officer",
    text:"Before you begin work, collect a yellow safety vest from the office beside the main entrance. Protective shoes are required in every storage area, but gloves are only compulsory in the cold room. Breaks are taken in the staff kitchen on the second floor; food must not be brought into the warehouse. If the fire alarm sounds, leave through the nearest marked exit and meet beside the north car park. Do not return until a manager gives permission.",
    questions:[q("Where should staff collect a safety vest?",["The cold room","The entrance office","The staff kitchen"],"The entrance office","office beside the main entrance。"),q("Where are gloves compulsory?",["Every storage area","Only the cold room","The car park"],"Only the cold room","only compulsory in the cold room。"),q("Where may staff eat?",["In the warehouse","In the second-floor kitchen","Beside the entrance"],"In the second-floor kitchen","breaks in the staff kitchen on the second floor。"),q("Where is the emergency meeting point?",["The south entrance","The north car park","The second floor"],"The north car park","meet beside the north car park。")]},
  {id:"l10",skill:"listening",section:"Part 2",title:"市民回收中心指南",level:"进阶",minutes:16,focus:"分类、限制、开放时间",audioFile:"l10.mp3",speakers:"Council officer",
    text:"The Green Lane Recycling Centre accepts paper, glass, metal and small electrical items. Garden waste should be taken to Bay Four, while paint and household chemicals must be handed directly to a member of staff at Bay Seven. The centre cannot accept building materials from commercial work. Residents may visit without charge, but they should bring proof of address. We open at eight thirty every day except Wednesday, when the centre opens at ten. Last entry is twenty minutes before closing.",
    questions:[q("Where should visitors take garden waste?",["Bay Four","Bay Seven","The main office"],"Bay Four","Garden waste should be taken to Bay Four。"),q("What must be given directly to staff?",["Glass","Small electrical items","Paint and chemicals"],"Paint and chemicals","must be handed directly to staff。"),q("What should residents bring?",["A payment card","Proof of address","A work permit"],"Proof of address","bring proof of address。"),q("What is different on Wednesday?",["The centre is free","It opens at ten","It closes twenty minutes early"],"It opens at ten","except Wednesday, when ... opens at ten。")]},
  {id:"l11",skill:"listening",section:"Part 2",title:"社区节日志愿者说明",level:"进阶",minutes:16,focus:"岗位、时间、物品",audioFile:"l11.mp3",speakers:"Event organiser",
    text:"Thank you for volunteering at Saturday's community festival. Registration opens at eight, and all volunteers should arrive by eight fifteen for a short briefing. The public enters at nine thirty. People working at the information tent will wear blue shirts; those helping with children's activities will wear green. Lunch vouchers are provided, but please bring your own water bottle. If heavy rain is expected, the outdoor music will move to the sports hall. Check your phone after seven on Saturday morning for any final change.",
    questions:[q("When should volunteers arrive?",["8:00","8:15","9:30"],"8:15","registration 与 volunteer arrival 不同。"),q("Who will wear green shirts?",["Information staff","Children's activity helpers","Music performers"],"Children's activity helpers","children's activities will wear green。"),q("What should volunteers bring?",["Lunch","A water bottle","A blue shirt"],"A water bottle","Lunch vouchers provided，但水瓶自带。"),q("Where will music move if it rains?",["The information tent","The sports hall","The community centre"],"The sports hall","move to the sports hall。")]},
  {id:"l12",skill:"listening",section:"Part 2",title:"海滨步道导览",level:"进阶",minutes:16,focus:"路线、警告、设施",audioFile:"l12.mp3",speakers:"Tour guide",
    text:"The coastal walk is six kilometres long and normally takes about two hours. From the visitor centre, follow the red signs towards Lighthouse Point. The path is narrow after the wooden bridge, so cyclists must use the lower road instead. There are toilets at the visitor centre and beside the lighthouse, but the small café is closed on Mondays. At high tide, the final beach section may be unsafe. A blue warning flag means you should return by the inland path.",
    questions:[q("How long does the walk usually take?",["One hour","Two hours","Six hours"],"Two hours","six kilometres 是距离，two hours 是时间。"),q("Who must use the lower road?",["Walkers","Cyclists","Visitors with dogs"],"Cyclists","cyclists must use the lower road。"),q("What is closed on Mondays?",["The lighthouse","The toilets","The café"],"The café","small café is closed on Mondays。"),q("What does a blue flag mean?",["Use the inland return path","The café is open","The tide is low"],"Use the inland return path","blue warning flag 后给出 return by inland path。")]},
  {id:"l13",skill:"listening",section:"Part 3",title:"学生策划社区调查",level:"进阶",minutes:18,focus:"方案评价、分工、修正",audioFile:"l13.mp3",speakers:"Two students",
    text:"Leah: We need at least eighty responses for our transport survey. I thought we could stand outside the station on Friday evening. Omar: That would mainly reach commuters. We also need older residents and people who work from home. Leah: Good point. Let's use the station on Friday, the market on Saturday morning and an online form for the rest. Omar: I'll design the questions, but we should test them with five people first. Leah: Agreed. I'll contact the market manager for permission and prepare a short information sheet explaining how the data will be used.",
    questions:[q("Why is the station alone unsuitable?",["It is too expensive","It reaches mainly commuters","It closes on Friday"],"It reaches mainly commuters","mainly reach commuters。"),q("Where will they collect answers on Saturday?",["The station","The market","A community hall"],"The market","market on Saturday morning。"),q("What will Omar do first?",["Contact the manager","Design the questions","Write the information sheet"],"Design the questions","I'll design the questions。"),q("Why will they test the questions?",["To obtain permission","To check the survey before full use","To reduce the number of responses"],"To check the survey before full use","先用五人测试表示试运行。")]},
  {id:"l14",skill:"listening",section:"Part 3",title:"同事比较培训方案",level:"进阶",minutes:18,focus:"优缺点、条件、决定",audioFile:"l14.mp3",speakers:"Two colleagues",
    text:"Jin: The project management course is available online or as a two-day workshop. The online version is cheaper and we can start at any time. Sara: True, but several people said the feedback is slow. The workshop costs more, although it includes practice with a tutor. Jin: Our department can pay up to two hundred pounds, so the workshop is still possible if we cover the travel ourselves. Sara: In that case, I prefer the workshop. The next one is in Bristol on the twelfth and thirteenth of November. Jin: Let's ask the manager today because registration closes on Friday.",
    questions:[q("What is an advantage of the online course?",["Tutor practice","A flexible start","Faster feedback"],"A flexible start","can start at any time。"),q("What problem is reported with the online course?",["Slow feedback","High travel costs","No certificate"],"Slow feedback","feedback is slow。"),q("What will the department pay up to?",["£120","£200","All travel costs"],"£200","up to two hundred pounds。"),q("Which option do they prefer?",["The online course","The workshop","Neither option"],"The workshop","Sara 明确说 I prefer the workshop，Jin 随后同意行动。")]},
  {id:"l15",skill:"listening",section:"Part 4",title:"睡眠与记忆讲座",level:"进阶",minutes:20,focus:"研究结论、过程、限制",audioFile:"l15.mp3",speakers:"Lecturer",
    text:"Sleep is not simply a period of inactivity. During sleep, the brain strengthens some of the connections formed while we were awake. In one study, adults learned pairs of unfamiliar words. Half reviewed the words in the morning and were tested that evening; the others studied in the evening and were tested after a night's sleep. The second group remembered more. However, sleep did not replace practice. Participants who made an active attempt to recall each word before sleeping performed better than those who only reread the list. Researchers also warn that one good night cannot fully correct weeks of poor sleep.",
    questions:[q("What does the brain do during sleep?",["Stops forming connections","Strengthens some new connections","Learns without prior study"],"Strengthens some new connections","strengthens some of the connections。"),q("What did participants learn?",["Routes through a city","Pairs of unfamiliar words","A list of names"],"Pairs of unfamiliar words","directly stated。"),q("Which study group remembered more?",["Those tested after sleep","Those tested the same morning","Those who did not study"],"Those tested after sleep","second group studied evening and tested after sleep。"),q("What improved performance before sleep?",["Rereading only","Active recall","Listening to music"],"Active recall","active attempt to recall ... performed better。")]},
  {id:"l16",skill:"listening",section:"Part 4",title:"城市树木与降温",level:"进阶",minutes:20,focus:"机制、数据、建议",audioFile:"l16.mp3",speakers:"Lecturer",
    text:"Urban trees cool cities in two main ways. Their leaves provide shade, reducing the amount of solar energy absorbed by roads and buildings. Trees also release water vapour, which cools the surrounding air. A survey in three neighbourhoods found that streets with mature trees were up to four degrees cooler on summer afternoons. Yet planting any tree anywhere is not enough. Young trees need water during their first years, and species must suit local soil and rainfall. Planners should also avoid blocking street lights or damaging underground pipes. The strongest results come when tree planting is combined with lighter road surfaces and accessible public parks.",
    questions:[q("How do leaves reduce heat?",["By producing electricity","By providing shade","By blocking rain"],"By providing shade","shade reduces solar energy absorbed。"),q("How much cooler were some tree-lined streets?",["Up to 2 degrees","Up to 4 degrees","Exactly 6 degrees"],"Up to 4 degrees","up to four degrees。"),q("What do young trees need?",["Extra lighting","Water in their early years","Underground pipes"],"Water in their early years","need water during their first years。"),q("What combination gives the strongest result?",["Trees alone","Trees, lighter surfaces and parks","Darker roads and more lights"],"Trees, lighter surfaces and parks","最后一句列出组合措施。")]},
];
