import type { ChoiceQuestion, CourseLesson } from "./curriculum-v2";
const q = (prompt: string, options: string[], answer: string, explanation: string): ChoiceQuestion => ({ prompt, options, answer, explanation });

export const listeningBatch10: CourseLesson[] = [
  {id:"l73",skill:"listening",section:"Part 1",title:"出国旅行货币与保险咨询",level:"基础",minutes:15,focus:"目的地、金额、领取时间与保险范围",audioFile:"l73.mp3",speakers:"Travel adviser + customer",text:"Adviser: Good morning. How can I help? Customer: I am travelling abroad next Thursday and need some local currency. Adviser: Which country are you visiting? Customer: Japan, for twelve days. I would like to exchange six hundred pounds. Adviser: We can prepare the yen by four tomorrow afternoon. There is no commission for amounts above five hundred pounds. Customer: Great. Does your standard travel insurance cover lost luggage? Adviser: Yes, up to one thousand five hundred pounds, but expensive electronic devices need to be listed separately. Customer: I have one camera worth eight hundred pounds. Adviser: I will add it. Please bring your passport when you collect the currency.",questions:[q("When is the customer travelling?",["Tomorrow","Next Thursday","In twelve weeks"],"Next Thursday","顾客说明下周四出发。"),q("How much money will be exchanged?",["£500","£600","£800"],"£600","兑换金额是六百英镑。"),q("When will the currency be ready?",["By 4 p.m. tomorrow","At noon today","Next Thursday evening"],"By 4 p.m. tomorrow","顾问承诺明天下午四点前备好。"),q("Which item must be listed separately?",["The passport","The camera","The luggage"],"The camera","高价电子设备需单列，顾客有一台相机。") ]},
  {id:"l74",skill:"listening",section:"Part 2",title:"慈善步行活动安全说明",level:"进阶",minutes:16,focus:"路线、装备、补给点与紧急程序",audioFile:"l74.mp3",speakers:"Charity event organiser",text:"Welcome to the Hillside charity walk. The full route forms a twelve-kilometre loop, while the junior route is five kilometres. Both begin at the sports arena, but only the longer route crosses the narrow wooden bridge. Wear proper walking shoes and carry a waterproof layer, because the forecast includes rough weather after midday. Water is available at kilometres four and nine. The photography team will be visible in orange jackets. If you are injured, do not continue alone: call the number on your belt card and wait beside a route marker. All walkers must return their timing chip at the finish, even if they leave the event early.",questions:[q("How long is the junior route?",["4 kilometres","5 kilometres","12 kilometres"],"5 kilometres","青少年路线为五公里。"),q("Which route crosses the wooden bridge?",["Only the full route","Only the junior route","Neither route"],"Only the full route","只有长路线经过窄木桥。"),q("Where is water available?",["At kilometres 4 and 9","Only at the finish","Beside every marker"],"At kilometres 4 and 9","补水点在第四和第九公里。"),q("What must every walker return?",["A waterproof layer","The timing chip","The belt card"],"The timing chip","无论是否提前退出都要归还计时芯片。") ]},
  {id:"l75",skill:"listening",section:"Part 3",title:"讨论虚拟培训课程改版",level:"进阶",minutes:18,focus:"反馈、顺序、互动方式与评估",audioFile:"l75.mp3",speakers:"Course designer + supervisor",text:"Designer: The feedback shows that staff found the virtual safety course boring. Supervisor: The visual content was strong, but each section was too long. Designer: I suggest dividing it into six short units and adding a practical choice after every video. Supervisor: Good. The chemical-handling unit must remain first because it contains fundamental information. Designer: Agreed. We can move the fire procedure to unit three and create a final sequence task. Supervisor: What about the online forum? Designer: Keep it open for questions, but a trainer should reply within one working day. Supervisor: Let us test the new version with the junior team, collect their input, and compare completion time and error frequency.",questions:[q("What did staff dislike?",["The visual design","The course was boring","The chemical content"],"The course was boring","反馈认为课程无聊，但视觉内容不错。"),q("What will follow each video?",["A practical choice","A written petition","A live interview"],"A practical choice","每段视频后增加实际选择题。"),q("Which unit must remain first?",["Fire procedure","Chemical handling","Customer service"],"Chemical handling","该单元包含基础安全信息。"),q("Who will test the new version?",["The junior team","Overseas customers","The finance bureau"],"The junior team","先由初级团队试用并收集意见。") ]},
  {id:"l76",skill:"listening",section:"Part 4",title:"高密度城市中的公共健康",level:"模考",minutes:19,focus:"因果关系、证据限制与综合政策",audioFile:"l76.mp3",speakers:"Public health lecturer",text:"High population density is often regarded as a health risk, but density alone does not define the outcome. Compact neighbourhoods can support frequent public transport, nearby clinics and daily walking. Problems arise when housing is overcrowded, ventilation is poor and green space is scarce. These are distinct conditions, although they may occur together. Research also shows that social connection can protect mental health. A busy district with active community groups may therefore produce better results than a lower-density area where residents feel isolated. Effective policy combines decent housing standards, visible public space, clean transport and access to care. It must also examine equity: an average improvement can hide severe conditions in one ward. The principle is simple. Measure the actual living environment, not only the number of people within a square kilometre.",questions:[q("What can compact neighbourhoods support?",["Frequent public transport","Permanent isolation","Lower service frequency"],"Frequent public transport","紧凑社区可支持公交、诊所和步行。"),q("When does density become harmful?",["When housing and services are poor","Whenever people walk daily","When community groups are active"],"When housing and services are poor","问题来自拥挤住房、差通风和缺少绿地。"),q("What may protect mental health?",["Social connection","A higher average only","Longer highways"],"Social connection","研究显示社会联系具有保护作用。"),q("What should authorities measure?",["Only people per square kilometre","The actual living environment","Only city revenue"],"The actual living environment","结论要求衡量真实生活环境，而非单一密度。") ]},
];

export const readingBatch10: CourseLesson[] = [
  {id:"r73",skill:"reading",section:"Section 1",title:"市中心手工艺市场摊位申请",level:"基础",minutes:16,focus:"资格、费用、设备与截止日期",text:"RIVER AVENUE CRAFT MARKET\nApplications are open for the autumn market on 14 September. Stalls are available to independent makers selling genuine handmade products; imported mass-produced goods and food are not accepted. The standard fee is £35, including one table and two chairs. Electricity costs an additional £8 and must be requested on the application. Each stallholder must provide evidence of public liability insurance. Submit three clear photographs of your products and a short description of your craft by 20 August. Successful applicants will receive a pitch number by email on 27 August. Fees are due only after a place is confirmed.",questions:[q("Who may apply?",["Independent makers","Food franchises","Any overseas factory"],"Independent makers","市场面向销售真实手工产品的独立创作者。"),q("What is included in the standard fee?",["Electricity","One table and two chairs","Public insurance"],"One table and two chairs","三十五英镑包含桌椅。"),q("What must accompany the application?",["Three product photographs","A timing chip","A medical letter"],"Three product photographs","需提交三张清晰产品照片和工艺说明。"),q("When are fees paid?",["Before applying","After a place is confirmed","On 20 August"],"After a place is confirmed","摊位确认后才付款。") ]},
  {id:"r74",skill:"reading",section:"Section 2",title:"实验室化学品泄漏程序",level:"进阶",minutes:18,focus:"隔离、个人防护、清理权限与记录",text:"MINOR CHEMICAL SPILL PROCEDURE\nFirst identify the substance from a safe distance and warn everyone nearby. If the label is missing, the liquid is producing gas, or anyone has intense symptoms, leave the laboratory, close the door and call the emergency number. Do not attempt a clean-up. For a known minor spill, trained staff should put on the protective kit stated in the safety sheet, place warning signs at each entrance and prevent the liquid from reaching a drain. Use the correct absorbent material; water may cause some chemicals to react. Collect waste in a labelled container and report the incident before the end of the shift. A supervisor must investigate the cause and replace every item used from the spill kit.",questions:[q("When must the laboratory be left?",["When the substance is unknown","After every small water spill","Only at the end of a shift"],"When the substance is unknown","缺标签、产生气体或出现强烈症状时必须撤离。"),q("Who may clean a known minor spill?",["Any visitor","Trained staff","Only customers"],"Trained staff","只有受训人员按安全表操作。"),q("Why might water be unsuitable?",["It may react with a chemical","It removes warning signs","It always reaches the roof"],"It may react with a chemical","部分化学品遇水会反应。"),q("What must the supervisor do?",["Investigate the cause","Hide the incident","Cancel all training"],"Investigate the cause","主管需调查原因并补齐使用过的物品。") ]},
  {id:"r75",skill:"reading",section:"Section 2",title:"员工丧亲与葬礼假期政策",level:"进阶",minutes:18,focus:"适用关系、天数、额外安排与隐私",text:"COMPASSIONATE LEAVE\nAn employee may take up to five paid working days after the death of a spouse, partner, child, parent or another person who belonged to the employee's household. One paid day is available to attend the funeral of another close relative. Tell your manager as soon as reasonably possible and give a rough indication of the dates needed. The company will not normally request formal evidence. If overseas travel, legal affairs or cultural customs require more time, employees may request annual leave, unpaid leave or a temporary change of shift. Managers should consider each request with sensitivity and keep personal information confidential. Compassionate leave is separate from sickness absence, although counselling support remains available through the wellbeing service.",questions:[q("Who can qualify for up to five paid days?",["A member of the employee's household","Any former customer","Every distant acquaintance"],"A member of the employee's household","家庭成员属于五天带薪假适用范围。"),q("How much leave is available for another close relative's funeral?",["One paid day","Five unpaid weeks","No leave"],"One paid day","其他近亲葬礼可获一天带薪假。"),q("What evidence is normally required?",["A court order","No formal evidence","A travel ticket"],"No formal evidence","公司通常不要求正式证明。"),q("What may be requested for overseas travel?",["A shift change","A lower salary","A new job title"],"A shift change","可申请年假、无薪假或临时换班。") ]},
  {id:"r76",skill:"reading",section:"Section 3",title:"博物馆如何面对争议遗产",level:"模考",minutes:23,focus:"立场、证据、展示方法与公众参与",text:"Museums once presented historic objects as if their meaning were fixed. Contemporary practice is more likely to reveal how an object was collected, who created it and which voices were ignored. This change is especially visible when collections contain items acquired through colonial power or violence.\n\nSome critics demand that every disputed object be returned to its place of origin. Others argue that international galleries allow a vast audience to compare cultures. The strongest cases avoid a simple formula. Ownership records, the wishes of source communities, legal agreements and an object's spiritual importance all matter. Return may be justified in one case, while a long-term loan or joint exhibition may be better in another.\n\nLabels are also changing. A brief title and date cannot capture a complex legacy. Museums increasingly invite input from ethnic communities and display several interpretations together. This may feel awkward to visitors expecting one authoritative account, but uncertainty can be intellectually honest.\n\nThe aim is not to destroy public trust. It is to build genuine trust through evidence, transparency and dialogue. A museum succeeds when it treats collections not as silent trophies but as part of an ongoing public affair.",questions:[q("What change has occurred in museum practice?",["More attention is given to origin and ignored voices","Objects are shown without labels","Every collection is kept private"],"More attention is given to origin and ignored voices","当代展示更重视来源、创作者及被忽视的声音。"),q("Why does the writer reject one simple rule?",["Different evidence and community wishes matter","Legal records never exist","All objects have equal spiritual value"],"Different evidence and community wishes matter","归还、借展或联合展示要依据具体证据。"),q("Why might new labels feel awkward?",["They present several interpretations","They contain no dates","They advertise food"],"They present several interpretations","习惯单一权威答案的访客可能不适应多种解释。"),q("How should museums build trust?",["Through evidence and dialogue","By hiding uncertainty","By ignoring source communities"],"Through evidence and dialogue","末段明确提出证据、透明和对话。") ]},
];

const task1Checklist=["开头直接说明写信目的","覆盖三个任务点并提供具体事实","语气符合正式或私人关系","至少 150 词并检查分段、时态和拼写"];
const task2Checklist=["引言明确回应题目并给出立场","主体段包含中心句、解释和例子","处理比较、因果或让步","至少 250 词且结论不加入新观点"];
export const writingBatch10: CourseLesson[] = [
  {id:"w73",skill:"writing",section:"Task 1 · 正式信",title:"申请手工艺市场摊位",level:"进阶",minutes:26,focus:"介绍产品、说明设备需求与询问安排",task:"You want to sell handmade products at a local craft market. Write a letter to the organiser. Write at least 150 words.",bullets:["describe your products and relevant experience","explain what equipment or space you need","ask about selection, payment and arrival arrangements"],checklist:task1Checklist},
  {id:"w74",skill:"writing",section:"Task 1 · 私人信",title:"感谢朋友帮助完成培训",level:"基础",minutes:25,focus:"说明困难、具体帮助与成果",task:"A friend helped you prepare for an important training course which you have now completed. Write a letter to your friend. Write at least 150 words.",bullets:["explain why the course was important","describe the help your friend gave","say how you will celebrate your achievement"],checklist:task1Checklist},
  {id:"w75",skill:"writing",section:"Task 2 · 观点",title:"公共资金是否应支持艺术",level:"模考",minutes:42,focus:"公共价值、基本服务与资金原则",task:"Governments should spend money on essential public services rather than on arts and cultural activities. To what extent do you agree or disagree? Write at least 250 words.",bullets:["define essential needs and cultural value","consider access, education and local commerce","state a clear funding principle"],checklist:task2Checklist},
  {id:"w76",skill:"writing",section:"Task 2 · 双边讨论",title:"出国学习还是本地学习",level:"模考",minutes:42,focus:"教育质量、成本、独立性与公平",task:"Some people believe students gain more by studying abroad, while others think it is better to study in their own country. Discuss both views and give your opinion. Write at least 250 words.",bullets:["compare academic and cultural benefits","examine cost, access and personal readiness","give a reasoned judgement rather than an absolute rule"],checklist:task2Checklist},
];

export const speakingBatch10: CourseLesson[] = [
  {id:"s73",skill:"speaking",section:"Part 1",title:"博物馆与美术馆",level:"基础",minutes:10,focus:"频率、偏好、体验与原因",prompts:["Do you often visit a museum or gallery?","What kind of visual art do you enjoy?","Did you visit museums as a junior student?","What makes an exhibition memorable?"],keywords:["gallery","visual","historic","atmosphere"]},
  {id:"s74",skill:"speaking",section:"Part 2",title:"一次值得庆祝的成就",level:"进阶",minutes:14,focus:"背景、努力、结果与感受",task:"Describe an achievement that you celebrated.",bullets:["what the achievement was","what effort or sacrifice it required","who celebrated with you","why you felt grateful"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["achievement","effort","sacrifice","grateful"]},
  {id:"s75",skill:"speaking",section:"Part 3",title:"城市密度与生活质量",level:"模考",minutes:16,focus:"住房、交通、健康与公平",prompts:["What are the benefits of higher population density?","When does dense housing damage health?","How can cities foster stronger social connection?","Why should planners examine equity between different wards?"],keywords:["density","vital","foster","equity"]},
  {id:"s76",skill:"speaking",section:"Part 3",title:"文化遗产归属与展示",level:"模考",minutes:16,focus:"所有权、公众利益、证据与协商",prompts:["Why do historic objects become controversial?","Should every object be returned to its place of origin?","How can museums include ethnic diversity in exhibitions?","What creates genuine trust in cultural institutions?"],keywords:["legacy","origin","diversity","genuine"]},
];
export const curriculumBatch10: CourseLesson[]=[...listeningBatch10,...readingBatch10,...writingBatch10,...speakingBatch10];
