import type { ChoiceQuestion, CourseLesson } from "./curriculum-v2";

const q = (prompt: string, options: string[], answer: string, explanation: string): ChoiceQuestion => ({ prompt, options, answer, explanation });
export const listeningBatch08: CourseLesson[] = [
  {id:"l65",skill:"listening",section:"Part 1",title:"领取处方药并确认剂量",level:"基础",minutes:15,focus:"身份核实、剂量、过敏与取药时间",audioFile:"l65.mp3",speakers:"Pharmacist + patient",text:"Pharmacist: Good afternoon. How can I help? Patient: I am here to collect a repeat prescription for Mina Dorj. Pharmacist: Could you confirm your date of birth? Patient: The seventeenth of September, nineteen eighty-eight. Pharmacist: Thank you. The tablets are ready, but the asthma inhaler will arrive after four thirty. Take one tablet twice a day with food. Patient: I am allergic to penicillin. Pharmacist: That is already shown on your record. This medication does not contain it. If you develop swelling or difficulty breathing, stop taking it and seek urgent medical help. Patient: I will return for the inhaler at five.",questions:[q("What is the patient's date of birth?",["17 September 1988","7 September 1988","17 November 1988"],"17 September 1988","患者逐项确认了日期和年份。"),q("Which item is not ready yet?",["The tablets","The asthma inhaler","The prescription form"],"The asthma inhaler","药片已好，吸入器四点半后到。"),q("How often should the tablets be taken?",["Once a day","Twice a day","Three times a day"],"Twice a day","原文直接说 one tablet twice a day。"),q("When will the patient return?",["4:00","4:30","5:00"],"5:00","患者最后说明五点回来。") ]},
  {id:"l66",skill:"listening",section:"Part 2",title:"市政厨余回收登记说明",level:"进阶",minutes:16,focus:"资格、容器、收集日与禁投物",audioFile:"l66.mp3",speakers:"Municipal recycling officer",text:"Residents in the western district can now register for weekly food-waste collection. Each eligible household receives a small kitchen container and a larger outdoor bin without charge. Register online by the twenty-sixth of April, or telephone the council if you need an accessible form. Deliveries begin on the sixth of May, and Tuesday will be the regular collection day. Put fruit, vegetables, cooked food and tea bags in the bin. Do not include plastic packaging, liquids or garden waste. Close the outdoor bin securely and leave it beside your usual rubbish bin before seven in the morning.",questions:[q("Who can register?",["Every business","Households in the western district","Only garden owners"],"Households in the western district","服务对象是 western district 的居民家庭。"),q("How much do the containers cost?",["Nothing","Six pounds","Twenty-six pounds"],"Nothing","两个容器均 without charge。"),q("What is the regular collection day?",["Monday","Tuesday","Thursday"],"Tuesday","原文明确 Tuesday。"),q("Which item must not be included?",["Tea bags","Cooked food","Plastic packaging"],"Plastic packaging","塑料包装属于禁投物。") ]},
  {id:"l67",skill:"listening",section:"Part 3",title:"讨论工作场所安全入职培训",level:"进阶",minutes:18,focus:"强制内容、形式比较、反馈与决定",audioFile:"l67.mp3",speakers:"Training manager + supervisor",text:"Manager: We need to revise the orientation for temporary warehouse staff. Supervisor: The current presentation is accurate, but ninety minutes is too long. Could the manual-handling section become a practical demonstration? Manager: Yes. That part is mandatory, along with fire procedures and reporting a hazard. Supervisor: What about the online quiz? Manager: Keep it, but allow staff to complete it before their first shift. We should also ask for feedback after one week, when they have actually used the equipment. Supervisor: Agreed. I will arrange a thirty-minute demonstration, and you can update the digital module. Manager: Let us evaluate the new format after the first two groups.",questions:[q("What problem does the supervisor identify?",["The information is inaccurate","The presentation is too long","The room is too small"],"The presentation is too long","主管认可内容准确，但认为九十分钟过长。"),q("Which section will become practical?",["Manual handling","Payroll","Customer feedback"],"Manual handling","双方决定把搬运内容改为示范。"),q("When should staff give feedback?",["Before applying","After one week","After one year"],"After one week","实际使用设备一周后再反馈。"),q("When will the format be evaluated?",["After two groups","Before the first shift","Every Friday"],"After two groups","经理最后提出前两组结束后评估。") ]},
  {id:"l68",skill:"listening",section:"Part 4",title:"租赁房屋物品清单与退租检查",level:"模考",minutes:19,focus:"证据、责任、押金与争议解决",audioFile:"l68.mp3",speakers:"Housing adviser",text:"A detailed inventory protects both a tenant and a landlord. At the start of a lease, inspect every room and compare its condition with the written list. Record stains, broken handles and missing items, even when the damage seems minor. Take dated photographs and submit corrections within the period stated in the agreement, which is often seven days. Before leaving, clean the property, remove personal belongings and ask how keys should be returned. Normal wear should not be charged against the deposit, but new damage may be. If you disagree with a deduction, first request the inspection evidence and the landlord's cost estimate. A deposit-protection service can then provide independent dispute resolution.",questions:[q("When should the inventory be checked?",["At the start of the lease","Only after moving out","After the deposit dispute"],"At the start of the lease","入住开始时逐房间核对。"),q("What evidence should a tenant create?",["Undated notes only","Dated photographs","A new lease"],"Dated photographs","讲者明确建议拍有日期的照片。"),q("What may be deducted from the deposit?",["Normal wear","New damage","Every missing receipt"],"New damage","正常损耗不应扣，新损坏可能扣。"),q("What should be requested before formal resolution?",["Inspection evidence and a cost estimate","A new property","A police license"],"Inspection evidence and a cost estimate","争议第一步是索取检查证据和估价。") ]},
];

export const readingBatch08: CourseLesson[] = [
  {id:"r65",skill:"reading",section:"Section 1",title:"道路封闭与居民停车许可通知",level:"基础",minutes:16,focus:"日期、范围、绕行与申请条件",text:"TEMPORARY ROAD CLOSURE\nKing Street will close to through traffic from 7 a.m. on Monday 12 August until 6 p.m. on Friday 16 August while the council repairs the junction. Pedestrian access to homes and shops will remain open. Bus route 14 will use Market Road, so stops K3 and K4 will not operate. Residents whose vehicles are normally parked inside the closed section may apply for a temporary permit to use the library car park. Submit the online form with proof of address and your vehicle registration by 5 p.m. on 8 August. One permit is available per household. Emergency vehicles and scheduled waste collections will retain access.",questions:[q("Why is King Street closing?",["For a market","For junction repairs","For a school event"],"For junction repairs","首句说明市政维修路口。"),q("Which access will remain open?",["Through traffic","Pedestrian access","Stops K3 and K4"],"Pedestrian access","住宅和商店的步行通道保持开放。"),q("Where may eligible residents park?",["The library car park","Market Road bus stops","The closed junction"],"The library car park","临时许可对应图书馆停车场。"),q("What must accompany the form?",["A medical prescription","Proof of address and vehicle registration","A waste container"],"Proof of address and vehicle registration","申请需两项证明。") ]},
  {id:"r66",skill:"reading",section:"Section 2",title:"员工差旅费用报销政策",level:"进阶",minutes:18,focus:"资格、证据、限额与审批",text:"TRAVEL EXPENSE POLICY\nEmployees may claim necessary travel costs incurred while carrying out approved duties away from their usual workplace. Obtain your manager's approval before booking overnight accommodation. Use standard rail fares unless a documented accessibility need requires another option. Private-car mileage is reimbursed at the published rate, but ordinary travel between home and work is not eligible. Submit the expense form within 30 days of the journey and attach itemised receipts; a card statement alone is not proof of purchase. Meals are covered only during an overnight trip and remain subject to daily limits. Finance may return an incomplete claim for correction. Approved expenses are normally paid with the next salary.",questions:[q("When is advance approval required?",["Before booking overnight accommodation","Before commuting home","After every meal"],"Before booking overnight accommodation","住宿预订前需要经理批准。"),q("Which journey is not eligible?",["Approved business travel","The normal home-to-work commute","A required accessible journey"],"The normal home-to-work commute","普通通勤明确排除。"),q("What evidence is required?",["Itemised receipts","Only a card statement","A colleague's estimate"],"Itemised receipts","银行卡流水不能替代明细收据。"),q("When are approved expenses usually paid?",["Immediately in cash","With the next salary","After one year"],"With the next salary","政策末句给出支付时间。") ]},
  {id:"r67",skill:"reading",section:"Section 2",title:"医院门诊检查准备指引",level:"进阶",minutes:18,focus:"报到、用药、饮食与出院安全",text:"OUTPATIENT PROCEDURE INSTRUCTIONS\nReport to East Reception 30 minutes before your appointment and bring photo identification, your referral letter and a current medication list. Continue prescribed medication unless the clinic has given explicit instructions to stop. Do not eat for six hours before the procedure; clear water is permitted until two hours beforehand. Notify the unit in advance if you have diabetes, asthma, an allergy or a recent infection. A nurse will complete a preliminary assessment and ask for your consent. Because the medication used during the procedure may cause temporary fatigue, you must arrange for a responsible adult to take you home. You should not drive, operate machinery or sign legal documents until the following morning.",questions:[q("How early should a patient report?",["Two hours","Thirty minutes","Six hours"],"Thirty minutes","报到时间是预约前 30 分钟。"),q("What may be consumed until two hours beforehand?",["A full meal","Clear water","Milk"],"Clear water","禁食六小时，但清水可到前两小时。"),q("Which condition should be reported?",["Asthma","A preferred seat","A parking discount"],"Asthma","糖尿病、哮喘、过敏或近期感染都要报告。"),q("Why must another adult take the patient home?",["The hospital closes early","Medication may cause fatigue","The referral is invalid"],"Medication may cause fatigue","用药可能造成暂时疲劳。") ]},
  {id:"r68",skill:"reading",section:"Section 3",title:"城市如何同时管理洪水与自然栖息地",level:"模考",minutes:22,focus:"因果、方案比较、共同收益与限制",text:"For decades, many cities treated flood water as something to remove as quickly as possible through concrete drains. This approach can protect one district, yet it may transfer a larger volume downstream and increase pressure on ageing infrastructure. Climate change is also making extreme rainfall less predictable.\n\nAn alternative is to create space where water can slow down. Parks can include shallow basins that remain usable in dry weather, while restored wetlands store water during storms. Permeable paving allows some rain to enter the soil instead of flowing directly into drains. These measures may reduce flood risk and create habitat, shade and cleaner air.\n\nHowever, attractive language does not guarantee a successful project. Designers must examine local soil, maintenance costs and the needs of neighboring residents. A wetland without reliable water flow can become polluted, and poorly located planting may obstruct paths. Municipal authorities therefore need clear monitoring criteria, including water levels, biodiversity and whether protection reaches lower-income areas.\n\nThe strongest strategy combines natural measures with maintained drains, accurate forecasts and emergency alerts. It does not assume that a single park can prevent every flood. Its advantage is that public space can provide daily value while also preparing the city for rare but serious events.",questions:[q("What can happen when water is removed too quickly?",["Downstream pressure may increase","Rain becomes predictable","All drains become new"],"Downstream pressure may increase","第一段指出风险可能转移到下游。"),q("What does permeable paving do?",["Blocks every footpath","Lets some rain enter soil","Creates more concrete runoff"],"Lets some rain enter soil","第二段直接解释其作用。"),q("What should monitoring include?",["Only construction speed","Water, biodiversity and fair protection","The colour of warning signs"],"Water, biodiversity and fair protection","第三段列出三类评估指标。"),q("What is the writer's preferred approach?",["Only natural parks","Only larger drains","Natural measures plus maintained systems and alerts"],"Natural measures plus maintained systems and alerts","末段主张组合策略。") ]},
];

const task1Checklist = ["开头直接说明写信目的", "三个任务点都有具体事实、请求或安排", "语气符合正式或半正式关系", "至少 150 词并检查时态、拼写和分段"];
const task2Checklist = ["引言回应题目并明确立场", "主体段有中心句、解释和具体例子", "比较、因果或让步关系清楚", "至少 250 词且结论不加入新观点"];

export const writingBatch08: CourseLesson[] = [
  {id:"w65",skill:"writing",section:"Task 1 · 正式信",title:"要求更正错误发票",level:"进阶",minutes:26,focus:"说明交易、指出错误与要求解决",task:"A supplier has sent your workplace an incorrect invoice for a recent delivery. Write a letter to the supplier. Write at least 150 words.",bullets:["identify the delivery and invoice","explain each error accurately","request a corrected invoice and confirm the payment deadline"],checklist:task1Checklist},
  {id:"w66",skill:"writing",section:"Task 1 · 半正式信",title:"请求调整加班安排",level:"进阶",minutes:26,focus:"说明现有安排、原因与替代方案",task:"Your manager has arranged overtime for you, but the time creates a serious difficulty. Write a letter to your manager. Write at least 150 words.",bullets:["refer to the overtime arrangement","explain why you cannot attend at that time","suggest a practical substitute and ask for approval"],checklist:task1Checklist},
  {id:"w67",skill:"writing",section:"Task 2 · 观点",title:"市政资金应优先公共交通吗",level:"模考",minutes:42,focus:"比较基础设施、拥堵、公平与成本",task:"Municipal authorities should spend more money on public transport than on building new roads. To what extent do you agree or disagree? Write at least 250 words.",bullets:["state the extent of agreement","compare congestion, access and economic needs","explain which investment criteria should determine priorities"],checklist:task2Checklist},
  {id:"w68",skill:"writing",section:"Task 2 · 双重问题",title:"预防慢性疾病是谁的责任",level:"模考",minutes:42,focus:"分析个人选择、公共服务与有效措施",task:"Chronic health problems are increasing in many countries. Why is this happening, and who should be mainly responsible for prevention? Write at least 250 words.",bullets:["explain several connected causes","compare individual, employer and government responsibility","recommend realistic preventive measures"],checklist:task2Checklist},
];

export const speakingBatch08: CourseLesson[] = [
  {id:"s65",skill:"speaking",section:"Part 1",title:"填写表格与在线服务",level:"进阶",minutes:10,focus:"频率、困难、偏好与可靠性",prompts:["How often do you fill in forms online?","Which details are most difficult to remember?","Do you prefer online or face-to-face services?","What makes an online service reliable?"],keywords:["usually","accurate","prefer","reliable"]},
  {id:"s66",skill:"speaking",section:"Part 2",title:"参加过的一次社区活动",level:"进阶",minutes:14,focus:"活动、角色、合作与结果",task:"Describe a community activity in which you participated or volunteered.",bullets:["what the initiative was","what your role involved","how people collaborated","what outcome the activity achieved"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["initiative","volunteer","collaboration","outcome"]},
  {id:"s67",skill:"speaking",section:"Part 3",title:"城市发展与自然环境",level:"模考",minutes:16,focus:"比较住房、交通、洪水与栖息地",prompts:["Why do growing cities often lose natural habitat?","How can urban design reduce flood risk?","Should every district receive the same environmental investment?","How can authorities evaluate whether a project works?"],keywords:["urban","habitat","flood","evaluate"]},
  {id:"s68",skill:"speaking",section:"Part 3",title:"工作培训与员工权益",level:"模考",minutes:16,focus:"强制培训、试用期、加班与补偿",prompts:["Which workplace training should be mandatory?","How should employers support staff during probation?","When is overtime reasonable?","What compensation should workers receive for extra duties?"],keywords:["mandatory","probation","overtime","compensation"]},
];

export const curriculumBatch08: CourseLesson[] = [...listeningBatch08, ...readingBatch08, ...writingBatch08, ...speakingBatch08];
