import type { ChoiceQuestion, CourseLesson } from "./curriculum-v2";

const q = (prompt: string, options: string[], answer: string, explanation: string): ChoiceQuestion => ({ prompt, options, answer, explanation });

export const listeningBatch06: CourseLesson[] = [
  { id:"l49", skill:"listening", section:"Part 1", title:"预约家电上门维修", level:"基础", minutes:15, focus:"型号、故障、时段与费用", audioFile:"l49.mp3", speakers:"Repair agent + customer",
    text:"Agent: Bright Home Repairs. Customer: My washing machine stops before the final spin. Agent: What make and model is it? Customer: A Henson W four twenty, bought three years ago. Agent: We can visit on Tuesday between nine and twelve, or Wednesday between two and five. Customer: Tuesday morning, please. Agent: The call-out fee is thirty-eight pounds. Parts are extra, but the engineer will give a price before fitting anything. Customer: Fine. The address is 18 Willow Close, flat three. Agent: Your reference is R M six one.",
    questions:[q("What problem does the washing machine have?",["It will not fill","It stops before the final spin","Its door is missing"],"It stops before the final spin","客户说机器在最后脱水前停止。"),q("Which appointment does the customer choose?",["Tuesday 9–12","Tuesday 2–5","Wednesday 9–12"],"Tuesday 9–12","客户选择 Tuesday morning。"),q("How much is the call-out fee?",["£18","£38","£61"],"£38","上门基础费是三十八英镑。"),q("What is the booking reference?",["RM16","RM61","WM42"],"RM61","客服最后给出 R M six one。")] },
  { id:"l50", skill:"listening", section:"Part 1", title:"报名社区急救课", level:"基础", minutes:15, focus:"日期、资格、用品与付款", audioFile:"l50.mp3", speakers:"Course assistant + caller",
    text:"Assistant: Eastside Training Centre. Caller: I want to join the basic first-aid course. Assistant: The next Saturday course is on the seventeenth of September from ten until four. Caller: Do I need any experience? Assistant: No. It is for beginners aged sixteen or over. The fee is fifty-two pounds, including the workbook and practice materials. Bring lunch and wear comfortable clothes. Caller: Can I pay on the day? Assistant: We need a twenty-pound deposit by Thursday. I will email the payment link to kai dot bat at mail dot com.",
    questions:[q("On what date is the course?",["7 September","17 September","27 September"],"17 September","课程在九月十七日。"),q("Who may attend?",["Only experienced staff","Beginners aged 16 or over","Children under 16"],"Beginners aged 16 or over","无需经验，但须年满十六岁。"),q("What is included in the fee?",["Lunch","Travel","A workbook and practice materials"],"A workbook and practice materials","教材和练习材料包含在费用中。"),q("What deposit is required for the first-aid course?",["£20","£32","£52"],"£20","周四前支付二十英镑订金。") ] },
  { id:"l51", skill:"listening", section:"Part 2", title:"露营地到达说明", level:"进阶", minutes:16, focus:"登记、营位、用火与安静时段", audioFile:"l51.mp3", speakers:"Campsite manager",
    text:"Welcome to Pine Field Campsite. Arrivals before six should check in at reception; later arrivals must collect a labelled envelope from the box beside Gate Two. Your pitch number is shown on the map inside. Park one car beside your tent and leave any second vehicle in the gravel car park. Raised gas stoves are permitted, but open fires and disposable barbecues are not. Drinking water points are marked blue. The shower block is cleaned from eleven until midday, when the accessible bathroom remains available. Quiet hours begin at ten thirty. If you leave before reception opens, return your gate card through the office letter slot.",
    questions:[q("Where do late arrivals collect their information?",["Inside the shower block","From a box beside Gate Two","At the gravel car park"],"From a box beside Gate Two","晚到者从二号门旁箱子取有标签的信封。"),q("Where must a second vehicle be left?",["Beside the tent","In the gravel car park","Outside Gate Two"],"In the gravel car park","营位旁只许一辆车。"),q("Which cooking equipment is allowed?",["An open fire","A disposable barbecue","A raised gas stove"],"A raised gas stove","只允许架高的燃气炉。"),q("When do quiet hours start?",["10:00","10:30","11:00"],"10:30","安静时段十点半开始。") ] },
  { id:"l52", skill:"listening", section:"Part 2", title:"博物馆夜间活动须知", level:"进阶", minutes:16, focus:"入口、寄存、活动预约与离场", audioFile:"l52.mp3", speakers:"Museum host",
    text:"Tonight's museum programme begins at seven. Please enter through the River Door because the main steps are closed for repair. Large bags must be left in the free lockers on the lower ground floor; you will need a one-pound coin, which is returned. The photography talk in Gallery Four has open seating, but the conservation workshop requires the yellow ticket included with selected bookings. Food is available in the courtyard until nine, while drinks must not enter exhibition rooms. The final short tour leaves the clock hall at nine fifteen. Everyone must leave by the River Door at ten.",
    questions:[q("Which entrance should visitors use?",["The main steps","The River Door","Gallery Four"],"The River Door","主台阶维修，访客使用 River Door。"),q("What is needed to operate a locker?",["A £1 coin","A yellow ticket","A bank card"],"A £1 coin","一英镑硬币会在取物时退回。"),q("Which activity requires a special ticket?",["The photography talk","The conservation workshop","The final short tour"],"The conservation workshop","修复工作坊须出示黄色票。"),q("When does the final short tour leave?",["9:00","9:15","10:00"],"9:15","最后短导览九点十五出发。") ] },
  { id:"l53", skill:"listening", section:"Part 3", title:"评估办公室照明研究", level:"进阶", minutes:17, focus:"研究对象、测量、变量与报告", audioFile:"l53.mp3", speakers:"Tutor + two trainees",
    text:"Tutor: Which office will you study? Mina: The customer-support floor because staff use screens throughout the day. Taro: We first planned to compare it with the warehouse. Tutor: The work is too different. Compare the east and west sides of the same floor instead. Mina: We will measure light at nine, one and four. Taro: And ask staff about headaches and eye strain. Tutor: Good, but record whether blinds are open and whether desks are beside a window. Do not collect employee names. Mina: We will present the light readings in a line graph and summarise anonymous comments by theme.",
    questions:[q("Which workplace will be studied?",["The warehouse","The customer-support floor","The reception lobby"],"The customer-support floor","研究对象是全天使用屏幕的客服楼层。"),q("What comparison does the tutor recommend?",["Two sides of one floor","Office and warehouse","Morning and night shifts"],"Two sides of one floor","导师认为岗位差异太大，应比较同楼层东西两侧。"),q("Which factor must the trainees record?",["Employee salaries","Whether blinds are open","Staff home addresses"],"Whether blinds are open","窗帘状态会影响光照。"),q("How will light readings be presented?",["In a line graph","As named interviews","In a floor photograph"],"In a line graph","Mina 明确提出用折线图。") ] },
  { id:"l54", skill:"listening", section:"Part 3", title:"策划社区树木调查", level:"进阶", minutes:17, focus:"抽样、记录、居民意见与分工", audioFile:"l54.mp3", speakers:"Tutor + two students",
    text:"Tutor: Tell me about your neighbourhood tree survey. Student one: We wanted to record every tree in the district. Tutor: That is too large. Select four streets with different traffic levels. Student two: For each tree we will note the species, trunk condition and distance from the road. Student one: I can photograph the leaves, but faces and house numbers must not appear. Tutor: Correct. Interview residents about shade and fallen branches, not whether they simply like trees. Student two: I will create the map, and my partner will check the identification guide. Tutor: Submit your raw table with the report so I can see how conclusions were reached.",
    questions:[q("How many streets will be sampled?",["Two","Four","Every street"],"Four","导师将范围缩小为四条不同交通量的街道。"),q("What will be recorded for every tree?",["The house owner","Its distance from the road","The price of the land"],"Its distance from the road","树种、树干情况和离道路距离均须记录。"),q("What must photographs avoid?",["Leaves","Traffic","Faces and house numbers"],"Faces and house numbers","隐私要求是不拍到人脸和门牌。"),q("What must accompany the report?",["The raw data table","A resident list","A new camera"],"The raw data table","导师要求提交原始表格以核查推论。") ] },
  { id:"l55", skill:"listening", section:"Part 4", title:"住宅保温与实际节能", level:"模考", minutes:18, focus:"技术效果、住户行为、反弹效应与评估", audioFile:"l55.mp3", speakers:"Energy researcher",
    text:"Home insulation reduces the heat that escapes through roofs, walls and floors, but predicted savings are not always achieved. Before improvement, some households heat only one room or tolerate low temperatures because energy is expensive. After insulation, they may choose a warmer and more comfortable home instead of using much less fuel. Researchers call this a rebound effect, although improved comfort is still a real benefit. Installation quality also matters: gaps around loft doors or poorly fitted wall material reduce performance. Reliable evaluation therefore combines energy bills with indoor temperature readings and interviews about heating routines. Comparing bills alone can be misleading when weather or household size changes.",
    questions:[q("Why may fuel savings be smaller than predicted?",["Residents may choose warmer homes","Insulation always raises prices","Roofs produce heat"],"Residents may choose warmer homes","部分住户把收益用于提高室温，而非全部节省燃料。"),q("What is the rebound effect in this context?",["A wall becoming thicker","Using some efficiency gain for more comfort","Changing energy supplier"],"Using some efficiency gain for more comfort","效率提升后增加舒适度就是文中反弹效应。"),q("What can reduce insulation performance?",["Accurate temperature readings","Gaps around loft doors","Household interviews"],"Gaps around loft doors","施工缝隙会降低效果。"),q("Why are bills alone insufficient?",["Bills contain no numbers","Weather and household size can change","Every home uses the same energy"],"Weather and household size can change","费用还受到天气和家庭人数影响。") ] },
  { id:"l56", skill:"listening", section:"Part 4", title:"城市货运集中配送", level:"模考", minutes:18, focus:"末端配送、成本、装载率与政策条件", audioFile:"l56.mp3", speakers:"Urban planning lecturer",
    text:"City-centre shops often receive separate deliveries from many suppliers, creating repeated van journeys on crowded streets. An urban consolidation centre receives goods at an edge-of-city warehouse, combines them and sends fewer, fuller vehicles to the centre. Electric vans or cargo bicycles can then reduce local noise and pollution. The model is not automatically cheaper. Goods must be handled an extra time, and small businesses may need rapid deliveries that are difficult to combine. Successful schemes define reliable delivery windows, share digital tracking and charge users fairly. Evaluators should measure vehicle kilometres and loading rates, not merely count deliveries, because one poorly loaded large vehicle may offer little improvement.",
    questions:[q("What happens at a consolidation centre?",["Customers collect all goods","Deliveries are combined into fuller vehicles","Shops manufacture products"],"Deliveries are combined into fuller vehicles","仓库汇集货物后用更少、更满的车辆配送。"),q("Which vehicle can reduce local noise?",["An electric van","An empty lorry","A private taxi"],"An electric van","电动货车或货运自行车可降低本地噪声。"),q("What challenge is mentioned for small businesses?",["They never require goods","Rapid deliveries can be hard to combine","They cannot use tracking"],"Rapid deliveries can be hard to combine","紧急小批配送不容易合并。"),q("Which measure is recommended?",["Number of shop windows","Vehicle kilometres and loading rates","Total city population"],"Vehicle kilometres and loading rates","评估应看行驶里程与装载率。") ] },
];

export const readingBatch06: CourseLesson[] = [
  { id:"r49", skill:"reading", section:"Section 1", title:"铁路季票续期说明", level:"基础", minutes:16, focus:"续期窗口、照片、折扣与领取", text:"RAIL SEASON-TICKET RENEWAL\nRenew online from 28 days before your current ticket expires. The new ticket begins immediately after the old one, so no travel days are lost. A new photograph is required only if the existing image is more than five years old or no longer clearly resembles you. Employees using a company discount must upload a fresh eligibility letter every year. Digital tickets appear in the app within two hours. Plastic cards ordered online can be collected after two working days from the station selected at checkout; bring the payment card and photo identification.", questions:[q("How early can a ticket be renewed?",["7 days","28 days","Five years"],"28 days","可在到期前二十八天续期。"),q("When is a new photograph required?",["For every renewal","When the old image is over five years old","Only for digital tickets"],"When the old image is over five years old","旧照片超过五年或已不相像时更新。"),q("What must discounted employees upload?",["A yearly eligibility letter","A train timetable","A plastic card"],"A yearly eligibility letter","公司折扣资格信每年更新。"),q("When is a plastic card ready for collection?",["Within two hours","After two working days","After 28 days"],"After two working days","实体卡网上购买后两个工作日领取。") ] },
  { id:"r50", skill:"reading", section:"Section 1", title:"宠物寄养预订规则", level:"基础", minutes:16, focus:"疫苗、到离店、用品与取消", text:"HAPPY PAWS BOARDING\nDogs and cats must have current vaccination records, emailed at least 48 hours before arrival. Check-in is between 3 p.m. and 6 p.m.; morning arrival is available for an additional £12. Owners should provide labelled medicine with written instructions, but food and bedding are included. Bring one familiar toy if desired, not bowls or large beds. Collection is by 11 a.m. on the final day. A full refund is available for cancellations made more than seven days ahead. Later cancellations receive credit only if the space is rebooked.", questions:[q("When must vaccination records be sent?",["At collection","At least 48 hours before arrival","Seven days after arrival"],"At least 48 hours before arrival","疫苗记录须至少提前四十八小时邮件发送。"),q("What costs an extra £12?",["Morning arrival","Food","Bedding"],"Morning arrival","常规下午登记，上午到达加十二英镑。"),q("What may an owner bring?",["A large bed","One familiar toy","Food bowls"],"One familiar toy","可带一个熟悉玩具。"),q("When is a full cancellation refund available?",["More than seven days ahead","On the final day","Only after rebooking"],"More than seven days ahead","提前超过七天取消可全退。") ] },
  { id:"r51", skill:"reading", section:"Section 1", title:"社区泳池临时关闭通知", level:"基础", minutes:16, focus:"关闭范围、替代场地、课程与会员", text:"RIVERSIDE POOL CLOSURE\nThe main pool will close from Monday 6 to Sunday 19 November while the ventilation system is replaced. The teaching pool and gym remain open, using the side entrance on Mill Lane. Adult lane-swimming sessions will move to North Park Pool, but places must be reserved through the Riverside account. Children's lessons will continue in the teaching pool at their usual times, except Saturday advanced classes, which instructors will rearrange by email. Monthly members may use North Park without extra payment or request a membership extension equal to the closure period.", questions:[q("What is being replaced?",["The teaching pool","The ventilation system","The gym entrance"],"The ventilation system","主泳池因更换通风系统关闭。"),q("Which facilities remain open?",["The main pool only","The teaching pool and gym","North Park gym only"],"The teaching pool and gym","教学池和健身房继续开放。"),q("How are Saturday advanced classes handled?",["They are permanently cancelled","Instructors rearrange them by email","They move without notice"],"Instructors rearrange them by email","教练会通过邮件改期。"),q("What can monthly members request?",["A free year","An extension for the closure period","Cash for every lesson"],"An extension for the closure period","会员可选择相应时长延期。") ] },
  { id:"r52", skill:"reading", section:"Section 2", title:"弹性工作时间政策", level:"进阶", minutes:18, focus:"核心时段、申请、服务覆盖与试行", text:"FLEXIBLE HOURS POLICY\nEmployees may start between 7:30 and 10:00 and finish after completing their contracted hours. Everyone must be available during the core period from 10:00 to 15:30, unless approved leave applies. Teams must maintain telephone cover from 8:30 to 17:30, so preferred schedules are not guaranteed. Submit a regular-hours request to your manager at least ten working days ahead. The manager will consider service demand, shared duties and meeting access, then confirm a three-month trial. Record actual hours in the time system each day. Either side may end the arrangement with two weeks' notice after discussing alternatives.", questions:[q("When does the core period end?",["15:30","17:30","10:00"],"15:30","所有人原则上十点至十五点半在线。"),q("Why might a preferred schedule be refused?",["The office has no clocks","Telephone cover must be maintained","Staff cannot record hours"],"Telephone cover must be maintained","团队须覆盖八点半到十七点半电话。"),q("How early should a regular request be submitted?",["Two days","Ten working days","Three months"],"Ten working days","至少提前十个工作日。"),q("How long is the initial trial?",["Two weeks","Three months","One year"],"Three months","经理确认三个月试行期。") ] },
  { id:"r53", skill:"reading", section:"Section 2", title:"电脑工位评估流程", level:"进阶", minutes:18, focus:"自查、调整、专业转介与复核", text:"WORKSTATION ASSESSMENT\nComplete the online self-check when joining the company, moving desk or developing discomfort. Adjust the chair so both feet are supported and place the main screen directly ahead, with its top around eye level. Frequently used items should remain within easy reach. After submission, the workplace assessor reviews your answers within five working days and may request photographs that do not show confidential material. Simple equipment such as a footrest can be authorised immediately. Persistent pain, disability-related needs or specialist equipment requests are referred to Occupational Health. Repeat the check after any recommended change has been used for two weeks.", questions:[q("When must a self-check be completed?",["Only after an accident","After moving desk","Once every ten years"],"After moving desk","入职、换桌或不适时都应自查。"),q("Where should the main screen be placed?",["Directly ahead","Behind the chair","On the floor"],"Directly ahead","屏幕应在正前方，顶部约齐眼。"),q("Who handles persistent pain?",["Reception","Occupational Health","A customer"],"Occupational Health","持续疼痛会转介职业健康。"),q("When should the check be repeated?",["After two weeks using the change","Before any change","After five years"],"After two weeks using the change","建议调整使用两周后复核。") ] },
  { id:"r54", skill:"reading", section:"Section 2", title:"客户投诉升级流程", level:"进阶", minutes:18, focus:"一线处理、记录、时限与升级标准", text:"COMPLAINT ESCALATION\nFront-line staff should first listen, confirm the desired outcome and resolve matters within their authority. Record the customer's words, order number, action taken and promised follow-up in the case system. Do not admit legal liability or promise compensation outside the published limits. Refer the case to a supervisor immediately if it involves safety, discrimination, threatened legal action or repeated failure. Other unresolved complaints move to the resolution team after two working days. Tell the customer who now owns the case and when to expect contact. A closed case may be reopened if new evidence is received within 30 days.", questions:[q("What should staff confirm first?",["The desired outcome","The customer's salary","A court date"],"The desired outcome","先倾听并确认客户希望的结果。"),q("What must not be promised?",["A case number","Compensation outside published limits","A follow-up time"],"Compensation outside published limits","一线人员不得超限承诺赔偿。"),q("Which case needs immediate supervisor referral?",["A spelling error","A safety concern","A new order"],"A safety concern","安全、歧视、法律威胁或反复失败需立即升级。"),q("When can a closed case be reopened?",["With new evidence within 30 days","Only after one year","Whenever no record exists"],"With new evidence within 30 days","三十天内收到新证据可重开。") ] },
  { id:"r55", skill:"reading", section:"Section 3", title:"夜间经济如何服务整座城市", level:"模考", minutes:22, focus:"就业、噪声、交通、安全与治理", text:"Restaurants, theatres and late-opening shops create jobs and make town centres lively after office workers leave. Yet the night-time economy is often discussed only when residents complain about noise or disorder. Treating every late activity as the same problem leads to blunt rules that may close responsible businesses without changing harmful behaviour.\n\nPlanning can separate some conflicting uses, but distance alone is not enough. Soundproofing, clear delivery hours and trained door staff reduce impacts at the source. Safe, frequent night transport matters for customers and for lower-paid workers whose shifts end after normal services. Well-lit walking routes and visible assistance points can improve confidence without turning public space into a hostile security zone.\n\nSuccessful towns collect evidence by hour and location rather than relying on total complaint numbers. They also include residents, workers, performers and transport providers in regular reviews. The aim is not unlimited opening, but a varied centre where people can work, socialise and sleep under rules that respond to real patterns.", questions:[q("Why are broad restrictions criticised?",["They may harm responsible businesses","They always increase transport","They remove every complaint"],"They may harm responsible businesses","把所有夜间活动视为同一问题会误伤守规企业。"),q("Why is night transport important for workers?",["Their shifts may end after normal services","They all live beside work","It replaces soundproofing"],"Their shifts may end after normal services","低薪夜班员工下班时常规交通已结束。"),q("How should towns analyse evidence?",["Only by annual totals","By hour and location","Only through business income"],"By hour and location","按时间与地点分析才能看到真实模式。"),q("What is the writer's preferred aim?",["Unlimited opening","A varied centre under responsive rules","Closing all late venues"],"A varied centre under responsive rules","结论追求兼顾工作、社交与睡眠。") ] },
  { id:"r56", skill:"reading", section:"Section 3", title:"学校街道能否减少交通风险", level:"模考", minutes:22, focus:"限时管制、行为变化、公平与评估", text:"A school street restricts most motor traffic near a school during morning arrival and afternoon collection. Barriers or cameras create space for walking and cycling, while residents, emergency vehicles and some disabled users receive exemptions. The immediate goal is safer gates, but supporters also hope families will leave cars at home.\n\nResults depend on design. If drivers simply park on the next street, danger and pollution may move rather than disappear. Authorities therefore need safe crossings on surrounding roads and should monitor access for households with limited mobility. Clear advance communication matters because unexpected fines can quickly damage trust.\n\nCounting vehicles at the gate shows only part of the effect. Surveys can reveal whether children changed travel mode, while air measurements and observations on nearby streets test whether problems were displaced. School streets work best as one element of a wider plan that includes reliable buses, connected cycle routes and practical alternatives for families living farther away.", questions:[q("Who may receive an exemption?",["Every through-driver","Some disabled users","Only tourists"],"Some disabled users","居民、紧急车辆及部分残障人士可豁免。"),q("What is displacement in this context?",["Traffic moving to nearby streets","Children changing school","Barriers being stored"],"Traffic moving to nearby streets","车辆可能转到下一条街而非消失。"),q("What can surveys reveal?",["Barrier weight","Changes in children's travel mode","Exact air chemistry only"],"Changes in children's travel mode","问卷可判断孩子是否改变出行方式。"),q("What wider support is recommended?",["More unexpected fines","Reliable buses and connected cycle routes","Removing all crossings"],"Reliable buses and connected cycle routes","学校街道需与公交、自行车网及远距家庭方案配套。") ] },
];

const task1Checklist = ["开头直接说明写信目的", "三个任务点都有具体事实、请求或安排", "语气符合正式或私人关系", "至少 150 词并检查时态、拼写和分段"];
const task2Checklist = ["引言回应题目并明确立场或范围", "主体段有中心句、解释和具体例子", "比较、因果或让步关系清楚", "至少 250 词且结论不加入新观点"];

export const writingBatch06: CourseLesson[] = [
  {id:"w49",skill:"writing",section:"Task 1 · 正式信",title:"要求房东维修漏风窗户",level:"进阶",minutes:26,focus:"问题证据、生活影响与维修时限",task:"The windows in your rented home do not close properly. Write a letter to your landlord. Write at least 150 words.",bullets:["describe the condition of the windows","explain how the problem affects you","request an inspection and repair date"],checklist:task1Checklist},
  {id:"w50",skill:"writing",section:"Task 1 · 半正式信",title:"感谢同事代班",level:"进阶",minutes:26,focus:"具体帮助、实际结果与回报安排",task:"A colleague covered your work while you dealt with an unexpected problem. Write a letter to your colleague. Write at least 150 words.",bullets:["explain why you had to leave","say how the colleague's help benefited you","offer practical help in return"],checklist:task1Checklist},
  {id:"w51",skill:"writing",section:"Task 1 · 正式信",title:"投诉送达时损坏的商品",level:"进阶",minutes:26,focus:"订单细节、损坏证据与解决方案",task:"An item you ordered online arrived damaged. Write a letter to the company. Write at least 150 words.",bullets:["give the order and delivery details","describe the damage and any evidence","state the solution and deadline you expect"],checklist:task1Checklist},
  {id:"w52",skill:"writing",section:"Task 1 · 私人信",title:"邀请朋友参加徒步假期",level:"进阶",minutes:26,focus:"行程亮点、难度、准备与回复",task:"You are planning a walking holiday and would like a friend to join you. Write a letter to your friend. Write at least 150 words.",bullets:["describe the route and dates","explain why the trip would suit your friend","suggest preparation and ask for a reply"],checklist:task1Checklist},
  {id:"w53",skill:"writing",section:"Task 2 · 优缺点",title:"压缩每周工作时间",level:"模考",minutes:42,focus:"比较效率、疲劳、服务覆盖与公平",task:"Some employees work their weekly hours over fewer, longer days. What are the advantages and disadvantages of this arrangement? Write at least 250 words.",bullets:["explain possible productivity and personal benefits","consider fatigue and service coverage","compare effects on different workers"],checklist:task2Checklist},
  {id:"w54",skill:"writing",section:"Task 2 · 双边讨论",title:"公共艺术还是基本服务",level:"模考",minutes:42,focus:"比较文化价值、机会成本与长期收益",task:"Some people think public money should support art in towns and cities, while others say it should be spent only on essential services. Discuss both views and give your own opinion. Write at least 250 words.",bullets:["explain cultural and economic benefits","consider urgent service needs and opportunity cost","give a practical funding position"],checklist:task2Checklist},
  {id:"w55",skill:"writing",section:"Task 2 · 问题与对策",title:"公共服务的数字排除",level:"模考",minutes:42,focus:"设备、技能、无障碍与线下替代",task:"More public services are moving online, but some people cannot use them easily. What problems does this cause, and what solutions are needed? Write at least 250 words.",bullets:["identify groups and barriers","explain consequences for access and trust","evaluate digital support and offline alternatives"],checklist:task2Checklist},
  {id:"w56",skill:"writing",section:"Task 2 · 观点",title:"城市是否应建设社区花园",level:"模考",minutes:42,focus:"权衡土地、健康、参与与维护",task:"Cities should use more public land for community gardens. To what extent do you agree or disagree? Write at least 250 words.",bullets:["state the extent of agreement","explain social and environmental benefits","consider land pressure, access and maintenance"],checklist:task2Checklist},
];

export const speakingBatch06: CourseLesson[] = [
  {id:"s49",skill:"speaking",section:"Part 1",title:"电子邮件",level:"进阶",minutes:10,focus:"频率、用途、语气与变化",prompts:["How often do you use email?","What kinds of messages do you send by email?","Do you find formal emails difficult to write?","Has your use of email changed in recent years?"],keywords:["usually","for example","because","used to"]},
  {id:"s50",skill:"speaking",section:"Part 1",title:"公共假日",level:"进阶",minutes:10,focus:"活动、偏好、过去经历与价值",prompts:["What do you usually do on public holidays?","Which public holiday do you enjoy most?","How did you spend public holidays as a child?","Are public holidays important for communities?"],keywords:["normally","prefer","when","important"]},
  {id:"s51",skill:"speaking",section:"Part 1",title:"室内植物",level:"进阶",minutes:10,focus:"拥有、照料、困难与空间影响",prompts:["Do you keep plants inside your home?","Who taught you how to care for plants?","What is difficult about keeping a plant healthy?","Do plants change how a room feels?"],keywords:["at home","learned","challenge","makes"]},
  {id:"s52",skill:"speaking",section:"Part 2",title:"帮助过你的工作人员",level:"进阶",minutes:14,focus:"场景、问题、帮助过程与评价",task:"Describe an employee or service worker who helped you well.",bullets:["where you met the person","what problem you had","what the person did","why the help was effective"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["needed","explained","as a result","effective"]},
  {id:"s53",skill:"speaking",section:"Part 2",title:"一次延误的旅程",level:"进阶",minutes:14,focus:"原计划、延误原因、应对与结果",task:"Describe a journey that was delayed.",bullets:["where you were going","what caused the delay","what you did while waiting","how the journey finally ended"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["planned","because","while","eventually"]},
  {id:"s54",skill:"speaking",section:"Part 2",title:"修好的一件物品",level:"进阶",minutes:14,focus:"物品、故障、维修过程与价值",task:"Describe something that you or another person repaired.",bullets:["what the item was","what was wrong with it","how it was repaired","why repairing it was worthwhile"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["stopped","fixed","instead of","worthwhile"]},
  {id:"s55",skill:"speaking",section:"Part 3",title:"公共艺术与城市空间",level:"模考",minutes:16,focus:"比较价值、审美冲突、经费与参与",prompts:["What can public art add to a town?","Why do people disagree about some public artworks?","Should local residents help choose public art?","How should cities decide how much to spend on it?"],keywords:["can","however","should","depends"]},
  {id:"s56",skill:"speaking",section:"Part 3",title:"数字服务与平等使用",level:"模考",minutes:16,focus:"便利、障碍、责任与保留渠道",prompts:["Why do organisations move services online?","Which people may have difficulty using digital services?","Who should teach essential digital skills?","Should every service keep a face-to-face option?"],keywords:["because","may","responsibility","in my view"]},
];

export const curriculumBatch06: CourseLesson[] = [...listeningBatch06, ...readingBatch06, ...writingBatch06, ...speakingBatch06];
