import type { ChoiceQuestion, CourseLesson } from "./curriculum-v2";

const q = (prompt: string, options: string[], answer: string, explanation: string): ChoiceQuestion => ({ prompt, options, answer, explanation });

export const listeningBatch07: CourseLesson[] = [
  { id:"l57", skill:"listening", section:"Part 1", title:"预订自助仓储单元", level:"基础", minutes:15, focus:"尺寸、日期、门禁与价格", audioFile:"l57.mp3", speakers:"Storage adviser + customer",
    text:"Adviser: SafeBox Storage. Customer: I need space for about twelve moving boxes and a bicycle. Adviser: A twenty-five-square-foot unit should be enough. Customer: Can I start on the third of March? Adviser: Yes. The minimum rental is four weeks at sixty-four pounds, plus a refundable twenty-pound key deposit. Access is from six in the morning until ten at night. Customer: Is insurance included? Adviser: Cover up to one thousand pounds is included, but please bring your own padlock. Customer: Fine. Reserve it under Saru Bat. Adviser: Your unit is C fourteen.",
    questions:[q("What will the customer store besides boxes?",["A sofa","A bicycle","A washing machine"],"A bicycle","客户要存十二个箱子和一辆自行车。"),q("What is the minimum rental period?",["Two weeks","Four weeks","Six months"],"Four weeks","最短租期四周。"),q("What must the customer bring?",["A padlock","Insurance papers","A key card"],"A padlock","基础保险包含，但挂锁自备。"),q("What is the unit number?",["C14","C40","B14"],"C14","客服最后给出 C fourteen。") ] },
  { id:"l58", skill:"listening", section:"Part 1", title:"安排宠物疫苗接种", level:"基础", minutes:15, focus:"宠物信息、疫苗、时间与准备", audioFile:"l58.mp3", speakers:"Veterinary receptionist + owner",
    text:"Receptionist: Meadow Veterinary Clinic. Owner: My dog needs his annual vaccination. Receptionist: What is his name and age? Owner: Piko, five years old. He is a medium-sized brown spaniel. Receptionist: We have Friday at eleven forty or Saturday at nine twenty. Owner: Saturday, please. Receptionist: The vaccination and health check cost forty-seven pounds. Do not feed him for two hours beforehand, but water is fine. Bring his vaccination card. Owner: I have recently changed address. Receptionist: We can update that when you arrive. Please use the rear entrance because the front car park is being repaired.",
    questions:[q("How old is the dog?",["Four","Five","Seven"],"Five","主人说 Piko 五岁。"),q("Which appointment is chosen?",["Friday 11:40","Saturday 9:20","Saturday 11:40"],"Saturday 9:20","主人选择 Saturday。"),q("How much will the visit cost?",["£27","£40","£47"],"£47","疫苗加健康检查四十七英镑。"),q("What should the owner bring?",["The dog's vaccination card","Food for the dog","A parking permit"],"The dog's vaccination card","接待员要求带疫苗卡。") ] },
  { id:"l59", skill:"listening", section:"Part 2", title:"地方选举投票站工作人员说明", level:"进阶", minutes:16, focus:"到岗、岗位、选民证件与封箱", audioFile:"l59.mp3", speakers:"Election coordinator",
    text:"Polling staff must arrive at the community hall by six fifteen so the station is ready to open at seven. Sign in with the presiding officer and place personal belongings in the locked kitchen. One clerk checks each voter's name and accepted identification; a second clerk issues the ballot paper and records its number. Never suggest how anyone should vote. If a voter needs physical assistance, call the presiding officer rather than entering the booth alone with them. The station closes at ten, but anyone already in the queue may vote. Afterward, count unused papers, seal the ballot box and sign the transport label before leaving.",
    questions:[q("When must staff arrive?",["6:15","7:00","10:00"],"6:15","工作人员六点十五到场布置。"),q("Where are personal belongings stored?",["In a voting booth","In the locked kitchen","Beside the ballot box"],"In the locked kitchen","私人物品放上锁厨房。"),q("Who should assist a voter with a physical need?",["Any other voter","The presiding officer","A clerk alone"],"The presiding officer","应呼叫投票站主任。"),q("What is signed after the box is sealed?",["The transport label","Every ballot paper","The kitchen door"],"The transport label","封箱后签运输标签。") ] },
  { id:"l60", skill:"listening", section:"Part 2", title:"公园志愿服务日说明", level:"进阶", minutes:16, focus:"集合、分组、工具、废物与天气", audioFile:"l60.mp3", speakers:"Volunteer coordinator",
    text:"Thank you for joining Sunday's park volunteer day. Meet at the east pavilion at eight forty-five for registration and a safety talk. Litter teams will work beside the lake, while planting teams go to the northern flower beds. Gloves, tools and high-visibility vests are provided. Wear strong closed shoes and bring a refillable drink bottle. Do not pick up needles or broken glass; mark the location with a red flag and tell a supervisor. Green waste goes into open trailers, but general litter belongs in clear bags. Light rain will not cancel the event. Check the council message page at seven if strong winds are forecast.",
    questions:[q("Where do volunteers meet?",["At the lake","At the east pavilion","At the northern gate"],"At the east pavilion","集合点是东侧凉亭。"),q("Which item must volunteers bring?",["A refillable drink bottle","Their own tools","Red plastic bags"],"A refillable drink bottle","手套工具马甲提供，水瓶自带。"),q("What should volunteers do with broken glass?",["Put it in a clear bag","Mark it and tell a supervisor","Carry it to the pavilion"],"Mark it and tell a supervisor","危险物不可捡，应标记并报告。"),q("When should the message page be checked?",["At 7:00","At 8:45","After the event"],"At 7:00","有强风预报时七点查通知。") ] },
  { id:"l61", skill:"listening", section:"Part 3", title:"研究客户等候时间", level:"进阶", minutes:17, focus:"定义、采样、隐私与建议", audioFile:"l61.mp3", speakers:"Trainer + two trainees",
    text:"Trainer: How will you study waiting time at the service desk? Trainee one: We will start timing when a customer enters the building. Trainer: That includes browsing. Start when the person takes a queue ticket and stop when an adviser begins speaking. Trainee two: We will sample Monday morning and Friday afternoon. Trainer: Add Wednesday lunchtime because staffing is lower then. Trainee one: May we record the reason for each visit? Trainer: Use broad categories such as payment, booking or complaint, but do not write names or account numbers. Trainee two: We will compare the median, not only the average, because one very long case could distort it. Trainer: Then link recommendations to the busiest category.",
    questions:[q("When should timing begin?",["At the building entrance","When a queue ticket is taken","When the adviser finishes"],"When a queue ticket is taken","等待从取号开始计算。"),q("Which extra period is added?",["Wednesday lunchtime","Tuesday evening","Sunday morning"],"Wednesday lunchtime","导师增加周三午餐时段。"),q("What information must not be recorded?",["Visit category","Account numbers","Day of visit"],"Account numbers","不得记录姓名或账号。"),q("Why will the median be used?",["One long case can distort the average","It records customer names","It removes all waiting"],"One long case can distort the average","极端长案例会拉高平均数。") ] },
  { id:"l62", skill:"listening", section:"Part 3", title:"策划社区口述历史访谈", level:"进阶", minutes:17, focus:"对象、问题、同意、转写与保存", audioFile:"l62.mp3", speakers:"Tutor + two students",
    text:"Tutor: Who will you interview for the oral-history project? Student one: People who have lived near the old market for at least twenty years. Student two: We planned ten interviews, but six detailed ones are more realistic. Tutor: Begin with open questions about daily life, then ask about specific changes. Do not lead people by calling the past better. Student one: We will record audio on our phones. Tutor: Use the college recorders and obtain written consent for recording and archive use. Student two: I will transcribe the first half and my partner the second. Tutor: Both of you must check every transcript against the audio, and participants should be allowed to correct names or private details before publication.",
    questions:[q("How many interviews will be conducted?",["Six","Ten","Twenty"],"Six","最终选择六次深入访谈。"),q("What kind of question should come first?",["A leading question","An open question","A question about payment"],"An open question","先用开放问题了解日常生活。"),q("Which recording equipment should be used?",["Personal phones","College recorders","No equipment"],"College recorders","导师要求使用学院录音设备。"),q("What may participants correct?",["The research question","Names or private details","The interview date only"],"Names or private details","发布前允许更正姓名或隐私细节。") ] },
  { id:"l63", skill:"listening", section:"Part 4", title:"食品标签如何影响选择", level:"模考", minutes:18, focus:"注意力、分量、健康提示与实验限制", audioFile:"l63.mp3", speakers:"Consumer researcher",
    text:"Food labels contain more information than shoppers can process during a quick decision. People usually notice price, brand and one or two prominent claims before reading a detailed nutrition table. Serving size creates difficulty: a package that appears to contain one portion may display values for half the pack. Front-of-pack colour systems make comparisons faster, but a single green symbol can create a health halo around a product that remains high in another ingredient. Researchers test labels using simulated shops and purchase tasks, yet stated intentions do not always predict real buying. Strong studies therefore compare actual sales before and after a label change while controlling for price promotions and product position.",
    questions:[q("What do shoppers often notice first?",["Every nutrient","Price and brand","The research method"],"Price and brand","快速决定时通常先看价格、品牌和显眼声明。"),q("Why can serving size confuse people?",["Values may cover only half a package","Every package is empty","Serving size shows only price"],"Values may cover only half a package","看似一份的包装可能只标半包数据。"),q("What is a health halo?",["One positive sign making the whole product seem healthy","A discount on vegetables","A compulsory laboratory test"],"One positive sign making the whole product seem healthy","单一绿色提示可能让整体显得健康。"),q("What should sales studies control for?",["Customer names","Price promotions and product position","Weather only"],"Price promotions and product position","促销和货架位置也会影响销量。") ] },
  { id:"l64", skill:"listening", section:"Part 4", title:"海岸步道侵蚀管理", level:"模考", minutes:18, focus:"自然过程、风险、改线与公众沟通", audioFile:"l64.mp3", speakers:"Coastal management lecturer",
    text:"Coastal paths face erosion from waves, rainfall and unstable cliffs. Rebuilding the same edge section after every storm may be expensive and can disturb habitats without providing lasting safety. Managers increasingly use adaptive routes: they monitor ground movement and prepare an inland alignment before the old path becomes dangerous. This approach requires agreements with landowners and clear signs so walkers understand that a diversion is planned, not a maintenance failure. Hard barriers remain appropriate near essential infrastructure, but they may shift erosion along the coast. Decisions should combine engineering evidence, habitat surveys and the social value of access. Publishing inspection dates and trigger points helps communities understand why a path moves or closes.",
    questions:[q("Why may repeated rebuilding be ineffective?",["It guarantees new land","It may be costly without lasting safety","It removes every habitat"],"It may be costly without lasting safety","在同一边缘反复修建成本高且不持久。"),q("What is an adaptive route?",["A prepared inland alternative","A path used only by vehicles","A permanent sea wall"],"A prepared inland alternative","监测地面并预先准备内陆线路。"),q("Where may hard barriers still be suitable?",["Near essential infrastructure","On every beach","Only beside cafés"],"Near essential infrastructure","重要基础设施附近仍可能需要硬防护。"),q("What improves public understanding?",["Hiding closure reasons","Publishing inspection dates and trigger points","Removing all route signs"],"Publishing inspection dates and trigger points","公开检查日期和触发标准可说明改线原因。") ] },
];

export const readingBatch07: CourseLesson[] = [
  { id:"r57", skill:"reading", section:"Section 1", title:"自助仓储合同要点", level:"基础", minutes:16, focus:"门禁、禁存物、付款与退租", text:"SAFEBOX CUSTOMER TERMS\nCustomers may access units daily from 06:00 to 22:00 with a personal gate code. Do not share this code or allow another vehicle to follow you through the gate. Food, plants, fuel, illegal goods and any living creature are prohibited. Monthly fees are collected in advance on the start date. If payment is seven days late, access is suspended but charges continue. Give 14 days' notice to end the agreement. On the final day, empty and sweep the unit, remove your padlock and upload a photograph before midnight. The key deposit is returned within five working days after inspection.", questions:[q("When can customers enter?",["Only on weekdays","06:00–22:00 daily","At any time overnight"],"06:00–22:00 daily","每日早六点至晚十点开放。"),q("Which item is prohibited?",["A bicycle","Fuel","Moving boxes"],"Fuel","食品、植物、燃料等不得存放。"),q("What happens after payment is seven days late?",["Access is suspended","All charges stop","The unit becomes free"],"Access is suspended","门禁暂停但费用继续。"),q("What must be uploaded on the final day?",["A passport copy","A photograph of the empty unit","A new contract"],"A photograph of the empty unit","清空打扫后午夜前上传照片。") ] },
  { id:"r58", skill:"reading", section:"Section 1", title:"宠物疫苗预约通知", level:"基础", minutes:16, focus:"登记、准备、副作用与复诊", text:"VACCINATION APPOINTMENT\nArrive ten minutes early and keep dogs on a short lead; cats must remain in secure carriers. Bring the vaccination record and a list of current medicines. Unless the clinic gives different instructions, pets may eat normally before routine vaccination. The nurse first checks weight and general health. Mild tiredness or tenderness can occur for a day afterward. Contact the clinic promptly if your pet has difficulty breathing, repeated vomiting or swelling around the face. A reminder for the next dose will be emailed, but owners remain responsible for booking it.", questions:[q("How should a cat arrive?",["On a short lead","In a secure carrier","Without an owner"],"In a secure carrier","猫必须留在安全运输箱中。"),q("What should owners bring besides the record?",["A list of medicines","A food bowl","A photograph of the clinic"],"A list of medicines","需带疫苗记录和当前用药清单。"),q("Which mild effect may occur?",["Temporary tiredness","Permanent blindness","A broken tooth"],"Temporary tiredness","一天内轻度疲倦或触痛属常见。"),q("Who must book the next dose?",["The owner","The email system","The animal shelter"],"The owner","邮件只是提醒，主人负责预约。") ] },
  { id:"r59", skill:"reading", section:"Section 1", title:"地方选举选民指引", level:"基础", minutes:16, focus:"时间、证件、代理与无障碍支持", text:"VOTING AT YOUR LOCAL ELECTION\nPolling stations are open from 7 a.m. to 10 p.m. Your poll card shows where to vote, but you do not need to bring the card. You must show one accepted form of photo identification; an expired document is allowed if the photograph still clearly resembles you. If you have appointed a proxy, that person votes at your station and must show their own identification. Large-print sample ballots and pencil grips are available. Ask staff for assistance, or take one companion aged 18 or over into the booth after staff record their name.", questions:[q("Is a poll card required?",["Yes, always","No","Only after 10 p.m."],"No","投票卡标地点，但不是必带证件。"),q("When can expired identification be accepted?",["When the photo still resembles the voter","Only with no photograph","Only for staff"],"When the photo still resembles the voter","照片仍清楚相像即可。"),q("Where does a proxy vote?",["At any station","At the voter's station","Only online"],"At the voter's station","代理人在选民所属投票站投票。"),q("What accessibility item is available?",["A free telephone","A pencil grip","A transport ticket"],"A pencil grip","现场提供大字样票和握笔辅助。") ] },
  { id:"r60", skill:"reading", section:"Section 2", title:"消防疏散员轮值规则", level:"进阶", minutes:18, focus:"职责、替班、检查与事故后记录", text:"FIRE WARDEN ROTA\nEach occupied floor must have one named fire warden and one deputy during core hours. Wardens who are absent or working remotely must arrange cover and update the shared rota before 9 a.m. During an alarm, sweep only the assigned zone while moving toward the exit; do not delay to search locked rooms or collect belongings. Report the zone status to the assembly coordinator outside. Weekly duties include checking that routes and fire doors are clear, not testing alarms. After any evacuation, record missing signage, blocked routes or assistance issues on the safety form before the end of the shift.", questions:[q("How many named roles must each floor have?",["One warden only","A warden and a deputy","Three managers"],"A warden and a deputy","每层核心时段须一名疏散员和一名副手。"),q("When must rota cover be updated?",["Before 9 a.m.","After the alarm","Once a month"],"Before 9 a.m.","缺勤或远程工作时九点前更新。"),q("What should not delay a sweep?",["Moving toward the exit","Searching locked rooms","Reporting outside"],"Searching locked rooms","不可为搜锁门房间而延误。"),q("When is the safety form completed?",["Before the end of the shift","A year later","Before every weekly check"],"Before the end of the shift","疏散后当班结束前记录问题。") ] },
  { id:"r61", skill:"reading", section:"Section 2", title:"学徒学习假政策", level:"进阶", minutes:18, focus:"资格、申请、证据与工作安排", text:"APPRENTICE STUDY LEAVE\nApprentices receive one paid study day for each formal assessment, plus up to two preparation days per training year. Submit requests at least 15 working days ahead with the assessment timetable attached. Preparation leave should normally be taken within the preceding month and may be divided into half days. Managers can change a requested date when minimum staffing would not be met, but must offer a reasonable alternative before the assessment. Travel to a required assessment is paid as working time. Additional revision time may be taken as annual leave through the normal booking process.", questions:[q("How much paid leave is given for each formal assessment?",["One study day","Two weeks","No paid time"],"One study day","每次正式考核一个带薪学习日。"),q("What must accompany the request?",["A medical report","The assessment timetable","A customer survey"],"The assessment timetable","申请需附考核时间表。"),q("When can a manager change the date?",["When minimum staffing would fail","Whenever the apprentice studies","After the assessment only"],"When minimum staffing would fail","人员覆盖不足时可调整但须给合理替代。"),q("How is required assessment travel treated?",["As unpaid leave","As working time","As annual leave only"],"As working time","必要考核路程计工作时间。") ] },
  { id:"r62", skill:"reading", section:"Section 2", title:"工作场所噪声防护", level:"进阶", minutes:18, focus:"风险区、耳部防护、轮岗与报告", text:"NOISE CONTROL AT WORK\nYellow signs mark areas where hearing protection is mandatory, even for short visits. Use the ear protection issued for your task and check seals or cushions for damage before every shift. Personal music headphones are not a substitute. Keep machine covers closed and never disable an alarm because it is difficult to hear. Supervisors may rotate staff to limit exposure, but rotation does not replace engineering controls or maintenance. Report ringing ears, muffled hearing or unusually loud equipment immediately. Annual hearing checks are confidential and help identify change; they are not a pass allowing unlimited exposure.", questions:[q("Where is hearing protection mandatory?",["In yellow-signed areas","Only outdoors","At the annual check"],"In yellow-signed areas","黄色标识区即使短时进入也必戴。"),q("What is not an acceptable substitute?",["Issued ear protection","Personal music headphones","Machine covers"],"Personal music headphones","个人音乐耳机不能代替防护。"),q("What does staff rotation not replace?",["Engineering controls and maintenance","A lunch break","A confidential form"],"Engineering controls and maintenance","轮岗不能替代工程控制和维护。"),q("Which symptom should be reported?",["Ringing ears","Clean gloves","A quiet office"],"Ringing ears","耳鸣、听感模糊或设备异常响都要报告。") ] },
  { id:"r63", skill:"reading", section:"Section 3", title:"补充装商店能否减少包装", level:"模考", minutes:22, focus:"重复使用、卫生、价格与真实影响", text:"Refill shops sell products such as grains, detergent and shampoo into containers that customers bring or borrow. The visible benefit is less single-use packaging, but the full environmental result depends on transport, cleaning and how often each container is reused. A heavy jar used twice may have a larger footprint than a light package designed efficiently.\n\nConvenience affects participation. Customers need clear weighing instructions, hygienic dispensers and the option to borrow containers when they forget their own. Prices must be shown per standard unit so shoppers can compare them with packaged goods. Shops also need procedures that prevent allergens from moving between products.\n\nThe most credible businesses measure packaging avoided without claiming that every refill is automatically sustainable. They work with suppliers to deliver goods in large reusable containers and study which products customers refill repeatedly. In this way, the model changes the supply chain rather than simply moving disposal from the customer to the shop.", questions:[q("What determines a container's environmental value?",["Its colour only","Transport, cleaning and repeated use","The shop's opening music"],"Transport, cleaning and repeated use","真实影响取决于运输、清洗和复用次数。"),q("Why should prices use a standard unit?",["To enable comparison","To hide product weight","To prevent borrowing"],"To enable comparison","统一单位让顾客与包装商品比较。"),q("Which safety issue must shops manage?",["Allergen transfer","Train delays","Street lighting"],"Allergen transfer","散装容器需要防止过敏原交叉。"),q("What supply change is recommended?",["More single-use bags","Large reusable delivery containers","Smaller disposable samples"],"Large reusable delivery containers","与供应商采用大型可复用容器才能改变供应链。") ] },
  { id:"r64", skill:"reading", section:"Section 3", title:"社区能源合作社的作用", level:"模考", minutes:22, focus:"所有权、收益、公平与治理", text:"A community energy cooperative allows local members to jointly own renewable generation such as rooftop solar panels or a small wind project. Members may receive interest or cheaper electricity, while part of the income supports local efficiency work. Shared ownership can build acceptance because residents see where revenue goes.\n\nHowever, a scheme funded only by people who can afford shares may exclude tenants and low-income households. Some cooperatives address this with low-cost membership, community shares held in trust and grants for insulation rather than payments only to investors. Technical expertise is also essential: enthusiasm cannot replace reliable cost estimates, grid agreements and maintenance plans.\n\nDemocratic voting gives members influence, but meetings can still be dominated by people with more time or confidence. Strong cooperatives publish plain-language accounts, offer several ways to vote and report who benefits. Their value lies not just in producing clean power, but in testing whether the transition can distribute control and savings more widely.", questions:[q("Why can shared ownership increase acceptance?",["Residents can see where revenue goes","It removes all maintenance","Only companies may vote"],"Residents can see where revenue goes","本地成员看得到收入用途。"),q("Who may be excluded by expensive shares?",["Low-income households","Technical advisers","Every investor"],"Low-income households","只靠有能力买股份的人融资会排除低收入者和租户。"),q("What cannot enthusiasm replace?",["Reliable technical and financial planning","Community meetings","Renewable electricity"],"Reliable technical and financial planning","项目仍需成本、并网与维护专业能力。"),q("What should strong cooperatives report?",["Only panel colour","Who benefits","No financial information"],"Who benefits","透明账目、多种投票方式并报告受益者。") ] },
];

const task1Checklist = ["开头直接说明写信目的", "三个任务点都有具体事实、请求或安排", "语气符合正式或私人关系", "至少 150 词并检查时态、拼写和分段"];
const task2Checklist = ["引言回应题目并明确立场或范围", "主体段有中心句、解释和具体例子", "比较、因果或让步关系清楚", "至少 250 词且结论不加入新观点"];

export const writingBatch07: CourseLesson[] = [
  {id:"w57",skill:"writing",section:"Task 1 · 正式信",title:"申请变更仓储合同",level:"进阶",minutes:26,focus:"现有安排、变化原因与费用确认",task:"You rent a storage unit but need to change the size and end date. Write a letter to the storage company. Write at least 150 words.",bullets:["give your current contract details","explain the changes you need and why","ask about availability, fees and confirmation"],checklist:task1Checklist},
  {id:"w58",skill:"writing",section:"Task 1 · 半正式信",title:"为损坏邻居物品道歉",level:"进阶",minutes:26,focus:"承担责任、解释经过与补救",task:"You accidentally damaged something belonging to your neighbour. Write a letter to your neighbour. Write at least 150 words.",bullets:["apologise and explain what happened","describe the damage honestly","offer repair, replacement or another solution"],checklist:task1Checklist},
  {id:"w59",skill:"writing",section:"Task 1 · 正式信",title:"申请转到另一门课程",level:"进阶",minutes:26,focus:"原课信息、困难与转课请求",task:"You have started a college course but would like to transfer to another course. Write a letter to the college. Write at least 150 words.",bullets:["give details of your current course","explain why it is unsuitable","request a transfer and ask about next steps"],checklist:task1Checklist},
  {id:"w60",skill:"writing",section:"Task 1 · 私人信",title:"给准备面试的朋友建议",level:"进阶",minutes:26,focus:"针对岗位、准备方法与当天表现",task:"A friend has asked for advice before an important job interview. Write a letter to your friend. Write at least 150 words.",bullets:["suggest how to research and prepare","recommend useful practice","give advice for the interview day"],checklist:task1Checklist},
  {id:"w61",skill:"writing",section:"Task 2 · 双边讨论",title:"本地食品还是进口食品",level:"模考",minutes:42,focus:"比较环境、价格、选择与韧性",task:"Some people believe consumers should buy locally produced food, while others value access to imported food. Discuss both views and give your own opinion. Write at least 250 words.",bullets:["explain local economic and environmental arguments","consider price, season and consumer choice","give a balanced practical position"],checklist:task2Checklist},
  {id:"w62",skill:"writing",section:"Task 2 · 双边讨论",title:"老年人延长工作年限",level:"模考",minutes:42,focus:"比较经验、收入、健康与机会",task:"Some people think older adults should be encouraged to continue working, while others believe they should retire earlier. Discuss both views and give your own opinion. Write at least 250 words.",bullets:["explain benefits of experience and income","consider health, choice and younger workers","state conditions for a fair policy"],checklist:task2Checklist},
  {id:"w63",skill:"writing",section:"Task 2 · 问题与对策",title:"城市噪声污染",level:"模考",minutes:42,focus:"交通、建设、夜间活动与执法",task:"Noise has become a serious problem in many towns and cities. What are the main causes, and what measures could reduce it? Write at least 250 words.",bullets:["identify major and less obvious sources","explain effects on health and daily life","evaluate planning, technical and enforcement measures"],checklist:task2Checklist},
  {id:"w64",skill:"writing",section:"Task 2 · 观点",title:"公司是否负责员工培训",level:"模考",minutes:42,focus:"界定公司、个人与政府责任",task:"Companies should be mainly responsible for keeping their employees' skills up to date. To what extent do you agree or disagree? Write at least 250 words.",bullets:["state the extent of agreement","explain business and employee benefits","consider personal and public responsibility"],checklist:task2Checklist},
];

export const speakingBatch07: CourseLesson[] = [
  {id:"s57",skill:"speaking",section:"Part 1",title:"日历与计划",level:"进阶",minutes:10,focus:"工具、频率、记忆与变化",prompts:["Do you use a calendar every day?","What kinds of events do you record?","How do you remember unexpected tasks?","Did you plan your time differently in the past?"],keywords:["usually","such as","otherwise","used to"]},
  {id:"s58",skill:"speaking",section:"Part 1",title:"居住区的声音",level:"进阶",minutes:10,focus:"声音来源、时段、影响与改善",prompts:["What sounds can you hear near your home?","At what time is your neighbourhood quietest?","Is there any sound that bothers you?","How could unwanted noise be reduced?"],keywords:["nearby","quietest","because","could"]},
  {id:"s59",skill:"speaking",section:"Part 1",title:"赠送礼物",level:"进阶",minutes:10,focus:"选择、场合、困难与偏好",prompts:["When do you usually give gifts?","How do you choose a gift for someone?","Is choosing a gift ever difficult?","Do you prefer useful or surprising gifts?"],keywords:["when","consider","sometimes","prefer"]},
  {id:"s60",skill:"speaking",section:"Part 2",title:"改善安全的一条规则",level:"进阶",minutes:14,focus:"规则、原因、执行与效果",task:"Describe a rule that made a place or activity safer.",bullets:["what the rule was","where it applied","how people responded","why it improved safety"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["required","at first","as a result","safer"]},
  {id:"s61",skill:"speaking",section:"Part 2",title:"一次有意思的交谈",level:"进阶",minutes:14,focus:"人物、话题、观点与收获",task:"Describe an interesting conversation you had with someone.",bullets:["who you spoke with","where the conversation happened","what you discussed","why it stayed in your mind"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["discussed","explained","whereas","remember"]},
  {id:"s62",skill:"speaking",section:"Part 2",title:"保存了很久的一件物品",level:"进阶",minutes:14,focus:"来源、用途、变化与情感价值",task:"Describe an object that you have kept for a long time.",bullets:["what the object is","how you obtained it","how its use or condition changed","why you still keep it"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["received","used to","although","means"]},
  {id:"s63",skill:"speaking",section:"Part 3",title:"工作培训与技能更新",level:"模考",minutes:16,focus:"比较责任、形式、时间与成效",prompts:["Why do workers need to update their skills?","Which training is better online and which is better in person?","Should training always take place during paid working time?","How can a company know whether training was effective?"],keywords:["because","whereas","should","evidence"]},
  {id:"s64",skill:"speaking",section:"Part 3",title:"本地食品与全球贸易",level:"模考",minutes:16,focus:"比较价格、环境、供应与消费者选择",prompts:["Why do some consumers prefer local food?","What benefits does imported food provide?","Can food labels help people make better choices?","Will food supply become more local in the future?"],keywords:["one reason","however","can","likely"]},
];

export const curriculumBatch07: CourseLesson[] = [...listeningBatch07, ...readingBatch07, ...writingBatch07, ...speakingBatch07];
