import type{SentenceChallenge}from"./sentence-challenges-base";
import type{SpeakingDrill}from"./speaking-drills-base";

export const sentenceChallengeBatch15:SentenceChallenge[]=[
{id:"g153",title:"剥夺某人某物",level:"基础",principle:"deprive A of B",segments:[{text:"The closure",role:"主语"},{text:"deprived residents",role:"影响对象"},{text:"of transport",role:"被剥夺事物"}],prompt:"The closure deprived residents ___ reliable transport.",options:["of","from","with"],correct:"of",explanation:"deprive someone of something 表示使某人失去某物。",errorHint:"被剥夺的事物前用 of。",model:"The closure deprived residents of reliable transport."},
{id:"g154",title:"使某人倾向于",level:"基础",principle:"incline A to do",segments:[{text:"Delays",role:"主语"},{text:"may incline commuters",role:"使人倾向"},{text:"to drive",role:"行动"}],prompt:"Repeated delays may incline commuters ___ drive.",options:["to","for","at"],correct:"to",explanation:"incline someone to do something 后接不定式。",errorHint:"行动动词前使用 to。",model:"Repeated delays may incline commuters to drive."},
{id:"g155",title:"为某人担保",level:"基础",principle:"vouch for",segments:[{text:"A supervisor",role:"主语"},{text:"can vouch for",role:"担保"},{text:"her reliability",role:"品质"}],prompt:"A supervisor can vouch ___ her reliability.",options:["for","to","on"],correct:"for",explanation:"vouch for 表示担保某人或证明某事。",errorHint:"固定介词是 for。",model:"A former supervisor can vouch for her reliability."},
{id:"g156",title:"在某方面取得进展",level:"进阶",principle:"make headway on",segments:[{text:"The team",role:"主语"},{text:"made headway",role:"取得进展"},{text:"on the dispute",role:"事项"}],prompt:"The team made headway ___ the dispute.",options:["on","into","beside"],correct:"on",explanation:"make headway on something 表示某事取得进展。",errorHint:"进展所针对的事项前用 on。",model:"The mediation team made headway on the dispute."},
{id:"g157",title:"迫使某人做某事",level:"进阶",principle:"oblige A to do",segments:[{text:"Flooding",role:"主语"},{text:"obliged residents",role:"迫使对象"},{text:"to leave",role:"行动"}],prompt:"Flooding obliged residents ___ leave.",options:["to","for","leaving to"],correct:"to",explanation:"oblige someone to do something 使用 to 不定式。",errorHint:"不要在 oblige 后直接接动名词。",model:"Severe flooding obliged residents to leave their homes."},
{id:"g158",title:"放弃某项权利",level:"进阶",principle:"relinquish + 名词",segments:[{text:"Members",role:"主语"},{text:"must relinquish",role:"放弃"},{text:"the vote",role:"对象"}],prompt:"Members with an interest must ___ the vote.",options:["relinquish","relinquishes","relinquishing"],correct:"relinquish",explanation:"must 后使用动词原形 relinquish。",errorHint:"情态动词后不加 s 或 ing。",model:"Members with a financial interest must relinquish the vote."},
{id:"g159",title:"使方案适得其反",level:"进阶",principle:"make + object + adjective",segments:[{text:"Harsh penalties",role:"主语"},{text:"may make the policy",role:"使某物"},{text:"counterproductive",role:"结果补语"}],prompt:"Harsh penalties may make the policy ___.",options:["counterproductive","counterproductively to","be counterproduce"],correct:"counterproductive",explanation:"make + 宾语 + 形容词表示使某物变得怎样。",errorHint:"这里需要形容词作宾补。",model:"Harsh penalties may make the policy counterproductive."},
{id:"g160",title:"与承诺偏离",level:"进阶",principle:"deviate from",segments:[{text:"Outcomes",role:"主语"},{text:"deviated",role:"偏离"},{text:"from promises",role:"参照"}],prompt:"The outcomes deviated ___ the original promises.",options:["from","toward","by"],correct:"from",explanation:"deviate from 表示偏离标准、路线或计划。",errorHint:"参照对象前用 from。",model:"The outcomes deviated from the original promises."}
];

export const speakingDrillBatch15:SpeakingDrill[]=[
{id:"d153",level:"基础",title:"预约社区门诊",scenario:"医疗接待处",prompt:"Ask about referral requirements, cost and how to prepare for an assessment.",model:"Could you tell me whether I need a referral, what the assessment costs and whether I should avoid strenuous exercise beforehand?",keywords:["referral","assessment","strenuous"],followUp:"Which appointment time suits you?"},
{id:"d154",level:"基础",title:"报告湿滑步道",scenario:"野生动物中心",prompt:"Report that drizzle has made a bridge slippery and suggest an immediate precaution.",model:"The drizzle has made the wooden bridge slippery, so could staff place a warning sign and check the handrail?",keywords:["drizzle","brisk","obstruct"],followUp:"Is another route available?"},
{id:"d155",level:"基础",title:"核对会议传闻",scenario:"工作会议",prompt:"Ask a colleague to distinguish documented evidence from hearsay.",model:"Could we verify the source before recording this allegation, since it currently appears to be hearsay?",keywords:["allegation","hearsay","verify"],followUp:"Where should the source be cited?"},
{id:"d156",level:"进阶",title:"描述临时解决方案",scenario:"Speaking Part 2",prompt:"Describe an impromptu solution that helped people make headway.",model:"We devised an impromptu booking system, and the nimble response helped the team make headway without losing customer records.",keywords:["impromptu","devise","nimble","headway"],followUp:"What would you improve next time?"},
{id:"d157",level:"进阶",title:"评估社区更新",scenario:"Speaking Part 3",prompt:"Explain how regeneration can benefit a district without depriving residents of affordable space.",model:"Regeneration can entice fledgling firms, but secure tenancies and affordable studios are needed so investment does not deprive residents of opportunity.",keywords:["regenerate","entice","fledgling","deprive"],followUp:"Who should monitor the results?"},
{id:"d158",level:"进阶",title:"反驳网络谣言",scenario:"社区群组",prompt:"Correct a harmful rumour with evidence without humiliating the person who shared it.",model:"The clinic's notice refutes that claim, so I would share the verified link and correct the rumour without trying to humiliate anyone.",keywords:["refute","hearsay","humiliate"],followUp:"When should moderators intervene?"},
{id:"d159",level:"进阶",title:"讨论洪水公平",scenario:"Speaking Part 3",prompt:"Explain why low-income households often bear the brunt of urban flooding.",model:"Households with scant savings bear the brunt because damaged furniture, temporary accommodation and lost work quickly exhaust their resources.",keywords:["scant","brunt","embankment"],followUp:"Which support should arrive first?"},
{id:"d160",level:"进阶",title:"调解共享空间争议",scenario:"社区工作室",prompt:"Mediate a dispute about blocked corridors and access to equipment.",model:"I would reiterate the safety rule, ask both members to explain their needs and mediate a schedule that keeps the corridor clear.",keywords:["reiterate","mediate","obstruct"],followUp:"What happens if the rule is ignored again?"}
];
