import type{SentenceChallenge}from"./sentence-challenges-base";
import type{SpeakingDrill}from"./speaking-drills-base";
export const sentenceChallengeBatch18:SentenceChallenge[]=[
{id:"g177",title:"反驳一种说法",level:"基础进阶",principle:"rebut + claim/argument",segments:[{text:"The records",role:"主语"},{text:"rebut",role:"谓语"},{text:"the allegation",role:"宾语"}],prompt:"The records ___ the allegation.",options:["rebut","rebuttal","are rebut"],correct:"rebut",explanation:"rebut 是及物动词，可直接接 claim 或 allegation。",errorHint:"此处需要谓语动词。",model:"The records rebut the allegation."},
{id:"g178",title:"与某人协调",level:"基础进阶",principle:"liaise with",segments:[{text:"The manager",role:"主语"},{text:"will liaise",role:"谓语"},{text:"with the council",role:"协调对象"}],prompt:"The manager will liaise ___ the council.",options:["with","to","at"],correct:"with",explanation:"liaise with someone 表示“与某人联络协调”。",errorHint:"固定搭配用 with。",model:"The manager will liaise with the council."},
{id:"g179",title:"侵占某处",level:"基础进阶",principle:"encroach on",segments:[{text:"New parking spaces",role:"主语"},{text:"must not encroach",role:"禁止行为"},{text:"on the wetland",role:"受影响区域"}],prompt:"New parking spaces must not encroach ___ the wetland.",options:["on","for","by"],correct:"on",explanation:"encroach on 表示逐渐侵占土地或权利。",errorHint:"被侵占对象前用 on。",model:"New parking spaces must not encroach on the wetland."},
{id:"g180",title:"勉强同意",level:"中级",principle:"acquiesce in/to",segments:[{text:"Residents",role:"主语"},{text:"would not acquiesce",role:"态度"},{text:"in the closure",role:"决定"}],prompt:"Residents would not acquiesce ___ the closure.",options:["in","from","over"],correct:"in",explanation:"acquiesce in a decision 表示默许或勉强接受。",errorHint:"此处不是争论 over。",model:"Residents would not acquiesce in the closure."},
{id:"g181",title:"驱使某人行动",level:"中级",principle:"impel someone to do",segments:[{text:"The rising cost",role:"主语"},{text:"may impel families",role:"影响"},{text:"to move",role:"行动"}],prompt:"The rising cost may impel families ___ move.",options:["to","for","with"],correct:"to",explanation:"impel someone to do 表示“驱使某人做某事”。",errorHint:"动作使用 to 加动词原形。",model:"The rising cost may impel families to move."},
{id:"g182",title:"超过供应",level:"中级",principle:"outstrip + noun",segments:[{text:"Demand",role:"主语"},{text:"continues to outstrip",role:"比较变化"},{text:"supply",role:"宾语"}],prompt:"Demand continues to ___ supply.",options:["outstrip","outstrips","be outstrip"],correct:"outstrip",explanation:"continue to 后接动词原形，outstrip 直接接宾语。",errorHint:"to 后不加 s。",model:"Demand continues to outstrip supply."},
{id:"g183",title:"违反规定",level:"中级",principle:"contravene + rule",segments:[{text:"The barrier",role:"主语"},{text:"may contravene",role:"可能违反"},{text:"access rules",role:"宾语"}],prompt:"The barrier may ___ access rules.",options:["contravene","contravenes","contravene against"],correct:"contravene",explanation:"contravene 是及物动词，直接接法规或规则。",errorHint:"may 后用原形且无需 against。",model:"The barrier may contravene access rules."},
{id:"g184",title:"使增长与排放脱钩",level:"中级",principle:"decouple A from B",segments:[{text:"The policy",role:"主语"},{text:"aims to decouple growth",role:"目标"},{text:"from emissions",role:"分离对象"}],prompt:"The policy aims to decouple growth ___ emissions.",options:["from","with","into"],correct:"from",explanation:"decouple A from B 表示把 A 与 B 分离。",errorHint:"分离对象前用 from。",model:"The policy aims to decouple growth from emissions."}
];
export const speakingDrillBatch18:SpeakingDrill[]=[
{id:"d177",level:"基础进阶",title:"预约家电维修",scenario:"生活服务",prompt:"描述故障、报出型号，并选择一个上门时段。",model:"My washing machine rattles and stops early. The model is HN46B, and Friday between one and three would suit me.",keywords:["rattle","model","suit"],followUp:"Is the utility cupboard accessible?"},
{id:"d178",level:"基础进阶",title:"说明营地疏散路线",scenario:"紧急沟通",prompt:"告诉同伴为什么要撤离、走哪条路线以及带什么。",model:"The river field is closing because heavy rain has saturated the valley. We should follow the blue signs and take medication, identification and warm clothes.",keywords:["saturate","evacuate","identification"],followUp:"Where will you park?"},
{id:"d179",level:"基础进阶",title:"报告疑似违规",scenario:"工作沟通",prompt:"只陈述观察到的事实、时间和可查记录，不作猜测。",model:"I observed two unrecorded payments on Tuesday afternoon. The till log and security footage may corroborate what happened.",keywords:["observe","record","corroborate"],followUp:"Could the reporting officer be involved?"},
{id:"d180",level:"中级",title:"描述克服语言障碍",scenario:"Speaking Part 2",prompt:"讲述你如何通过持续努力克服一次语言沟通困难。",model:"I had to explain a repair problem in English. I rehearsed the key details, spoke slowly and eventually surmounted the language barrier.",keywords:["rehearse","surmount","eventually"],followUp:"What would you do differently now?"},
{id:"d181",level:"中级",title:"评价处方集更新",scenario:"Speaking Part 3",prompt:"解释统一用药目录的好处以及为什么仍需例外程序。",model:"A formulary can control cost and standardise care, but clinicians need an exception process when allergy or infirmity makes the routine medicine unsuitable.",keywords:["formulary","infirmity","exception"],followUp:"Who should approve an exception?"},
{id:"d182",level:"中级",title:"讨论文化藏品返还",scenario:"Speaking Part 3",prompt:"提出返还的一项理由，并说明共享保管何时更实际。",model:"Repatriation can address historical injustice, while shared custody may be practical when conservation and public access require cooperation.",keywords:["repatriation","custody","conservation"],followUp:"Who should make the final decision?"},
{id:"d183",level:"中级",title:"解释效率反弹效应",scenario:"Speaking Part 3",prompt:"用交通例子解释为什么更高效率不一定降低总消耗。",model:"Efficient cars use less fuel per kilometre, but cheaper travel may impel people to drive farther, so total consumption can remain high.",keywords:["efficient","impel","consumption"],followUp:"What policy could limit this effect?"},
{id:"d184",level:"中级",title:"反驳没有证据的指控",scenario:"正式讨论",prompt:"礼貌指出证据不足，并说明哪些记录能验证事实。",model:"I understand the concern, but the allegation is not yet tenable. We should examine the payment log and interview the staff before drawing a conclusion.",keywords:["allegation","tenable","conclusion"],followUp:"How should confidentiality be protected?"}
];
