import type { SentenceChallenge } from "./sentence-challenges-base";
import type { SpeakingDrill } from "./speaking-drills-base";

export const sentenceChallengeBatch02: SentenceChallenge[] = [
  {id:"g37",title:"礼貌问句不倒装",level:"进阶",principle:"间接疑问句语序",segments:[{text:"Could you tell me",role:"礼貌引导"},{text:"where the office is",role:"陈述语序"},{text:"please",role:"礼貌补充"}],prompt:"Could you tell me where ___?",options:["is the office","the office is","the office"],correct:"the office is",explanation:"间接疑问句使用陈述语序：where + 主语 + 动词。",errorHint:"前面已有 Could you tell me，后面不再使用直接问句倒装。",model:"Could you tell me where the office is?"},
  {id:"g38",title:"空间是否足够",level:"进阶",principle:"形容词 + enough",segments:[{text:"The room",role:"主语"},{text:"is large enough",role:"足够程度"},{text:"for thirty people",role:"适用对象"}],prompt:"The room is ___ for thirty people.",options:["enough large","large enough","too large"],correct:"large enough",explanation:"enough 修饰形容词时放在形容词后面：large enough。",errorHint:"enough 放在名词前，但放在形容词后。",model:"The room is large enough for thirty people."},
  {id:"g39",title:"太重而无法搬动",level:"进阶",principle:"too + 形容词 + to",segments:[{text:"The box",role:"主语"},{text:"is too heavy",role:"超过合适程度"},{text:"to carry alone",role:"无法完成的动作"}],prompt:"The box is ___ alone.",options:["too heavy to carry","heavy enough to carry","so heavy carry"],correct:"too heavy to carry",explanation:"too heavy to carry 表示“太重，因此无法独自搬运”。",errorHint:"too 后接形容词，再用 to + 动词说明无法完成的动作。",model:"The box is too heavy to carry alone."},
  {id:"g40",title:"过去曾经如此",level:"进阶",principle:"used to + 动词原形",segments:[{text:"The building",role:"主语"},{text:"used to be",role:"过去状态"},{text:"a factory",role:"身份"}],prompt:"The building ___ a factory.",options:["use to be","used to be","was used be"],correct:"used to be",explanation:"used to + 动词原形表示过去存在、现在已经改变的状态。",errorHint:"这里不是“被用来”，而是讲过去曾经如此。",model:"The building used to be a factory."},
  {id:"g41",title:"从周一一直在维修",level:"进阶",principle:"现在完成进行时",segments:[{text:"They",role:"主语"},{text:"have been repairing",role:"持续动作"},{text:"the road since Monday",role:"起点"}],prompt:"They ___ the road since Monday.",options:["repaired","have repaired","have been repairing"],correct:"have been repairing",explanation:"动作从周一开始并仍在进行，用 have been + -ing。",errorHint:"since 给出起点，句子强调维修过程持续到现在。",model:"They have been repairing the road since Monday."},
  {id:"g42",title:"申请必须被提交",level:"进阶",principle:"情态动词被动语态",segments:[{text:"Applications",role:"承受动作"},{text:"must be submitted",role:"强制被动"},{text:"by Friday",role:"截止时间"}],prompt:"Applications must ___ by Friday.",options:["submit","be submitted","submitted"],correct:"be submitted",explanation:"申请是被提交的，must 后使用 be + 过去分词。",errorHint:"情态动词后先放 be，才能构成被动。",model:"Applications must be submitted by Friday."},
  {id:"g43",title:"转述未来安排",level:"进阶",principle:"间接引语中的 would",segments:[{text:"The manager said",role:"过去转述"},{text:"the office would close",role:"过去视角的未来"},{text:"early",role:"方式"}],prompt:"The manager said that the office ___ early.",options:["will close","would close","has closed"],correct:"would close",explanation:"过去时 said 后转述当时的未来安排，will 通常后移为 would。",errorHint:"站在过去的时间点看后续动作。",model:"The manager said that the office would close early."},
  {id:"g44",title:"两项都不包含",level:"进阶",principle:"neither ... nor",segments:[{text:"The fee includes",role:"主干"},{text:"neither meals",role:"否定项目一"},{text:"nor transport",role:"否定项目二"}],prompt:"The fee includes ___ meals nor transport.",options:["neither","either","both"],correct:"neither",explanation:"neither 与 nor 搭配，表示两项都不包含。",errorHint:"看到后面的 nor，寻找与它配对的词。",model:"The fee includes neither meals nor transport."},
  {id:"g45",title:"尽管天气很差",level:"进阶",principle:"despite + 名词短语",segments:[{text:"Despite the bad weather",role:"让步条件"},{text:"the event",role:"主语"},{text:"continued",role:"主要结果"}],prompt:"___ the bad weather, the event continued.",options:["Despite","Although","Because"],correct:"Despite",explanation:"the bad weather 是名词短语，前面用 Despite。",errorHint:"Although 后面需要主语和谓语构成完整从句。",model:"Despite the bad weather, the event continued."},
  {id:"g46",title:"除非出示通行证",level:"进阶",principle:"unless 表示必要条件",segments:[{text:"You cannot enter",role:"结果"},{text:"unless",role:"必要条件"},{text:"you show your pass",role:"条件"}],prompt:"You cannot enter ___ you show your pass.",options:["unless","because","although"],correct:"unless",explanation:"unless 相当于 if not，表示不出示通行证就不能进入。",errorHint:"后半句说明解除前面限制的必要条件。",model:"You cannot enter unless you show your pass."},
  {id:"g47",title:"补充说明新时间表",level:"进阶",principle:"非限制性定语从句",segments:[{text:"The new timetable",role:"先行词"},{text:"which starts on Monday",role:"补充信息"},{text:"adds two buses",role:"主句"}],prompt:"The new timetable, ___ starts on Monday, adds two buses.",options:["which","that","where"],correct:"which",explanation:"逗号之间是补充信息，指物时使用 which。",errorHint:"非限制性定语从句不能在这里使用 that。",model:"The new timetable, which starts on Monday, adds two buses."},
  {id:"g48",title:"不但减废还创造工作",level:"进阶",principle:"not only ... but also",segments:[{text:"The project",role:"主语"},{text:"not only reduced waste",role:"作用一"},{text:"but also created jobs",role:"作用二"}],prompt:"The project not only reduced waste ___ created jobs.",options:["but also","as well","although"],correct:"but also",explanation:"not only 与 but also 成对连接两个并列动作。",errorHint:"空格后是第二个并列的积极结果。",model:"The project not only reduced waste but also created jobs."},
];

export const speakingDrillBatch02: SpeakingDrill[] = [
  {id:"d37",level:"基础",title:"报告错误账单",scenario:"致电能源公司",prompt:"Explain that your bill includes a charge that is not yours.",model:"I am calling because my latest bill includes a charge for a service I did not receive.",keywords:["bill","charge","did not"],followUp:"Which date and amount are incorrect?"},
  {id:"d38",level:"基础",title:"查询包裹延误",scenario:"联系配送客服",prompt:"Ask when a delayed parcel will arrive.",model:"My parcel was due yesterday, so could you tell me when it is now expected to arrive?",keywords:["parcel","due","arrive"],followUp:"What is the tracking number?"},
  {id:"d39",level:"基础",title:"登记遗失交通卡",scenario:"在车站服务台",prompt:"Report a lost travel card and ask how to replace it.",model:"I lost my travel card this morning and I would like to know how I can get a replacement.",keywords:["lost","travel card","replacement"],followUp:"Where did you last use the card?"},
  {id:"d40",level:"基础",title:"确认课程费用",scenario:"致电成人学院",prompt:"Ask whether materials are included in the course fee.",model:"Could you confirm whether the course fee includes all the books and materials?",keywords:["confirm","fee","materials"],followUp:"Is payment required before the first class?"},
  {id:"d41",level:"进阶",title:"一次困难的决定",scenario:"Speaking Part 2",prompt:"Describe a difficult decision that you made.",model:"I decided to change my work schedule so that I could study regularly. It was difficult because I had to discuss new duties with my team, but the change gave me a reliable study routine.",keywords:["decided","because","result"],followUp:"Would you make the same decision again?"},
  {id:"d42",level:"进阶",title:"帮助陌生人的经历",scenario:"Speaking Part 2",prompt:"Describe a time when you helped someone you did not know.",model:"I helped a passenger understand the ticket machine at a station. I explained each step slowly, and in the end the person bought the correct ticket and reached the platform on time.",keywords:["helped","explained","in the end"],followUp:"Why are some people unwilling to ask for help?"},
  {id:"d43",level:"进阶",title:"实用的网站",scenario:"Speaking Part 2",prompt:"Describe a website that is useful in your daily life.",model:"I often use a local transport website because it shows live departures and service changes. It saves time, especially when bad weather affects the trains.",keywords:["use","because","especially"],followUp:"How could the website be improved?"},
  {id:"d44",level:"进阶",title:"安静的户外地点",scenario:"Speaking Part 2",prompt:"Describe a quiet outdoor place that you enjoy visiting.",model:"There is a small riverside park near my home. I usually walk there in the early morning, when there are few people and the traffic is less noticeable.",keywords:["near","usually","when"],followUp:"Why do cities need quiet public spaces?"},
  {id:"d45",level:"进阶",title:"优质客户服务",scenario:"Speaking Part 3",prompt:"What makes customer service effective?",model:"Effective service requires clear information, realistic response times and staff who can take responsibility instead of passing the customer between departments.",keywords:["clear","response","responsibility"],followUp:"Should companies compensate customers after every mistake?"},
  {id:"d46",level:"进阶",title:"旧建筑的新用途",scenario:"Speaking Part 3",prompt:"Why do some cities convert old buildings instead of replacing them?",model:"Reuse can protect local character and reduce construction waste; however, older structures may be expensive to make safe, accessible and energy efficient.",keywords:["protect","however","accessible"],followUp:"Which old buildings are most worth preserving?"},
  {id:"d47",level:"进阶",title:"公共空间的无障碍",scenario:"Speaking Part 3",prompt:"How can public spaces serve a wider range of people?",model:"Designers should provide step-free routes, clear signs, seating and safe crossings, while consulting people whose needs are often overlooked.",keywords:["provide","while","needs"],followUp:"Who should pay for these improvements?"},
  {id:"d48",level:"进阶",title:"个人数据保护",scenario:"Speaking Part 3",prompt:"Why are people concerned about how companies use personal data?",model:"People may not know what is collected or who receives it. Clear consent and limited storage can improve trust, but rules also need effective enforcement.",keywords:["collected","consent","but"],followUp:"Should convenience ever be exchanged for less privacy?"},
];
