import type { SentenceChallenge } from "./sentence-challenges-base";
import type { SpeakingDrill } from "./speaking-drills-base";

export const sentenceChallengeBatch08:SentenceChallenge[]=[
  {id:"g97",title:"打算完成某事",level:"基础",principle:"intend to + 动词原形",segments:[{text:"I",role:"主语"},{text:"intend",role:"意图"},{text:"to renew my passport",role:"计划行动"}],prompt:"I intend ___ my passport before travelling.",options:["to renew","renewing","renew"],correct:"to renew",explanation:"intend to do 表示“打算做某事”，to 后接动词原形。",errorHint:"不要把 intend 和 enjoy 的结构混用。",model:"I intend to renew my passport before travelling."},
  {id:"g98",title:"应对压力",level:"基础",principle:"cope with + 名词",segments:[{text:"New carers",role:"主语"},{text:"must cope with",role:"应对关系"},{text:"daily pressure",role:"对象"}],prompt:"New carers must cope ___ daily pressure.",options:["with","for","at"],correct:"with",explanation:"cope with 是固定搭配，表示应对问题或压力。",errorHint:"这里需要介词 with 连接应对的对象。",model:"New carers must cope with daily pressure."},
  {id:"g99",title:"低于资格门槛",level:"基础",principle:"below + threshold",segments:[{text:"Households",role:"主语"},{text:"below the income threshold",role:"条件修饰"},{text:"may apply",role:"结果"}],prompt:"Households ___ the income threshold may apply.",options:["below","beneath to","down"],correct:"below",explanation:"below the threshold 表示低于规定的界线。",errorHint:"threshold 是抽象标准，最自然的搭配是 below。",model:"Households below the income threshold may apply."},
  {id:"g100",title:"直到某事发生期间",level:"进阶",principle:"in the meantime",segments:[{text:"The lift is being repaired",role:"背景"},{text:"in the meantime",role:"时间连接"},{text:"use the stairs",role:"临时措施"}],prompt:"The lift is being repaired; ___, use the stairs.",options:["in the meantime","on the contrary","as a result of"],correct:"in the meantime",explanation:"in the meantime 表示“在此期间”，连接维修与临时安排。",errorHint:"这里不是对比，也不能在 as a result of 后直接接完整指令。",model:"The lift is being repaired; in the meantime, use the stairs."},
  {id:"g101",title:"满足全部条件",level:"进阶",principle:"satisfy + requirements/conditions",segments:[{text:"The evidence",role:"主语"},{text:"must satisfy",role:"必须满足"},{text:"all requirements",role:"标准"}],prompt:"The evidence must ___ all requirements.",options:["satisfy","satisfied","satisfying"],correct:"satisfy",explanation:"情态动词 must 后接动词原形 satisfy。",errorHint:"must 后不能接过去式或现在分词。",model:"The evidence must satisfy all requirements."},
  {id:"g102",title:"不仅是理论而且有实践",level:"进阶",principle:"combine A with B",segments:[{text:"The course",role:"主语"},{text:"combines theory",role:"第一部分"},{text:"with practical work",role:"第二部分"}],prompt:"The course combines theory ___ practical work.",options:["with","to","by"],correct:"with",explanation:"combine A with B 表示把两部分结合起来。",errorHint:"此处固定使用 with，不用 to。",model:"The course combines theory with practical work."},
  {id:"g103",title:"只在特定条件下可行",level:"进阶",principle:"viable where + 从句",segments:[{text:"Night delivery",role:"主语"},{text:"is viable",role:"可行判断"},{text:"where rules are enforced",role:"条件"}],prompt:"Night delivery is viable ___ rules are enforced.",options:["where","unless of","despite"],correct:"where",explanation:"where 可引导表示条件环境的从句，即“在规则得到执行的地方／情况下”。",errorHint:"despite 后应接名词，unless 不与 of 连用。",model:"Night delivery is viable where rules are enforced."},
  {id:"g104",title:"把某事视为整体的一部分",level:"进阶",principle:"be integral to + 名词",segments:[{text:"Clear communication",role:"主语"},{text:"is integral to",role:"不可或缺关系"},{text:"safe care",role:"整体"}],prompt:"Clear communication is integral ___ safe care.",options:["to","for being","with to"],correct:"to",explanation:"be integral to 表示“对……不可或缺”，to 是介词。",errorHint:"integral 后固定使用 to，再接名词或动名词。",model:"Clear communication is integral to safe care."},
];

export const speakingDrillBatch08:SpeakingDrill[]=[
  {id:"d97",level:"基础",title:"报告洗衣房漏水",scenario:"致电物业管理员",prompt:"Report a leaking washing machine and explain what you have already done.",model:"The second washing machine is leaking underneath, so I switched it off and placed a warning sign beside the door.",keywords:["leak","underneath","warning"],followUp:"When did you first notice the water?"},
  {id:"d98",level:"基础",title:"确认护照要求",scenario:"致电旅行服务台",prompt:"Ask whether your passport will remain valid long enough for a planned trip.",model:"Could you confirm whether my passport must be valid for the entire journey or for an additional period afterwards?",keywords:["passport","valid","journey"],followUp:"Which country are you travelling to?"},
  {id:"d99",level:"基础",title:"请求工作场所调整",scenario:"与直属经理沟通",prompt:"Explain a practical adaptation that would help you work safely.",model:"A height-adjustable desk would be a reasonable adaptation because my current position is causing ankle and back pain.",keywords:["adaptation","reasonable","pain"],followUp:"Do you have a medical recommendation?"},
  {id:"d100",level:"进阶",title:"描述难忘的展览",scenario:"Speaking Part 2",prompt:"Describe a museum exhibition that you admired.",model:"I visited a maritime exhibition with a superb collection of ship models, and the guide made the history both clear and memorable.",keywords:["maritime","admire","memorable"],followUp:"Would you visit the museum again?"},
  {id:"d101",level:"进阶",title:"解释夜间货运立场",scenario:"Speaking Part 3",prompt:"Explain when night freight can be a viable policy.",model:"Night freight is viable where authorities set a measurable noise threshold, require quiet equipment and respond to residents' complaints.",keywords:["freight","viable","threshold"],followUp:"Who should pay for quieter vehicles?"},
  {id:"d102",level:"进阶",title:"讨论持续职业培训",scenario:"Speaking Part 3",prompt:"Explain why employers may need to provide regular training.",model:"Regular training helps staff adapt to sophisticated technology, strengthens safety and gives experienced workers a fair chance to progress.",keywords:["adapt","sophisticated","strengthen"],followUp:"Should workers train in their own time?"},
  {id:"d103",level:"进阶",title:"回应不当言论",scenario:"向人力资源部门说明情况",prompt:"Report an inappropriate remark without exaggerating what happened.",model:"I want to report an inappropriate remark made during training because it was personal, repeated and created a hostile atmosphere.",keywords:["inappropriate","hostile","report"],followUp:"Were there any witnesses?"},
  {id:"d104",level:"进阶",title:"权衡一个社区提案",scenario:"委员会公开讨论",prompt:"Assess the merit of a proposal to extend library hours during heatwaves.",model:"The proposal has clear merit because it offers a cool public space, but we should first gauge demand and confirm that staffing costs are viable.",keywords:["merit","gauge","viable"],followUp:"How would you measure whether it worked?"},
];
