import type { SentenceChallenge } from "./sentence-challenges-base";
import type { SpeakingDrill } from "./speaking-drills-base";

export const sentenceChallengeBatch09:SentenceChallenge[]=[
 {id:"g105",title:"反对某项计划",level:"基础",principle:"oppose + 名词/动名词",segments:[{text:"Residents",role:"主语"},{text:"oppose",role:"反对"},{text:"the proposal",role:"对象"}],prompt:"Several residents ___ the proposal.",options:["oppose","opposes","opposing to"],correct:"oppose",explanation:"复数主语 residents 后用动词原形 oppose，后面直接接对象。",errorHint:"oppose 后不加 to。",model:"Several residents oppose the proposal."},
 {id:"g106",title:"容易发生某事",level:"基础",principle:"be prone to + 名词/动名词",segments:[{text:"The road",role:"主语"},{text:"is prone to",role:"易发关系"},{text:"flooding",role:"问题"}],prompt:"The road is prone ___ flooding.",options:["to","for","with"],correct:"to",explanation:"be prone to 表示容易出现某种问题，to 是介词。",errorHint:"to 后可接名词 flooding。",model:"The road is prone to flooding."},
 {id:"g107",title:"不得超过限制",level:"基础",principle:"must not exceed",segments:[{text:"Your bag",role:"主语"},{text:"must not exceed",role:"限制"},{text:"the weight limit",role:"标准"}],prompt:"Your bag must not ___ the weight limit.",options:["exceed","exceeds","exceeded"],correct:"exceed",explanation:"情态动词 must 后接动词原形。",errorHint:"这里不用第三人称或过去式。",model:"Your bag must not exceed the weight limit."},
 {id:"g108",title:"尽管存在一个限制",level:"进阶",principle:"albeit + 形容词/短语",segments:[{text:"The route is shorter",role:"主句"},{text:"albeit",role:"让步连接"},{text:"slightly more expensive",role:"限制"}],prompt:"The route is shorter, ___ slightly more expensive.",options:["albeit","therefore of","because to"],correct:"albeit",explanation:"albeit 表示“尽管”，常接形容词或简短成分。",errorHint:"这里需要让步，不是因果。",model:"The route is shorter, albeit slightly more expensive."},
 {id:"g109",title:"妨碍某项活动",level:"进阶",principle:"interfere with",segments:[{text:"Noise",role:"主语"},{text:"may interfere with",role:"妨碍关系"},{text:"the examination",role:"对象"}],prompt:"Noise may interfere ___ the examination.",options:["with","to","against"],correct:"with",explanation:"interfere with 是固定搭配，表示干扰某事。",errorHint:"不要按中文直译选择 to。",model:"Noise may interfere with the examination."},
 {id:"g110",title:"构成有效证明",level:"进阶",principle:"constitute + 名词",segments:[{text:"These documents",role:"主语"},{text:"constitute",role:"构成"},{text:"valid proof",role:"结果"}],prompt:"These documents ___ valid proof of residence.",options:["constitute","constitutes","are constitute"],correct:"constitute",explanation:"复数主语直接使用 constitute，表示共同构成。",errorHint:"constitute 本身就是谓语，不加 are。",model:"These documents constitute valid proof of residence."},
 {id:"g111",title:"把反馈纳入计划",level:"进阶",principle:"incorporate A into B",segments:[{text:"The team",role:"主语"},{text:"incorporated feedback",role:"纳入内容"},{text:"into the plan",role:"目标"}],prompt:"The team incorporated feedback ___ the plan.",options:["into","among","onto of"],correct:"into",explanation:"incorporate A into B 表示把 A 纳入 B。",errorHint:"这里强调进入整体，使用 into。",model:"The team incorporated feedback into the plan."},
 {id:"g112",title:"说服某人采取行动",level:"进阶",principle:"persuade someone to do",segments:[{text:"The evidence",role:"主语"},{text:"persuaded the council",role:"说服对象"},{text:"to restore the service",role:"行动"}],prompt:"The evidence persuaded the council ___ the service.",options:["to restore","restoring","restore to"],correct:"to restore",explanation:"persuade someone to do something 是固定结构。",errorHint:"被说服后采取的行动使用 to 加动词原形。",model:"The evidence persuaded the council to restore the service."},
];

export const speakingDrillBatch09:SpeakingDrill[]=[
 {id:"d105",level:"基础",title:"改约牙科检查",scenario:"致电牙科诊所",prompt:"Move a dental appointment and mention a new symptom.",model:"I cannot attend today because I injured my ankle, so I would like to move the check-up and mention a dull pain in my lower jaw.",keywords:["dentist","ankle","jaw"],followUp:"Which afternoon can you attend?"},
 {id:"d106",level:"基础",title:"询问徒步安全要求",scenario:"联系户外活动中心",prompt:"Ask about the route, weather and equipment for a guided hike.",model:"Could you tell me the route length, expected altitude and whether robust waterproof boots are required?",keywords:["hike","altitude","robust"],followUp:"How much water should each walker carry?"},
 {id:"d107",level:"基础",title:"澄清文件保密要求",scenario:"向隐私负责人咨询",prompt:"Ask how to send a confidential file outside the organisation.",model:"Could you clarify which encrypted system I should use and what information must be removed before I disclose the file?",keywords:["clarify","confidential","disclose"],followUp:"Who is the intended recipient?"},
 {id:"d108",level:"进阶",title:"描述一次户外长途步行",scenario:"Speaking Part 2",prompt:"Describe a long walk that required preparation and endurance.",model:"I joined an inland hike to a ruined abbey, and the changing altitude, fierce hail and lengthy route tested my endurance.",keywords:["inland","hail","endure"],followUp:"What would you prepare differently next time?"},
 {id:"d109",level:"进阶",title:"评估自动驾驶原型",scenario:"Speaking Part 3",prompt:"Explain what an autonomous bus prototype should prove before public use.",model:"The prototype should demonstrate robust collision avoidance, clear passenger communication and competent performance in an independent simulation.",keywords:["prototype","robust","simulation"],followUp:"Who should analyze the test evidence?"},
 {id:"d110",level:"进阶",title:"讨论近海风电项目",scenario:"Speaking Part 3",prompt:"Explain how an offshore wind project can gain lasting local support.",model:"It should disclose its environmental impact, recruit local workers and provide a defined economic dividend rather than a symbolic payment.",keywords:["offshore","recruit","dividend"],followUp:"Which concerns would justify opposing it?"},
 {id:"d111",level:"进阶",title:"判断地标投资价值",scenario:"Speaking Part 3",prompt:"Assess whether a new landmark is a desirable public investment.",model:"A landmark is desirable when it incorporates useful services, has transparent overhead and can sustain renewal after publicity fades.",keywords:["landmark","overhead","sustain"],followUp:"How should the council measure success?"},
 {id:"d112",level:"进阶",title:"解释结构化招聘",scenario:"人力资源会议",prompt:"Explain why interview panels should use systematic questions and scores.",model:"A systematic interview helps distinguish evidence from instinct, supports reasonable adaptation and creates a defensible justification for the decision.",keywords:["systematic","distinguish","justification"],followUp:"When is a follow-up question appropriate?"},
];
