import type { SentenceChallenge } from "./sentence-challenges-base";
import type { SpeakingDrill } from "./speaking-drills-base";

export const sentenceChallengeBatch07:SentenceChallenge[]=[
  {id:"g89",title:"结果取决于条件",level:"基础",principle:"depend on + 名词",segments:[{text:"Approval",role:"主语"},{text:"depends on",role:"条件关系"},{text:"the evidence",role:"条件"}],prompt:"Approval will depend ___ the evidence.",options:["on","at","from"],correct:"on",explanation:"depend on 表示“取决于／依赖”。",errorHint:"这个固定搭配使用介词 on。",model:"Approval will depend on the evidence."},
  {id:"g90",title:"把整体分成部分",level:"基础",principle:"divide A into B",segments:[{text:"Divide",role:"动作"},{text:"the class",role:"对象"},{text:"into four groups",role:"结果"}],prompt:"Divide the class ___ four groups.",options:["into","onto","among to"],correct:"into",explanation:"divide A into B 表示“把A分成B”。",errorHint:"这里强调分成后的结果，使用 into。",model:"Divide the class into four groups."},
  {id:"g91",title:"敦促某人采取行动",level:"基础",principle:"urge + 人 + to do",segments:[{text:"Doctors",role:"主语"},{text:"urge patients",role:"敦促对象"},{text:"to complete treatment",role:"行动"}],prompt:"Doctors urge patients ___ the treatment.",options:["to complete","completing","complete to"],correct:"to complete",explanation:"urge someone to do something 是固定结构。",errorHint:"urge 后先接人，再接 to 加动词原形。",model:"Doctors urge patients to complete the treatment."},
  {id:"g92",title:"与预期相反",level:"进阶",principle:"contrary to + 名词",segments:[{text:"Contrary to",role:"对比引导"},{text:"the forecast",role:"对照信息"},{text:"the road stayed open",role:"实际结果"}],prompt:"___ the forecast, the road stayed open.",options:["Contrary to","Moreover","Beneath"],correct:"Contrary to",explanation:"contrary to 引出与实际结果相反的预期。",errorHint:"这里不是补充信息或方位关系。",model:"Contrary to the forecast, the road stayed open."},
  {id:"g93",title:"造成一种风险",level:"进阶",principle:"pose + a risk/threat",segments:[{text:"Loose cables",role:"风险源"},{text:"pose",role:"造成"},{text:"a serious risk",role:"风险"}],prompt:"Loose cables ___ a serious risk.",options:["pose","pursue","yield"],correct:"pose",explanation:"pose a risk/threat 表示“造成风险／威胁”。",errorHint:"不是追求风险，也不是产生结果。",model:"Loose cables pose a serious risk."},
  {id:"g94",title:"不仅不减少反而加重",level:"进阶",principle:"rather than + 动词原形",segments:[{text:"The rule",role:"主语"},{text:"increased confusion",role:"实际结果"},{text:"rather than reducing it",role:"对照"}],prompt:"The rule increased confusion rather than ___ it.",options:["reducing","reduced","to reduce"],correct:"reducing",explanation:"rather than 在这里连接并列动作，前有 increased，后用动名词表达对照过程。",errorHint:"介词化结构后使用 reducing。",model:"The rule increased confusion rather than reducing it."},
  {id:"g95",title:"尽管存在部分分歧",level:"进阶",principle:"although + 完整从句",segments:[{text:"Although",role:"让步连接"},{text:"the agreement was partial",role:"让步从句"},{text:"work could proceed",role:"主句"}],prompt:"___ the agreement was partial, work could proceed.",options:["Although","Because of","Moreover"],correct:"Although",explanation:"although 后接完整主谓从句，表达让步。",errorHint:"because of 后不能直接接完整句，moreover 不引导从句。",model:"Although the agreement was partial, work could proceed."},
  {id:"g96",title:"信息不但准确而且匿名",level:"进阶",principle:"both ... and ...",segments:[{text:"The feedback",role:"主语"},{text:"must be both accurate",role:"第一要求"},{text:"and anonymous",role:"第二要求"}],prompt:"The feedback must be both accurate ___ anonymous.",options:["and","but","or to"],correct:"and",explanation:"both 与 and 成对连接两个并列性质。",errorHint:"这里两个要求同时成立。",model:"The feedback must be both accurate and anonymous."},
];

export const speakingDrillBatch07:SpeakingDrill[]=[
  {id:"d89",level:"基础",title:"预约维修水泵",scenario:"致电维修公司",prompt:"Report a noisy pump and request a morning appointment.",model:"The pump beside the hot-water tank is making a harsh noise, so I would like to arrange a morning inspection.",keywords:["pump","harsh","inspection"],followUp:"Is there any water beneath the pump?"},
  {id:"d90",level:"基础",title:"询问避难所入口",scenario:"致电社区服务处",prompt:"Ask where the overnight shelter entrance is and what to bring.",model:"Could you tell me where the overnight shelter entrance is and whether I should bring a blanket or medication?",keywords:["overnight","shelter","bring"],followUp:"Do you need help with transport?"},
  {id:"d91",level:"基础",title:"报告资料误发",scenario:"联系隐私负责人",prompt:"Explain that your personal data was sent to the wrong person.",model:"I need to report a possible data breach because an email containing my personal details was sent to another customer.",keywords:["data","breach","customer"],followUp:"When did you discover the email?"},
  {id:"d92",level:"进阶",title:"解释匿名调查",scenario:"向员工介绍调查",prompt:"Explain how the survey protects anonymity while comparing departments.",model:"The survey is anonymous, and we will not publish a departmental result when fewer than ten people have responded.",keywords:["anonymous","publish","department"],followUp:"Can staff add a written comment?"},
  {id:"d93",level:"进阶",title:"描述一次海港游览",scenario:"Speaking Part 2",prompt:"Describe a cruise, boat trip or visit to a harbour that you remember.",model:"I joined an evening harbour cruise and saw a striking mixture of historic naval buildings and modern galleries.",keywords:["harbour","cruise","striking"],followUp:"What made the trip memorable?"},
  {id:"d94",level:"进阶",title:"讨论公共监控",scenario:"Speaking Part 3",prompt:"When is video surveillance justified in a public place?",model:"Surveillance is justified only when it tackles a precise risk, stores data securely and gives the public a genuine route to challenge misuse.",keywords:["surveillance","precise","justified"],followUp:"Should facial recognition be treated differently?"},
  {id:"d95",level:"进阶",title:"讨论异议价值",scenario:"Speaking Part 3",prompt:"Why can disagreement improve a group decision?",model:"A respectful dispute can highlight weak evidence, reveal hidden risks and prevent a false consensus created by pressure.",keywords:["dispute","highlight","consensus"],followUp:"When should discussion finally stop?"},
  {id:"d96",level:"进阶",title:"讨论创新资助",scenario:"Speaking Part 3",prompt:"Which small projects deserve public innovation funding?",model:"A project deserves funding when it tackles a real local problem, has a realistic cost breakdown and can generate lasting public value.",keywords:["tackle","breakdown","lasting"],followUp:"How should its result be measured?"},
];
