import type{SentenceChallenge}from"./sentence-challenges-base";
import type{SpeakingDrill}from"./speaking-drills-base";

export const sentenceChallengeBatch17:SentenceChallenge[]=[
{id:"g169",title:"有权获得某物",level:"基础进阶",principle:"entitle someone to something",segments:[{text:"This ticket",role:"主语"},{text:"entitles you",role:"谓语与宾语"},{text:"to a free transfer",role:"权利内容"}],prompt:"This ticket entitles you ___ a free transfer.",options:["to","for","with"],correct:"to",explanation:"entitle someone to something 表示“使某人有权获得某物”。",errorHint:"权利内容前使用 to。",model:"This ticket entitles you to a free transfer."},
{id:"g170",title:"与……一致",level:"基础进阶",principle:"be congruent with",segments:[{text:"The new rule",role:"主语"},{text:"is congruent",role:"系表结构"},{text:"with current policy",role:"比较对象"}],prompt:"The new rule is congruent ___ current policy.",options:["with","to","from"],correct:"with",explanation:"congruent with 表示“与……一致或相符”。",errorHint:"固定搭配使用 with。",model:"The new rule is congruent with current policy."},
{id:"g171",title:"从信息中推断",level:"基础进阶",principle:"glean something from",segments:[{text:"Readers",role:"主语"},{text:"can glean useful details",role:"谓语与宾语"},{text:"from the notice",role:"信息来源"}],prompt:"Readers can glean useful details ___ the notice.",options:["from","at","over"],correct:"from",explanation:"glean information from a source 表示“从某来源收集或了解到信息”。",errorHint:"来源前使用 from。",model:"Readers can glean useful details from the notice."},
{id:"g172",title:"被……吓倒",level:"中级",principle:"undaunted by",segments:[{text:"She remained undaunted",role:"主干"},{text:"by the rejection",role:"让步背景"},{text:"and applied again",role:"并列结果"}],prompt:"She remained undaunted ___ the rejection.",options:["by","of","for"],correct:"by",explanation:"undaunted by 表示“没有被……吓倒”。",errorHint:"说明未造成畏惧的事物用 by 引出。",model:"She remained undaunted by the rejection and applied again."},
{id:"g173",title:"取代旧规则",level:"中级",principle:"supersede something",segments:[{text:"The digital pass",role:"主语"},{text:"will supersede",role:"谓语"},{text:"the paper permit",role:"宾语"}],prompt:"The digital pass will ___ the paper permit.",options:["supersede","superseded","be superseding by"],correct:"supersede",explanation:"will 后接动词原形；supersede 本身可直接带宾语。",errorHint:"不要添加多余介词或被动结构。",model:"The digital pass will supersede the paper permit."},
{id:"g174",title:"使担忧缓和",level:"中级",principle:"assuage concerns",segments:[{text:"Independent tests",role:"主语"},{text:"may assuage",role:"谓语"},{text:"public concerns",role:"宾语"}],prompt:"Independent tests may ___ public concerns.",options:["assuage","assuages","assuaging to"],correct:"assuage",explanation:"may 后使用动词原形，assuage 可直接接 concerns。",errorHint:"情态动词后不加 s。",model:"Independent tests may assuage public concerns."},
{id:"g175",title:"放弃责任",level:"中级",principle:"abdicate responsibility for",segments:[{text:"Managers",role:"主语"},{text:"cannot abdicate responsibility",role:"谓语与宾语"},{text:"for staff safety",role:"责任范围"}],prompt:"Managers cannot abdicate responsibility ___ staff safety.",options:["for","of","at"],correct:"for",explanation:"responsibility for something 表示“对某事的责任”。",errorHint:"责任对象前使用 for。",model:"Managers cannot abdicate responsibility for staff safety."},
{id:"g176",title:"逐渐减少",level:"中级",principle:"begin to dwindle",segments:[{text:"Passenger numbers",role:"主语"},{text:"began to dwindle",role:"变化"},{text:"after nine",role:"时间背景"}],prompt:"Passenger numbers began ___ after nine.",options:["to dwindle","dwindle to","dwindled"],correct:"to dwindle",explanation:"begin to do 表示“开始做或开始发生”。",errorHint:"begin 后用 to 加动词原形。",model:"Passenger numbers began to dwindle after nine."}
];

export const speakingDrillBatch17:SpeakingDrill[]=[
{id:"d169",level:"基础进阶",title:"改约公证服务",scenario:"市政服务",prompt:"说明原预约时间、提出新的时间并确认需要携带的材料。",model:"I need to change my appointment from Monday to Thursday afternoon. Could you confirm whether I should bring the original agreement and photo identification?",keywords:["appointment","confirm","identification"],followUp:"How many certified copies do you need?"},
{id:"d170",level:"基础进阶",title:"报告步道安全问题",scenario:"户外与安全",prompt:"报告一段湿滑道路，说明具体位置，并建议临时绕行。",model:"The lower path near marker six is extremely slippery after the rain. Could walkers use the yellow uphill route until it is inspected?",keywords:["slippery","marker","inspect"],followUp:"Is the route still passable for children?"},
{id:"d171",level:"基础进阶",title:"询问食物过敏信息",scenario:"餐馆沟通",prompt:"说明自己的过敏原，并要求对方核对调味品和交叉接触风险。",model:"I am allergic to sesame. Could you check every condiment in this dish and tell me whether it is prepared on a separate surface?",keywords:["allergic","condiment","separate"],followUp:"How severe is your allergy?"},
{id:"d172",level:"中级",title:"描述一处恢复活力的地方",scenario:"Speaking Part 2",prompt:"描述一处经过更新后重新吸引人们的建筑或地区。",model:"An abandoned mansion in my town was rejuvenated as a museum. The project preserved the main rooms while adding accessible public facilities.",keywords:["mansion","rejuvenate","accessible"],followUp:"What changed most after it reopened?"},
{id:"d173",level:"中级",title:"解释为何结论被夸大",scenario:"学习讨论",prompt:"礼貌指出一个结论超过了样本所能支持的范围。",model:"The result is interesting, but saying that every neighbourhood benefits would overstate the evidence because the study covered only three sites.",keywords:["overstate","evidence","sample"],followUp:"What additional data would strengthen the claim?"},
{id:"d174",level:"中级",title:"提出夜班疲劳对策",scenario:"Speaking Part 3",prompt:"说明过度加班的风险，并提出雇主可以采取的两项措施。",model:"Inordinate overtime can impair judgement and overwork employees. Employers should rotate demanding tasks and provide scheduled rest breaks.",keywords:["inordinate","overwork","rotate"],followUp:"What responsibility do workers have?"},
{id:"d175",level:"中级",title:"讨论公共机构的责任",scenario:"Speaking Part 3",prompt:"解释为什么透明证据和问责制度可以建立公众信任。",model:"Independent evidence can assuage concern, while clear accountability prevents officials from abdicating responsibility for harmful decisions.",keywords:["assuage","accountability","abdicate"],followUp:"Should every official decision be published?"},
{id:"d176",level:"中级",title:"评价废水循环利用",scenario:"Speaking Part 3",prompt:"讨论循环用水的一个好处、一个公众担忧和一个必要保障。",model:"Recycling treated effluent can protect rivers during drought, but authorities need independent testing to address public trepidation and guarantee safety.",keywords:["effluent","trepidation","testing"],followUp:"Where should recycled water be used first?"}
];
