import type{SentenceChallenge}from"./sentence-challenges-base";
import type{SpeakingDrill}from"./speaking-drills-base";

export const sentenceChallengeBatch16:SentenceChallenge[]=[
{id:"g161",title:"排除某种可能",level:"蝓ｺ遑",principle:"preclude + 名词 / doing",segments:[{text:"The injury",role:"主语"},{text:"may preclude him",role:"谓语与宾语"},{text:"from lifting",role:"被排除的行动"}],prompt:"The injury may preclude him ___ lifting heavy boxes.",options:["from","of","at"],correct:"from",explanation:"preclude someone from doing 表示使某人无法做某事。",errorHint:"这里需要 from 引出被阻止的行动。",model:"The injury may preclude him from lifting heavy boxes."},
{id:"g162",title:"减损整体体验",level:"蝓ｺ遑",principle:"detract from",segments:[{text:"Constant noise",role:"主语"},{text:"detracts",role:"谓语"},{text:"from the experience",role:"受影响对象"}],prompt:"Constant noise detracts ___ the visitor experience.",options:["from","with","into"],correct:"from",explanation:"detract from something 表示减损某事物的价值或效果。",errorHint:"固定搭配使用 from。",model:"Constant noise detracts from the visitor experience."},
{id:"g163",title:"坚持完成行动",level:"蝓ｺ遑",principle:"persevere with / in",segments:[{text:"Learners",role:"主语"},{text:"should persevere",role:"情态与谓语"},{text:"with daily practice",role:"持续事项"}],prompt:"Learners should persevere ___ daily practice.",options:["with","against","beside"],correct:"with",explanation:"persevere with something 表示虽有困难仍坚持某事。",errorHint:"这里不是反对某事，而是坚持练习。",model:"Learners should persevere with daily practice."},
{id:"g164",title:"把责任托付给某人",level:"霑幃亳",principle:"entrust A with B",segments:[{text:"Parents",role:"主语"},{text:"entrust the nursery",role:"托付对象"},{text:"with daily care",role:"托付事项"}],prompt:"Parents entrust the nursery ___ their children's daily care.",options:["with","from","by"],correct:"with",explanation:"entrust someone with something 表示把某项责任托付给某人。",errorHint:"托付的事项由 with 引出。",model:"Parents entrust the nursery with their children's daily care."},
{id:"g165",title:"接着发生的结果",level:"霑幃亳",principle:"ensue 不及物",segments:[{text:"Confusion",role:"主语"},{text:"may ensue",role:"可能发生"},{text:"after conflicting advice",role:"时间背景"}],prompt:"Confusion may ___ after conflicting advice.",options:["ensue","ensues","be ensue"],correct:"ensue",explanation:"情态动词 may 后使用动词原形 ensue，且不需要被动。",errorHint:"may 后不加 s，也不用 be。",model:"Confusion may ensue after conflicting advice."},
{id:"g166",title:"使问题进一步恶化",level:"霑幃亳",principle:"exacerbate + 名词",segments:[{text:"Delayed repairs",role:"主语"},{text:"will exacerbate",role:"谓语"},{text:"the damp problem",role:"直接宾语"}],prompt:"Delayed repairs will ___ the damp problem.",options:["exacerbate","exacerbating","exacerbated by"],correct:"exacerbate",explanation:"will 后用动词原形，exacerbate 直接接问题作宾语。",errorHint:"这里需要主动语态的动词原形。",model:"Delayed repairs will exacerbate the damp problem."},
{id:"g167",title:"从证据中推断",level:"霑幃亳",principle:"deduce A from B",segments:[{text:"Readers",role:"主语"},{text:"can deduce the view",role:"推断内容"},{text:"from the conclusion",role:"证据来源"}],prompt:"Readers can deduce the writer's view ___ the conclusion.",options:["from","for","across"],correct:"from",explanation:"deduce something from evidence 表示从证据推断结论。",errorHint:"证据来源使用 from。",model:"Readers can deduce the writer's view from the conclusion."},
{id:"g168",title:"使某事成为必要",level:"霑幃亳",principle:"necessitate + 名词 / doing",segments:[{text:"Structural damage",role:"主语"},{text:"may necessitate",role:"谓语"},{text:"temporary closure",role:"必要结果"}],prompt:"Structural damage may ___ temporary closure.",options:["necessitate","necessitates","necessitating to"],correct:"necessitate",explanation:"may 后用原形；necessitate 可直接接名词。",errorHint:"不要在情态动词后加 s，也不要加多余的 to。",model:"Structural damage may necessitate temporary closure."}
];

export const speakingDrillBatch16:SpeakingDrill[]=[
{id:"d161",level:"蝓ｺ遑",title:"预约房屋维修",scenario:"租房生活",prompt:"Report a stuffy room and a pungent odour, then request a specific inspection time.",model:"My bedroom is very stuffy and there is a pungent odour near the vent. Could an engineer inspect it on Wednesday afternoon?",keywords:["stuffy","pungent","inspect"],followUp:"Has the problem affected your health?"},
{id:"d162",level:"蝓ｺ遑",title:"报告工作场所小事故",scenario:"工作与安全",prompt:"Describe a minor mishap, say what you have already done and ask what should happen next.",model:"A container fell and a small amount of liquid spilled. I stopped the machine and kept everyone away; what should I do next?",keywords:["mishap","spill","disengage"],followUp:"Can you identify the substance?"},
{id:"d163",level:"蝓ｺ遑",title:"礼貌反驳不准确信息",scenario:"社区会议",prompt:"Correct an inaccurate claim by referring to evidence without belittling the speaker.",model:"I understand the concern, but the inspection report appears to disprove that claim. Could we examine the figures together?",keywords:["disprove","evidence","belittle"],followUp:"Which figure is most relevant?"},
{id:"d164",level:"霑幃亳",title:"描述一次坚持完成的任务",scenario:"Speaking Part 2",prompt:"Describe a difficult task that you managed to complete by persevering.",model:"I nearly gave up on a formal application, but I divided it into short stages, persevered with the paperwork and submitted it before the deadline.",keywords:["persevere","procrastination","succinct"],followUp:"What made the task difficult at first?"},
{id:"d165",level:"霑幃亳",title:"讨论城市扩张的代价",scenario:"Speaking Part 3",prompt:"Explain how urban sprawl can affect transport, farmland and people without cars.",model:"Urban sprawl may erode arable land and necessitate longer journeys, while residents without cars become alienated from essential services.",keywords:["sprawl","erode","arable","alienate"],followUp:"What would a better neighbourhood provide?"},
{id:"d166",level:"霑幃亳",title:"建议应对城市高温",scenario:"Speaking Part 3",prompt:"Propose a layered response that protects underprivileged residents during extreme heat.",model:"Cities should subsidize insulation, open cool public rooms and disseminate unambiguous warnings, especially in underprivileged districts.",keywords:["subsidize","disseminate","unambiguous"],followUp:"How should success be measured?"},
{id:"d167",level:"霑幃亳",title:"处理专横管理方式",scenario:"工作沟通",prompt:"Tell a manager that an inflexible rule is stifling staff input and suggest a fair alternative.",model:"The inflexible rule is beginning to stifle useful feedback, so could we trial a confidential suggestion process for one month?",keywords:["inflexible","stifle","confidential"],followUp:"Who should review the suggestions?"},
{id:"d168",level:"霑幃亳",title:"解释研究结论的边界",scenario:"Speaking Part 3",prompt:"Explain why a small sample cannot support an infallible conclusion.",model:"A small and dissimilar sample may reveal a pattern, but it is too tenuous to justify an infallible conclusion about the whole population.",keywords:["dissimilar","tenuous","infallible"],followUp:"What additional evidence is needed?"}
];
