import type {SentenceChallenge} from "./sentence-challenges-base";import type {SpeakingDrill} from "./speaking-drills-base";
export const sentenceChallengeBatch10:SentenceChallenge[]=[
 {id:"g113",title:"陪同某人",level:"基础",principle:"accompany + 人",segments:[{text:"An adult",role:"主语"},{text:"must accompany",role:"陪同"},{text:"each child",role:"对象"}],prompt:"An adult must ___ each child.",options:["accompany","accompany with","accompanies"],correct:"accompany",explanation:"must 后接动词原形，accompany 直接接人。",errorHint:"accompany 后不需要 with。",model:"An adult must accompany each child."},
 {id:"g114",title:"不愿采取行动",level:"基础",principle:"reluctant to do",segments:[{text:"Some residents",role:"主语"},{text:"are reluctant",role:"态度"},{text:"to leave",role:"行动"}],prompt:"Some residents are reluctant ___ the area.",options:["to leave","leaving","leave to"],correct:"to leave",explanation:"be reluctant to do 表示不情愿做某事。",errorHint:"使用 to 加动词原形。",model:"Some residents are reluctant to leave the area."},
 {id:"g115",title:"阻止问题扩大",level:"基础",principle:"curb + 名词",segments:[{text:"The policy",role:"主语"},{text:"aims to curb",role:"抑制"},{text:"dangerous driving",role:"对象"}],prompt:"The policy aims to ___ dangerous driving.",options:["curb","curbed","curbing to"],correct:"curb",explanation:"aim to 后接动词原形 curb。",errorHint:"这里不使用过去式。",model:"The policy aims to curb dangerous driving."},
 {id:"g116",title:"把变化归因于原因",level:"进阶",principle:"attribute A to B",segments:[{text:"Researchers",role:"主语"},{text:"attribute the change",role:"结果"},{text:"to earlier checks",role:"原因"}],prompt:"Researchers attribute the change ___ earlier checks.",options:["to","for","with"],correct:"to",explanation:"attribute A to B 表示把 A 归因于 B。",errorHint:"固定介词是 to。",model:"Researchers attribute the change to earlier checks."},
 {id:"g117",title:"取决于批准",level:"进阶",principle:"contingent on",segments:[{text:"Funding",role:"主语"},{text:"is contingent on",role:"条件"},{text:"approval",role:"结果"}],prompt:"Funding is contingent ___ approval.",options:["on","at","from"],correct:"on",explanation:"be contingent on 表示取决于某条件。",errorHint:"这里固定使用 on。",model:"Funding is contingent on approval."},
 {id:"g118",title:"超出有限容量",level:"进阶",principle:"exceed + 名词",segments:[{text:"Demand",role:"主语"},{text:"may exceed",role:"超过"},{text:"local capacity",role:"界限"}],prompt:"Demand may ___ local capacity.",options:["exceed","exceeds","be exceed"],correct:"exceed",explanation:"may 后接动词原形 exceed。",errorHint:"情态动词后不加 s。",model:"Demand may exceed local capacity."},
 {id:"g119",title:"帮助某人理解",level:"进阶",principle:"help someone comprehend",segments:[{text:"Diagrams",role:"主语"},{text:"help patients comprehend",role:"帮助理解"},{text:"the options",role:"对象"}],prompt:"Diagrams help patients ___ the options.",options:["comprehend","comprehended","comprehending to"],correct:"comprehend",explanation:"help someone do 后可接动词原形。",errorHint:"这里不用过去式。",model:"Diagrams help patients comprehend the options."},
 {id:"g120",title:"既不理想也不可行",level:"进阶",principle:"neither A nor B",segments:[{text:"A total ban",role:"主语"},{text:"is neither feasible",role:"第一判断"},{text:"nor desirable",role:"第二判断"}],prompt:"A total ban is neither feasible ___ desirable.",options:["nor","or to","but"],correct:"nor",explanation:"neither 与 nor 成对连接两个并列成分。",errorHint:"neither 后对应 nor。",model:"A total ban is neither feasible nor desirable."},
];
export const speakingDrillBatch10:SpeakingDrill[]=[
 {id:"d113",level:"基础",title:"处理超重行李",scenario:"机场值机柜台",prompt:"Ask about options for an overweight suitcase.",model:"My luggage exceeds the allowance by three kilograms; could I move some items into my cabin baggage instead of paying the charge?",keywords:["luggage","exceed","baggage"],followUp:"Which items do you want to transfer?"},
 {id:"d114",level:"基础",title:"报告儿童药物要求",scenario:"幼儿园接待处",prompt:"Explain the medicine your child needs and provide parental consent.",model:"My child needs this prescribed medicine at noon, and I have attached the signed parental form that matches the original label.",keywords:["parental","attach","medicine"],followUp:"Who is the second emergency contact?"},
 {id:"d115",level:"基础",title:"询问学徒评估",scenario:"联系培训主管",prompt:"Ask what evidence is required for an apprentice review.",model:"Could you clarify whether my work log, completed tasks and supervisor feedback are sufficient evidence for the apprentice review?",keywords:["apprentice","clarify","sufficient"],followUp:"Do you need any change to the review format?"},
 {id:"d116",level:"进阶",title:"描述社区应急行动",scenario:"Speaking Part 2",prompt:"Describe a time when people united to confront an emergency.",model:"Residents united during a flood, distributed sandbags and helped reluctant neighbours flee before the water surrounded their homes.",keywords:["unite","distribute","flee"],followUp:"What was the greatest obstacle?"},
 {id:"d117",level:"进阶",title:"讨论公共健康沟通",scenario:"Speaking Part 3",prompt:"Explain why blunt health messages can fail.",model:"Blunt correction may deepen stigma and contempt, whereas interpreting a genuine objection makes persuasion more feasible.",keywords:["stigma","interpret","feasible"],followUp:"When is celebrity endorsement useful?"},
 {id:"d118",level:"进阶",title:"分析招聘研究",scenario:"Speaking Part 3",prompt:"Describe how to test prejudice without creating a biased study.",model:"Researchers can compare identical applications, modify only one attribute and acknowledge that a simulation has limited predictive power.",keywords:["prejudice","modify","simulation"],followUp:"Should participants know the hypothesis first?"},
 {id:"d119",level:"进阶",title:"权衡旅游限制",scenario:"Speaking Part 3",prompt:"Explain when a tourist destination should curb visitor numbers.",model:"Restrictions are apt when demand exceeds finite capacity, damages fragile sites and prevents residents from accessing housing.",keywords:["curb","finite","fragile"],followUp:"How could local businesses be protected?"},
 {id:"d120",level:"进阶",title:"反对公共项目",scenario:"规划听证会",prompt:"Raise a formal objection to a vanity project.",model:"I object because the proposal offers prestige and decoration but lacks comparative costs, public services and a feasible long-term plan.",keywords:["objection","prestige","feasible"],followUp:"What alternative would you support?"},
];
