import type{SentenceChallenge}from"./sentence-challenges-base";import type{SpeakingDrill}from"./speaking-drills-base";
export const sentenceChallengeBatch19:SentenceChallenge[]=[
{id:"g185",title:"习惯某种环境",level:"基础进阶",principle:"accustom someone to",segments:[{text:"Daily listening",role:"主语"},{text:"can accustom learners",role:"作用"},{text:"to natural speed",role:"适应对象"}],prompt:"Daily listening can accustom learners ___ natural speed.",options:["to","for","with"],correct:"to",explanation:"accustom someone to something 表示使某人习惯某事。",errorHint:"适应对象前使用 to。",model:"Daily listening can accustom learners to natural speed."},
{id:"g186",title:"经过一段时间",level:"基础进阶",principle:"time + elapse",segments:[{text:"Twenty minutes",role:"时间主语"},{text:"must elapse",role:"必须经过"},{text:"before the test",role:"后续节点"}],prompt:"Twenty minutes must ___ before the test.",options:["elapse","elapsed","be elapsing by"],correct:"elapse",explanation:"情态动词 must 后接原形 elapse。",errorHint:"不要使用过去式。",model:"Twenty minutes must elapse before the test."},
{id:"g187",title:"安抚担忧",level:"基础进阶",principle:"mollify + person/group",segments:[{text:"A clear explanation",role:"主语"},{text:"may mollify",role:"作用"},{text:"angry passengers",role:"宾语"}],prompt:"A clear explanation may ___ angry passengers.",options:["mollify","mollifies","mollify to"],correct:"mollify",explanation:"may 后接原形，mollify 直接接被安抚的人。",errorHint:"不需要介词 to。",model:"A clear explanation may mollify angry passengers."},
{id:"g188",title:"限制权力范围",level:"中级",principle:"circumscribe + power",segments:[{text:"The law",role:"主语"},{text:"should circumscribe",role:"限制"},{text:"surveillance powers",role:"宾语"}],prompt:"The law should ___ surveillance powers.",options:["circumscribe","circumscribes","circumscribe around"],correct:"circumscribe",explanation:"should 后用原形，circumscribe 直接接被限制对象。",errorHint:"此处无需 around。",model:"The law should circumscribe surveillance powers."},
{id:"g189",title:"从手术中康复",level:"中级",principle:"convalesce after/from",segments:[{text:"She returned home",role:"主干"},{text:"to convalesce",role:"目的"},{text:"after surgery",role:"背景"}],prompt:"She returned home to convalesce ___ surgery.",options:["after","among","towards"],correct:"after",explanation:"convalesce after surgery 表示术后休养。",errorHint:"选择表示时间顺序的 after。",model:"She returned home to convalesce after surgery."},
{id:"g190",title:"反驳一种解释",level:"中级",principle:"controvert + claim",segments:[{text:"New evidence",role:"主语"},{text:"may controvert",role:"反驳"},{text:"the original claim",role:"宾语"}],prompt:"New evidence may ___ the original claim.",options:["controvert","controverts","controvert against"],correct:"controvert",explanation:"controvert 是及物动词，直接接 claim。",errorHint:"may 后用原形且不加 against。",model:"New evidence may controvert the original claim."},
{id:"g191",title:"给予投票权",level:"中级",principle:"enfranchise + people",segments:[{text:"The reform",role:"主语"},{text:"will enfranchise",role:"赋权"},{text:"previously excluded citizens",role:"对象"}],prompt:"The reform will ___ previously excluded citizens.",options:["enfranchise","enfranchised","be enfranchise"],correct:"enfranchise",explanation:"will 后接原形，enfranchise 表示给予政治权利。",errorHint:"此处是主动语态。",model:"The reform will enfranchise previously excluded citizens."},
{id:"g192",title:"过度开发资源",level:"中级",principle:"overexploit + resource",segments:[{text:"Mass tourism",role:"主语"},{text:"can overexploit",role:"影响"},{text:"local water supplies",role:"宾语"}],prompt:"Mass tourism can ___ local water supplies.",options:["overexploit","overexploits","overexploit of"],correct:"overexploit",explanation:"can 后用原形，overexploit 直接接资源。",errorHint:"不要加 of。",model:"Mass tourism can overexploit local water supplies."}
];
export const speakingDrillBatch19:SpeakingDrill[]=[
{id:"d185",level:"基础进阶",title:"咨询弹性办公会员",scenario:"生活与工作",prompt:"说明使用频率，询问费用、开放时间和包含设施。",model:"I need a desk three mornings a week. Could you explain the flexible monthly fee, included facilities and staffed reception hours?",keywords:["flexible","facility","staffed"],followUp:"Would you prefer a fixed weekday plan?"},
{id:"d186",level:"基础进阶",title:"说明海岸志愿任务",scenario:"环境活动",prompt:"告诉同伴分组任务、工具位置和撤离时间。",model:"Our team will plant native grass behind the fence. The tools are in the green trailer, and we must leave the lower path before noon.",keywords:["native","trailer","path"],followUp:"Why is the lower path closing?"},
{id:"d187",level:"基础进阶",title:"报告地图数据局限",scenario:"学习讨论",prompt:"说明两个数据源边界不一致以及某类人群缺失。",model:"The census and transport survey use different boundaries, and the survey excludes people working from home, so the comparison needs caution.",keywords:["boundary","exclude","comparison"],followUp:"How could you reduce the problem?"},
{id:"d188",level:"中级",title:"描述适应新环境的经历",scenario:"Speaking Part 2",prompt:"讲述你如何逐渐适应新的天气、工作或学习环境。",model:"It took several weeks to acclimatize to the colder climate. A stable routine and short outdoor walks gradually accustomed me to it.",keywords:["acclimatize","accustom","gradually"],followUp:"What was hardest at first?"},
{id:"d189",level:"中级",title:"讨论弹性工时公平性",scenario:"Speaking Part 3",prompt:"说明弹性工时如何帮助员工，以及管理者需要设置什么边界。",model:"Flexitime can support caring responsibilities, but managers should define a core period and review any restriction transparently.",keywords:["flexitime","circumscribe","transparent"],followUp:"Could customers be disadvantaged?"},
{id:"d190",level:"中级",title:"解释普查不能单独解决的问题",scenario:"Speaking Part 3",prompt:"说明普查的价值、时效局限以及为何要组合其他数据。",model:"A census gives a universal benchmark, but it ages quickly in a megacity, so planners should interweave it with recent administrative and survey data.",keywords:["census","megacity","interweave"],followUp:"What privacy risk could arise?"},
{id:"d191",level:"中级",title:"提出城市热风险对策",scenario:"Speaking Part 3",prompt:"给出一项短期保护、一项长期设计和一种非数字沟通方式。",model:"Cooling rooms can mollify immediate risk, while shade and revegetation offer durable protection. Staff should also visit isolated residents directly.",keywords:["mollify","revegetation","isolated"],followUp:"Which neighbourhood should be prioritised?"},
{id:"d192",level:"中级",title:"指出轻视投诉的后果",scenario:"公共服务",prompt:"礼貌说明机构不应轻视居民经验，并提出核实方式。",model:"We should not trivialize these reports. Local residents can identify the hottest flats, so their evidence should be checked against temperature and clinic data.",keywords:["trivialize","identify","evidence"],followUp:"How would you collect their evidence?"}
];
