import type{SentenceChallenge}from"./sentence-challenges-base";import type{SpeakingDrill}from"./speaking-drills-base";
export const sentenceChallengeBatch14:SentenceChallenge[]=[
{id:"g145",title:"取决于证据",level:"基础",principle:"hinge on",segments:[{text:"Approval",role:"主语"},{text:"hinges on",role:"取决于"},{text:"evidence",role:"条件"}],prompt:"Approval hinges ___ evidence.",options:["on","at","from"],correct:"on",explanation:"hinge on 表示取决于。",errorHint:"固定介词是 on。",model:"Approval hinges on clear evidence."},
{id:"g146",title:"有资格获得",level:"基础",principle:"eligible for",segments:[{text:"She",role:"主语"},{text:"is eligible for",role:"有资格"},{text:"the grant",role:"对象"}],prompt:"She is eligible ___ the grant.",options:["for","to","with"],correct:"for",explanation:"eligible for 后接福利或项目。",errorHint:"资格对象前用 for。",model:"She is eligible for the training grant."},
{id:"g147",title:"带来额外费用",level:"基础",principle:"incur + costs",segments:[{text:"Delay",role:"主语"},{text:"may incur",role:"产生"},{text:"costs",role:"结果"}],prompt:"Delay may ___ extra costs.",options:["incur","incurs","incurring to"],correct:"incur",explanation:"may 后接动词原形。",errorHint:"情态动词后不用 s。",model:"Delay may incur extra costs."},
{id:"g148",title:"妨碍理解",level:"进阶",principle:"hamper + 名词",segments:[{text:"Jargon",role:"主语"},{text:"can hamper",role:"妨碍"},{text:"understanding",role:"对象"}],prompt:"Jargon can ___ understanding.",options:["hamper","hampers","hamper to"],correct:"hamper",explanation:"can 后使用 hamper 原形。",errorHint:"直接接宾语，不加介词。",model:"Technical jargon can hamper understanding."},
{id:"g149",title:"大于缺点",level:"进阶",principle:"outweigh + 名词",segments:[{text:"Benefits",role:"主语"},{text:"outweigh",role:"超过"},{text:"drawbacks",role:"比较对象"}],prompt:"The benefits ___ the drawbacks.",options:["outweigh","outweighs","are outweigh"],correct:"outweigh",explanation:"复数主语使用动词原形。",errorHint:"benefits 是复数。",model:"The long-term benefits outweigh the drawbacks."},
{id:"g150",title:"与结果相关",level:"进阶",principle:"correlate A with B",segments:[{text:"Researchers",role:"主语"},{text:"correlate sleep",role:"变量一"},{text:"with memory",role:"变量二"}],prompt:"Researchers correlate sleep ___ memory.",options:["with","to be","from"],correct:"with",explanation:"correlate A with B 表示分析相关性。",errorHint:"第二变量前用 with。",model:"Researchers correlate sleep with memory."},
{id:"g151",title:"需要关闭设施",level:"进阶",principle:"entail + doing",segments:[{text:"Repairs",role:"主语"},{text:"will entail",role:"意味着"},{text:"closing the hall",role:"后果"}],prompt:"Repairs will entail ___ the hall.",options:["closing","to close","close"],correct:"closing",explanation:"entail 后接名词或动名词。",errorHint:"这里使用 closing。",model:"Repairs will entail closing the hall."},
{id:"g152",title:"区分可靠信息",level:"进阶",principle:"discern A from B",segments:[{text:"Users",role:"主语"},{text:"must discern facts",role:"辨别"},{text:"from rumours",role:"对照"}],prompt:"Users must discern facts ___ rumours.",options:["from","with","onto"],correct:"from",explanation:"discern A from B 表示区分两者。",errorHint:"对照来源使用 from。",model:"Users must discern facts from rumours."}
];
export const speakingDrillBatch14:SpeakingDrill[]=[
{id:"d145",level:"基础",title:"咨询职业培训",scenario:"学院接待处",prompt:"Ask about prerequisites, fees and the course timetable.",model:"Could you tell me whether experience is a prerequisite, what the fee includes and when the course begins?",keywords:["prerequisite","fee","itinerary"],followUp:"What vocation interests you?"},
{id:"d146",level:"基础",title:"报告化学品泄漏",scenario:"工作场所",prompt:"Report a ruptured pesticide container and describe the immediate action.",model:"A pesticide container has ruptured, so we isolated the puddle, moved upwind and notified the supervisor.",keywords:["pesticide","rupture","inhale"],followUp:"Was anyone injured?"},
{id:"d147",level:"基础",title:"要求易读说明",scenario:"公共服务柜台",prompt:"Explain that jargon makes a letter difficult to understand.",model:"The legal jargon is difficult to discern, so could you summarize the required action in lucid language?",keywords:["jargon","discern","lucid"],followUp:"Would a translated version help?"},
{id:"d148",level:"进阶",title:"描述团队合作",scenario:"Speaking Part 2",prompt:"Describe a fruitful project that required practical ingenuity.",model:"Our team refined the plan after a technical snag, and strong cohesion helped us complete the project successfully.",keywords:["fruitful","ingenuity","snag"],followUp:"What was your role?"},
{id:"d149",level:"进阶",title:"比较学历与经验",scenario:"Speaking Part 3",prompt:"Explain how employers can assess vocational aptitude fairly.",model:"Qualifications affirm standard training, but supervised tasks can illuminate aptitude gained through practical experience.",keywords:["affirm","aptitude","illuminate"],followUp:"Which jobs require certification?"},
{id:"d150",level:"进阶",title:"讨论湿地修复",scenario:"Speaking Part 3",prompt:"Explain why wetland restoration may benefit a city.",model:"Wetlands nurture wildlife, hamper flood waves and provide intangible benefits that may outweigh short-term disruption.",keywords:["nurture","hamper","intangible"],followUp:"Who may incur costs?"},
{id:"d151",level:"进阶",title:"反对目击者恐吓",scenario:"社区会议",prompt:"Explain why witnesses need legal protection.",model:"Overt attempts to intimidate an eyewitness can withhold evidence and undermine confidence in justice.",keywords:["overt","intimidate","eyewitness"],followUp:"How should intimidation be reported?"},
{id:"d152",level:"进阶",title:"分析清晰传播",scenario:"工作培训",prompt:"Explain how instructions can reduce malfunction and injury.",model:"Lucid steps, luminous signs and a comprehension check can prevent a malfunction from injuring workers.",keywords:["lucid","luminous","malfunction"],followUp:"When should instructions be updated?"}
];
