import type{SentenceChallenge}from"./sentence-challenges-base";import type{SpeakingDrill}from"./speaking-drills-base";
export const sentenceChallengeBatch11:SentenceChallenge[]=[
 {id:"g121",title:"为不便道歉",level:"基础",principle:"apologise for + 名词",segments:[{text:"We",role:"主语"},{text:"apologise for",role:"道歉"},{text:"the inconvenience",role:"对象"}],prompt:"We apologise ___ the inconvenience.",options:["for","to","with"],correct:"for",explanation:"apologise for something 表示为某事道歉。",errorHint:"这里固定使用 for。",model:"We apologise for the inconvenience."},
 {id:"g122",title:"遵守安全规定",level:"基础",principle:"adhere to",segments:[{text:"Contractors",role:"主语"},{text:"must adhere to",role:"遵守"},{text:"the rules",role:"对象"}],prompt:"Contractors must adhere ___ the rules.",options:["to","at","from"],correct:"to",explanation:"adhere to 表示遵守规定。",errorHint:"固定介词是 to。",model:"Contractors must adhere to the rules."},
 {id:"g123",title:"易受极端天气影响",level:"基础",principle:"susceptible to",segments:[{text:"Older people",role:"主语"},{text:"are susceptible to",role:"易受影响"},{text:"extreme heat",role:"风险"}],prompt:"Older people are susceptible ___ extreme heat.",options:["to","for","with"],correct:"to",explanation:"be susceptible to 表示易受某事影响。",errorHint:"使用介词 to。",model:"Older people are susceptible to extreme heat."},
 {id:"g124",title:"使培训符合标准",level:"进阶",principle:"align A with B",segments:[{text:"We",role:"主语"},{text:"align training",role:"对齐对象"},{text:"with the standard",role:"标准"}],prompt:"We align training ___ the standard.",options:["with","onto","from"],correct:"with",explanation:"align A with B 表示使两者一致。",errorHint:"标准搭配使用 with。",model:"We align training with the standard."},
 {id:"g125",title:"事先提交文件",level:"进阶",principle:"beforehand",segments:[{text:"Submit insurance",role:"行动"},{text:"beforehand",role:"时间"},{text:"to avoid delay",role:"目的"}],prompt:"Submit the insurance ___ to avoid delay.",options:["beforehand","onwards of","backward"],correct:"beforehand",explanation:"beforehand 表示事先、提前。",errorHint:"这里需要时间副词。",model:"Submit the insurance beforehand to avoid delay."},
 {id:"g126",title:"既保留又改进",level:"进阶",principle:"while + 动词-ing",segments:[{text:"Modify the process",role:"主要行动"},{text:"while retaining",role:"同时保留"},{text:"the standard",role:"对象"}],prompt:"Modify the process while ___ the standard.",options:["retaining","retain","retained to"],correct:"retaining",explanation:"while 后用现在分词表示同时发生。",errorHint:"此处是省略主语的伴随结构。",model:"Modify the process while retaining the standard."},
 {id:"g127",title:"阻止某人参与",level:"进阶",principle:"discourage someone from doing",segments:[{text:"High fees",role:"主语"},{text:"discourage families",role:"阻止对象"},{text:"from attending",role:"行动"}],prompt:"High fees discourage families ___ attending.",options:["from","to","against to"],correct:"from",explanation:"discourage someone from doing 是固定结构。",errorHint:"这里使用 from 加动名词。",model:"High fees discourage families from attending."},
 {id:"g128",title:"达到专业掌握",level:"进阶",principle:"attain + 名词",segments:[{text:"Learners",role:"主语"},{text:"attain",role:"达到"},{text:"practical mastery",role:"目标"}],prompt:"Learners can ___ practical mastery through use.",options:["attain","attains","attained to"],correct:"attain",explanation:"can 后接动词原形 attain。",errorHint:"情态动词后不用第三人称。",model:"Learners can attain practical mastery through use."},
];
export const speakingDrillBatch11:SpeakingDrill[]=[
 {id:"d121",level:"基础",title:"修改宴会预订",scenario:"致电社区馆",prompt:"Increase the guest number and ask about outside catering.",model:"I need to modify our booking to eighty guests and ask whether an outside caterer may use the kitchen.",keywords:["modify","banquet","caterer"],followUp:"Do you require additional tables?"},
 {id:"d122",level:"基础",title:"报告森林步道危险",scenario:"联系护林员",prompt:"Report smoke and a damaged tree near a trail perimeter.",model:"I noticed fresh smoke and a damaged tree near the eastern perimeter, so I left the area and called immediately.",keywords:["blaze","perimeter","imminent"],followUp:"Which route did you use?"},
 {id:"d123",level:"基础",title:"报告可疑付款",scenario:"致电银行",prompt:"Describe a fraudulent payment and ask the bank to suspend your card.",model:"I do not recognise this payment, so please suspend my card, intercept the transaction and assign a case number.",keywords:["fraudulent","suspend","intercept"],followUp:"Have you changed your password?"},
 {id:"d124",level:"进阶",title:"描述解决设备问题",scenario:"Speaking Part 2",prompt:"Describe a time you helped overhaul an outdated system.",model:"During my internship, we replaced an obsolete booking tool, removed duplicate records and created a versatile new workflow.",keywords:["obsolete","duplicate","versatile"],followUp:"What tangible improvement followed?"},
 {id:"d125",level:"进阶",title:"讨论应用成瘾设计",scenario:"Speaking Part 3",prompt:"Explain how technology can manipulate users' attention.",model:"Addictive apps use perpetual alerts and tempting rewards to interrupt users, so regulation should require transparent controls.",keywords:["manipulate","addictive","interrupt"],followUp:"What responsibility belongs to users?"},
 {id:"d126",level:"进阶",title:"评估公园更新",scenario:"Speaking Part 3",prompt:"Explain how a park overhaul can reinforce belonging.",model:"Planners should align design with local needs, provide ample access and measure tangible outcomes instead of superficial aesthetics.",keywords:["align","tangible","superficial"],followUp:"Which groups are often peripheral?"},
 {id:"d127",level:"进阶",title:"讨论实习质量",scenario:"Speaking Part 3",prompt:"Describe what makes an internship rewarding rather than exploitative.",model:"A rewarding placement assigns meaningful work, provides a competent tutor and never uses an intern to replace redundant staff.",keywords:["assign","tutor","redundant"],followUp:"When should a placement terminate?"},
 {id:"d128",level:"进阶",title:"解释城市绿地价值",scenario:"Speaking Part 3",prompt:"Explain why green space is more than attractive decoration.",model:"A vibrant park can stimulate activity, relieve stress and create an urban oasis, provided people can navigate it safely.",keywords:["vibrant","stimulate","navigate"],followUp:"How can benefits be measured?"},
];
