import type { SentenceChallenge } from "./sentence-challenges-base";
import type { SpeakingDrill } from "./speaking-drills-base";

export const sentenceChallengeBatch06: SentenceChallenge[] = [
  {id:"g81",title:"最近持续发生的变化",level:"基础",principle:"have/has + 过去分词 + lately",segments:[{text:"Services",role:"主语"},{text:"have improved",role:"现在完成时"},{text:"lately",role:"近期时间"}],prompt:"Bus services ___ lately.",options:["have improved","improve yesterday","has improving"],correct:"have improved",explanation:"lately 表示延续到现在的近期，常与现在完成时搭配。",errorHint:"services 是复数，使用 have 加过去分词。",model:"Bus services have improved lately."},
  {id:"g82",title:"要求读者查阅信息",level:"基础",principle:"refer to + 名词",segments:[{text:"Please refer to",role:"指引动作"},{text:"the final chart",role:"查阅对象"},{text:"for details",role:"目的"}],prompt:"Please refer ___ the final chart for details.",options:["to","at","with"],correct:"to",explanation:"refer to 表示“查阅／提到”。",errorHint:"这里不是 look at 的介词结构。",model:"Please refer to the final chart for details."},
  {id:"g83",title:"描述事物归属",level:"基础",principle:"belong to + 人或事物",segments:[{text:"These keys",role:"主语"},{text:"belong to",role:"归属"},{text:"the laboratory",role:"所有者"}],prompt:"These keys belong ___ the laboratory.",options:["to","for","into"],correct:"to",explanation:"belong to 是固定搭配，表示“属于”。",errorHint:"belong 不使用进行时，也不能省略 to。",model:"These keys belong to the laboratory."},
  {id:"g84",title:"被普遍认为是",level:"进阶",principle:"be regarded as + 名词",segments:[{text:"The change",role:"主语"},{text:"is regarded as",role:"评价结构"},{text:"a success",role:"评价"}],prompt:"The change is regarded ___ a major success.",options:["as","to","for"],correct:"as",explanation:"regard A as B 表示“把 A 视为 B”，被动形式为 A is regarded as B。",errorHint:"不要把中文“认为是”逐词套成 regarded to。",model:"The change is regarded as a major success."},
  {id:"g85",title:"正式表达因此",level:"进阶",principle:"hence + 名词短语",segments:[{text:"The road is flooded",role:"原因"},{text:"hence",role:"结果连接"},{text:"the diversion",role:"结果"}],prompt:"The road is flooded, ___ the diversion.",options:["hence","despite","meanwhile"],correct:"hence",explanation:"hence 可直接连接由前因产生的名词性结果。",errorHint:"这里表达因果，不是让步或同时发生。",model:"The road is flooded, hence the diversion."},
  {id:"g86",title:"后续动作的时间关系",level:"进阶",principle:"subsequent + 名词",segments:[{text:"A subsequent inspection",role:"后续事件"},{text:"confirmed",role:"谓语"},{text:"the repair",role:"对象"}],prompt:"A ___ inspection confirmed the repair was safe.",options:["subsequent","subsequently","sequence"],correct:"subsequent",explanation:"inspection 是名词，需要形容词 subsequent 修饰。",errorHint:"subsequently 是副词，不能直接修饰名词。",model:"A subsequent inspection confirmed the repair was safe."},
  {id:"g87",title:"更有可能成功",level:"进阶",principle:"be likely to + 动词原形",segments:[{text:"Prepared applicants",role:"主语"},{text:"are likely to",role:"可能性"},{text:"succeed",role:"结果"}],prompt:"Prepared applicants are likely to ___.",options:["succeed","success","succeeded"],correct:"succeed",explanation:"be likely to 后接动词原形。",errorHint:"success 是名词，succeeded 是过去式。",model:"Prepared applicants are likely to succeed."},
  {id:"g88",title:"不仅……而且……",level:"进阶",principle:"not only ... but also ...",segments:[{text:"The policy",role:"主语"},{text:"improves not only safety",role:"第一作用"},{text:"but also equity",role:"第二作用"}],prompt:"The policy improves not only safety ___ equity.",options:["but also","despite","because"],correct:"but also",explanation:"not only 与 but also 成对连接两个并列项目。",errorHint:"空格后是第二个并列受益点，不是原因。",model:"The policy improves not only safety but also equity."},
];

export const speakingDrillBatch06: SpeakingDrill[] = [
  {id:"d81",level:"基础",title:"领取外币",scenario:"在旅行服务柜台",prompt:"Ask when you can collect your foreign currency and what document to bring.",model:"Could you tell me when I can collect the foreign currency and whether I need to bring my passport?",keywords:["collect","currency","passport"],followUp:"How much would you like to exchange?"},
  {id:"d82",level:"基础",title:"报告化学品泄漏",scenario:"联系工作场所主管",prompt:"Report a visible liquid spill and say what you have already done.",model:"There is a visible liquid spill near the laboratory door, so I have warned the team and kept everyone away.",keywords:["visible","liquid","laboratory"],followUp:"Can you identify the chemical safely?"},
  {id:"d83",level:"基础",title:"请求丧亲假",scenario:"与经理私下交谈",prompt:"Explain that you need time off to attend a family funeral.",model:"I need to request compassionate leave because I must travel to attend a close family funeral next week.",keywords:["request","funeral","travel"],followUp:"Do you know which working days you will need?"},
  {id:"d84",level:"进阶",title:"解释一次投诉调查",scenario:"向顾客说明处理流程",prompt:"Explain that an independent officer will investigate and contact the customer later.",model:"An independent officer will investigate the incident, review the available footage and contact you with the outcome within ten working days.",keywords:["independent","investigate","footage"],followUp:"Which evidence have you already provided?"},
  {id:"d85",level:"进阶",title:"描述一处文化场所",scenario:"Speaking Part 2",prompt:"Describe a museum, gallery or historic place that you found interesting.",model:"I visited a contemporary art gallery in a historic building. Its visual displays revealed the cultural legacy of several local communities.",keywords:["contemporary","visual","legacy"],followUp:"What would improve the visitor experience?"},
  {id:"d86",level:"进阶",title:"讨论公共艺术投入",scenario:"Speaking Part 3",prompt:"Is public funding for arts a worthy investment?",model:"It is a worthy investment when it widens access, fosters education and boosts local commerce, provided that fundamental public services remain protected.",keywords:["worthy","fosters","commerce"],followUp:"How should success be measured?"},
  {id:"d87",level:"进阶",title:"讨论城市健康差异",scenario:"Speaking Part 3",prompt:"Why can health outcomes differ between wards in the same city?",model:"Housing density, air quality and access to care can vary greatly, so an average city result may hide severe conditions in a particular ward.",keywords:["density","vary","severe"],followUp:"Which policy could improve equity first?"},
  {id:"d88",level:"进阶",title:"讨论海外学习",scenario:"Speaking Part 3",prompt:"When does studying overseas produce genuine educational value?",model:"Overseas study has genuine value when learners engage with a distinct culture and develop independence, rather than treating the experience as an expensive holiday.",keywords:["overseas","genuine","distinct"],followUp:"Who may find studying abroad unsuitable?"},
];
