import type{SentenceChallenge}from"./sentence-challenges-base";import type{SpeakingDrill}from"./speaking-drills-base";
export const sentenceChallengeBatch13:SentenceChallenge[]=[
{id:"g137",title:"入读一门课程",level:"基础",principle:"enroll in",segments:[{text:"I",role:"主语"},{text:"enrolled in",role:"报名"},{text:"the course",role:"课程"}],prompt:"I enrolled ___ the evening course.",options:["in","at","for to"],correct:"in",explanation:"enroll in 表示报名参加课程。",errorHint:"课程前使用 in。",model:"I enrolled in the evening course."},
{id:"g138",title:"不论收入",level:"基础",principle:"irrespective of",segments:[{text:"Help",role:"主语"},{text:"is available",role:"状态"},{text:"irrespective of income",role:"让步"}],prompt:"Help is available irrespective ___ income.",options:["of","from","to"],correct:"of",explanation:"irrespective of 表示不论某因素。",errorHint:"固定介词为 of。",model:"Help is available irrespective of income."},
{id:"g139",title:"开始一个项目",level:"基础",principle:"embark on",segments:[{text:"They",role:"主语"},{text:"embarked on",role:"开始"},{text:"a project",role:"对象"}],prompt:"They embarked ___ a new project.",options:["on","to","with"],correct:"on",explanation:"embark on 表示着手开始。",errorHint:"开始事业或项目用 on。",model:"They embarked on a new project."},
{id:"g140",title:"擅长解释",level:"进阶",principle:"adept at",segments:[{text:"She",role:"主语"},{text:"is adept at",role:"擅长"},{text:"explaining rules",role:"行为"}],prompt:"She is adept ___ explaining rules.",options:["at","to","for"],correct:"at",explanation:"adept at 后接名词或动名词。",errorHint:"技能搭配使用 at。",model:"She is adept at explaining complex rules."},
{id:"g141",title:"妨碍某人做事",level:"进阶",principle:"inhibit A from doing",segments:[{text:"Fear",role:"主语"},{text:"may inhibit people",role:"妨碍"},{text:"from applying",role:"行为"}],prompt:"Fear may inhibit people ___ applying.",options:["from","to","with"],correct:"from",explanation:"inhibit someone from doing 表示阻止做某事。",errorHint:"doing 前使用 from。",model:"Fear may inhibit people from applying."},
{id:"g142",title:"恶化为冲突",level:"进阶",principle:"degenerate into",segments:[{text:"The dispute",role:"主语"},{text:"degenerated into",role:"恶化为"},{text:"conflict",role:"结果"}],prompt:"The dispute degenerated ___ conflict.",options:["into","at","from"],correct:"into",explanation:"degenerate into 表示恶化成另一状态。",errorHint:"变化结果用 into。",model:"The dispute degenerated into open conflict."},
{id:"g143",title:"对结果施加影响",level:"进阶",principle:"exert influence on",segments:[{text:"Costs",role:"主语"},{text:"exert influence",role:"施加影响"},{text:"on decisions",role:"对象"}],prompt:"Costs exert influence ___ decisions.",options:["on","with","for"],correct:"on",explanation:"exert influence on 表示对某事产生影响。",errorHint:"影响对象前使用 on。",model:"Costs exert influence on public decisions."},
{id:"g144",title:"援引合法权利",level:"进阶",principle:"invoke + 名词",segments:[{text:"The tenant",role:"主语"},{text:"may invoke",role:"援引"},{text:"a legal right",role:"对象"}],prompt:"The tenant may ___ a legal right.",options:["invoke","invokes","be invoke"],correct:"invoke",explanation:"may 后使用动词原形 invoke。",errorHint:"情态动词后不加 s。",model:"The tenant may invoke a legal right."}
];
export const speakingDrillBatch13:SpeakingDrill[]=[
{id:"d137",level:"基础",title:"报告家中霉菌",scenario:"联系房东",prompt:"Describe recurring mould and request an inspection.",model:"Black mould has returned behind the wardrobe, and I would like an urgent inspection because it is affecting my health.",keywords:["mould","dizzy","inspection"],followUp:"When did it return?"},
{id:"d138",level:"基础",title:"询问步道安全",scenario:"游客中心",prompt:"Ask whether recent rain has made a gorge route unsafe.",model:"Is the gorge route open, or has the recent torrent made the uphill section unsafe to traverse?",keywords:["gorge","torrent","traverse"],followUp:"Do you have waterproof footwear?"},
{id:"d139",level:"基础",title:"申诉工作评估",scenario:"人力资源部门",prompt:"Request evidence and an impartial review of an appraisal.",model:"I believe two ratings in my appraisal contradict the written evidence, so I would like an impartial review.",keywords:["appraisal","contradict","impartial"],followUp:"Which ratings do you dispute?"},
{id:"d140",level:"进阶",title:"描述克服逆境",scenario:"Speaking Part 2",prompt:"Describe how you overcame a daunting practical hurdle.",model:"The application seemed daunting, but I divided it into small tasks, sought pertinent advice and completed it within a fortnight.",keywords:["daunting","pertinent","fortnight"],followUp:"What did the experience teach you?"},
{id:"d141",level:"进阶",title:"评价自然式公园",scenario:"Speaking Part 3",prompt:"Explain how a park can balance ecology with public safety.",model:"Native planting can conserve water and reclaim barren land, while clear paths prevent vegetation from camouflaging hazards.",keywords:["conserve","reclaim","camouflage"],followUp:"Should every area look tidy?"},
{id:"d142",level:"进阶",title:"防范网络假票",scenario:"消费者建议",prompt:"Warn a friend about a deceptive ticket offer.",model:"The negligible price and abrupt payment request suggest a counterfeit offer, so verify the authorized seller before paying.",keywords:["negligible","counterfeit","authorize"],followUp:"Which evidence would you save?"},
{id:"d143",level:"进阶",title:"讨论公共信任",scenario:"Speaking Part 3",prompt:"Explain what makes consultation credible.",model:"Credible consultation uses audible and accessible language, enlists a multicultural public and shows how evidence changed the decision.",keywords:["audible","enlist","multicultural"],followUp:"Why is impartial review important?"},
{id:"d144",level:"进阶",title:"分析睡眠研究",scenario:"学术讨论",prompt:"Explain why a longitudinal design is preferable for sleep research.",model:"A longitudinal study can track insomnia and cognition over time, while a brief survey may capture only a transient pattern.",keywords:["longitudinal","insomnia","cognition"],followUp:"Which other factors should be recorded?"}
];
