import type { SentenceChallenge } from "./sentence-challenges-base";
import type { SpeakingDrill } from "./speaking-drills-base";

export const sentenceChallengeBatch04: SentenceChallenge[] = [
  {id:"g65",title:"符合某项资格",level:"基础",principle:"be eligible for + noun",segments:[{text:"Part-time staff",role:"主语"},{text:"are eligible for",role:"符合资格"},{text:"travel support",role:"福利"}],prompt:"Part-time staff are eligible ___ travel support.",options:["for","to","with"],correct:"for",explanation:"eligible for 后接可申请或享有的福利。",errorHint:"这里不是 eligible to do 的动词结构。",model:"Part-time staff are eligible for travel support."},
  {id:"g66",title:"遵守规则",level:"基础",principle:"comply with + rule",segments:[{text:"Contractors",role:"主语"},{text:"must comply with",role:"强制遵守"},{text:"the safety rules",role:"规则"}],prompt:"Contractors must comply ___ the safety rules.",options:["with","for","at"],correct:"with",explanation:"comply with regulations/rules 是固定搭配。",errorHint:"中文是“遵守”，英语动词后仍需要 with。",model:"Contractors must comply with the safety rules."},
  {id:"g67",title:"确保一件事发生",level:"基础",principle:"ensure that + clause",segments:[{text:"Please ensure",role:"提醒"},{text:"that every section",role:"从句主语"},{text:"is complete",role:"状态"}],prompt:"Please ensure ___ every section is complete.",options:["that","of","to"],correct:"that",explanation:"ensure that 后接完整句，表示确保某事实成立。",errorHint:"空格后已有主语 every section 和谓语 is。",model:"Please ensure that every section is complete."},
  {id:"g68",title:"必须被提交",level:"进阶",principle:"modal + be + past participle",segments:[{text:"The form",role:"承受动作的主语"},{text:"must be submitted",role:"被动要求"},{text:"by Friday",role:"截止时间"}],prompt:"The form must ___ by Friday.",options:["be submitted","submit","be submitting"],correct:"be submitted",explanation:"表格是“被提交”，must 后使用 be + 过去分词。",errorHint:"主语 the form 不能主动执行 submit。",model:"The form must be submitted by Friday."},
  {id:"g69",title:"建议某人做某事",level:"进阶",principle:"recommend that + base verb",segments:[{text:"Doctors recommend",role:"建议"},{text:"that patients take",role:"建议内容"},{text:"regular breaks",role:"对象"}],prompt:"Doctors recommend that patients ___ regular breaks.",options:["take","takes","to take"],correct:"take",explanation:"正式英语中 recommend that 后可用动词原形。",errorHint:"从句主语虽是复数，这里仍练 recommend that + 原形。",model:"Doctors recommend that patients take regular breaks."},
  {id:"g70",title:"等待批准的状态",level:"进阶",principle:"pending + noun",segments:[{text:"The payment",role:"主语"},{text:"remains pending",role:"待处理状态"},{text:"approval",role:"等待事项"}],prompt:"The payment remains pending ___.",options:["approval","approve","approved"],correct:"approval",explanation:"pending 在此后接名词 approval，表示“等待批准”。",errorHint:"需要的是事项名称，不是动词。",model:"The payment remains pending approval."},
  {id:"g71",title:"解释用途的关系从句",level:"进阶",principle:"noun + which + verb",segments:[{text:"Use the reference number",role:"行动"},{text:"which appears",role:"修饰编号"},{text:"on your receipt",role:"位置"}],prompt:"Use the reference number ___ appears on your receipt.",options:["which","where","what"],correct:"which",explanation:"which 指代前面的物 reference number，并在从句中作主语。",errorHint:"where 指地点；what 前面不再保留被修饰名词。",model:"Use the reference number which appears on your receipt."},
  {id:"g72",title:"表达唯一条件",level:"进阶",principle:"only if + clause",segments:[{text:"The deposit is returned",role:"结果"},{text:"only if",role:"必要条件"},{text:"the room is undamaged",role:"条件"}],prompt:"The deposit is returned ___ the room is undamaged.",options:["only if","even though","because of"],correct:"only if",explanation:"only if 表示“只有在……条件下才”。",errorHint:"后面是决定退还押金的必要条件。",model:"The deposit is returned only if the room is undamaged."},
];

export const speakingDrillBatch04: SpeakingDrill[] = [
  {id:"d65",level:"基础",title:"询问补贴资格",scenario:"致电市政服务中心",prompt:"Ask whether you are eligible for a heating subsidy.",model:"Could you tell me whether I am eligible for the heating subsidy and what proof of income I need?",keywords:["eligible","subsidy","proof"],followUp:"When would you like to submit the application?"},
  {id:"d66",level:"基础",title:"报告发票错误",scenario:"联系供应商财务部门",prompt:"Explain that an invoice includes an item you did not order.",model:"I am calling because the invoice includes an item that our office did not order, so could you issue a corrected copy?",keywords:["invoice","includes","corrected"],followUp:"What is the invoice number?"},
  {id:"d67",level:"基础",title:"申请停车许可",scenario:"在市政服务柜台",prompt:"Ask how to obtain a resident parking permit.",model:"I would like to obtain a resident parking permit. Could you explain which documents I must submit?",keywords:["obtain","permit","submit"],followUp:"Do you have proof of address?"},
  {id:"d68",level:"基础",title:"描述用药后的症状",scenario:"致电社区诊所",prompt:"Describe a symptom that began after a new medication.",model:"I started this medication yesterday, and since then I have had a headache and unusual fatigue.",keywords:["medication","symptom","fatigue"],followUp:"Have you had any difficulty breathing?"},
  {id:"d69",level:"进阶",title:"协商加班安排",scenario:"与经理讨论本周排班",prompt:"Explain why you cannot work overtime on Friday and offer a practical substitute.",model:"I cannot work overtime on Friday because of a medical appointment, but I could cover the same hours on Saturday morning.",keywords:["overtime","because","could"],followUp:"How would the change affect the rest of the team?"},
  {id:"d70",level:"进阶",title:"一次社区志愿经历",scenario:"Speaking Part 2",prompt:"Describe a community initiative in which you volunteered.",model:"I joined a river clean-up organised by the municipal council. Our collaboration removed litter and also raised public awareness of the local habitat.",keywords:["initiative","collaboration","awareness"],followUp:"What made the activity effective?"},
  {id:"d71",level:"进阶",title:"城市交通投资重点",scenario:"Speaking Part 3",prompt:"Which transport infrastructure should growing cities improve first?",model:"Cities should first improve reliable bus routes and safe intersections because these changes benefit many districts without requiring every resident to own a car.",keywords:["infrastructure","reliable","districts"],followUp:"How should a council evaluate the outcome?"},
  {id:"d72",level:"进阶",title:"公共健康责任",scenario:"Speaking Part 3",prompt:"How should governments and individuals share responsibility for preventing chronic illness?",model:"Governments can fund vaccination, accurate information and accessible care, while individuals remain responsible for using those services and making informed daily choices.",keywords:["preventing","fund","responsible"],followUp:"Which preventive service gives the greatest public benefit?"},
];
