import type { SentenceChallenge } from "./sentence-challenges-base";
import type { SpeakingDrill } from "./speaking-drills-base";

export const sentenceChallengeBatch03: SentenceChallenge[] = [
  {id:"g49",title:"让专业人员完成维修",level:"进阶",principle:"have + object + past participle",segments:[{text:"I",role:"主语"},{text:"had",role:"安排"},{text:"the window repaired",role:"物品＋完成动作"}],prompt:"I had the window ___ before winter.",options:["repair","repaired","repairing"],correct:"repaired",explanation:"have something done 表示安排别人完成某事，物品后用过去分词。",errorHint:"不是“我亲自修”，而是“我让人把窗户修好”。",model:"I had the window repaired before winter."},
  {id:"g50",title:"更喜欢一个选择",level:"进阶",principle:"prefer A to B",segments:[{text:"Many passengers",role:"主语"},{text:"prefer trains",role:"偏好"},{text:"to buses",role:"比较对象"}],prompt:"Many passengers prefer trains ___ buses.",options:["than","to","over than"],correct:"to",explanation:"prefer A to B 是固定结构，比较两个偏好对象。",errorHint:"不要套用比较级的 than。",model:"Many passengers prefer trains to buses."},
  {id:"g51",title:"说明完成方式",level:"进阶",principle:"by + -ing",segments:[{text:"We reduced costs",role:"结果"},{text:"by sharing",role:"方式"},{text:"one vehicle",role:"对象"}],prompt:"We reduced costs by ___ one vehicle.",options:["share","sharing","shared"],correct:"sharing",explanation:"介词 by 后用动名词，说明“通过什么方式”。",errorHint:"by 在这里是介词，后面的动作要加 -ing。",model:"We reduced costs by sharing one vehicle."},
  {id:"g52",title:"为了达到一个结果",level:"进阶",principle:"so that + clause",segments:[{text:"Leave early",role:"行动"},{text:"so that",role:"目的连接"},{text:"you can avoid traffic",role:"目的"}],prompt:"Leave early ___ you can avoid heavy traffic.",options:["so that","because of","despite"],correct:"so that",explanation:"so that 后接完整句，表达前面行动的目的。",errorHint:"空格后有主语 you 和谓语 can avoid。",model:"Leave early so that you can avoid heavy traffic."},
  {id:"g53",title:"两个动作同时发生",level:"进阶",principle:"while + -ing",segments:[{text:"Keep the receipt",role:"主要动作"},{text:"while waiting",role:"同时动作"},{text:"for the refund",role:"补充"}],prompt:"Keep the receipt while ___ for the refund.",options:["wait","waiting","waited"],correct:"waiting",explanation:"主从句主语相同时，while 后可省略主语和 be，保留 -ing。",errorHint:"完整形式是 while you are waiting。",model:"Keep the receipt while waiting for the refund."},
  {id:"g54",title:"过去本应做却没做",level:"进阶",principle:"should have + past participle",segments:[{text:"You",role:"主语"},{text:"should have checked",role:"过去建议"},{text:"the terms",role:"对象"}],prompt:"You should have ___ the terms before paying.",options:["check","checked","checking"],correct:"checked",explanation:"should have + 过去分词用来评价过去本应完成的动作。",errorHint:"have 后不是原形，而是过去分词。",model:"You should have checked the terms before paying."},
  {id:"g55",title:"想象没有发生的过去",level:"进阶",principle:"third conditional",segments:[{text:"If we had booked earlier",role:"过去虚拟条件"},{text:"we would have paid",role:"过去虚拟结果"},{text:"less",role:"结果补充"}],prompt:"If we had booked earlier, we ___ less.",options:["would pay","would have paid","had paid"],correct:"would have paid",explanation:"过去事实相反的条件句：If + had done，结果用 would have done。",errorHint:"两边都谈已经错过的过去。",model:"If we had booked earlier, we would have paid less."},
  {id:"g56",title:"希望现在不同",level:"进阶",principle:"wish + past simple",segments:[{text:"I wish",role:"愿望"},{text:"the bus came",role:"与现在相反"},{text:"more often",role:"频率"}],prompt:"I wish the bus ___ more often.",options:["comes","came","has come"],correct:"came",explanation:"wish 表达与现在事实不同的愿望时，后接一般过去时。",errorHint:"形式是过去时，意思仍然指现在。",model:"I wish the bus came more often."},
  {id:"g57",title:"尽管后接完整事实",level:"进阶",principle:"despite the fact that",segments:[{text:"Despite the fact that",role:"让步连接"},{text:"the fee increased",role:"完整事实"},{text:"demand remained high",role:"主结论"}],prompt:"___ the fee increased, demand remained high.",options:["Despite the fact that","Despite","Because of"],correct:"Despite the fact that",explanation:"后面是完整句 the fee increased，despite 需加 the fact that 才能连接。",errorHint:"单独 despite 后应接名词，不直接接完整句。",model:"Despite the fact that the fee increased, demand remained high."},
  {id:"g58",title:"无论两个选择哪个",level:"进阶",principle:"whether ... or",segments:[{text:"Tell us",role:"主句"},{text:"whether you prefer morning",role:"选择一"},{text:"or afternoon",role:"选择二"}],prompt:"Tell us ___ you prefer morning or afternoon.",options:["whether","despite","unless"],correct:"whether",explanation:"whether ... or 引出两个可能选择，常用于间接问题。",errorHint:"句子不是说明条件，而是在确认两个选项。",model:"Tell us whether you prefer morning or afternoon."},
  {id:"g59",title:"多个之中的一个",level:"进阶",principle:"one of the + plural noun",segments:[{text:"This is",role:"主干"},{text:"one of the busiest",role:"范围中的一个"},{text:"routes",role:"复数集合"}],prompt:"This is one of the busiest ___ in the city.",options:["route","routes","routing"],correct:"routes",explanation:"one of the 后面指一个集合，因此名词用复数。",errorHint:"虽然主语是“一个”，但它来自“多条路线”。",model:"This is one of the busiest routes in the city."},
  {id:"g60",title:"表示已经出现变化",level:"进阶",principle:"there has been",segments:[{text:"There has been",role:"存在变化"},{text:"a clear improvement",role:"单数对象"},{text:"in service",role:"范围"}],prompt:"There ___ a clear improvement in service.",options:["has been","have been","was being"],correct:"has been",explanation:"后面的核心名词 improvement 是单数，因此用 there has been。",errorHint:"判断 be 的形式要看后面的名词。",model:"There has been a clear improvement in service."},
  {id:"g61",title:"与另一对象相比",level:"进阶",principle:"compared with",segments:[{text:"Compared with last year",role:"比较基准"},{text:"complaints",role:"主语"},{text:"fell",role:"变化"}],prompt:"___ last year, complaints fell by ten per cent.",options:["Compared with","Comparing","Compare to"],correct:"Compared with",explanation:"compared with 放句首表示“与……相比”，逻辑上是被比较。",errorHint:"后面主句主语是 complaints，不是执行 compare 的人。",model:"Compared with last year, complaints fell by ten per cent."},
  {id:"g62",title:"名词形式表达原因",level:"进阶",principle:"as a result of + noun",segments:[{text:"The event moved indoors",role:"结果"},{text:"as a result of",role:"原因连接"},{text:"heavy rain",role:"名词原因"}],prompt:"The event moved indoors as a result ___ heavy rain.",options:["of","from","that"],correct:"of",explanation:"as a result of 后接名词或名词短语，表示原因。",errorHint:"这里不是 as a result, that... 的句子结构。",model:"The event moved indoors as a result of heavy rain."},
  {id:"g63",title:"数量这个数字作主语",level:"进阶",principle:"the number of + singular verb",segments:[{text:"The number of visitors",role:"单数主语概念"},{text:"has increased",role:"单数谓语"},{text:"this month",role:"时间"}],prompt:"The number of visitors ___ increased this month.",options:["has","have","are"],correct:"has",explanation:"the number of 强调“这个数量”，整体按单数处理。",errorHint:"不要被紧邻的复数 visitors 误导。",model:"The number of visitors has increased this month."},
  {id:"g64",title:"有一些人或物",level:"进阶",principle:"a number of + plural verb",segments:[{text:"A number of residents",role:"复数主语"},{text:"have requested",role:"复数谓语"},{text:"a crossing",role:"对象"}],prompt:"A number of residents ___ requested a new crossing.",options:["has","have","is"],correct:"have",explanation:"a number of 表示“一些”，后接复数名词并使用复数谓语。",errorHint:"对比 the number of；这里强调多人提出请求。",model:"A number of residents have requested a new crossing."},
];

export const speakingDrillBatch03: SpeakingDrill[] = [
  {id:"d49",level:"基础",title:"确认仓储门禁时间",scenario:"致电自助仓储公司",prompt:"Ask when you can enter your storage unit.",model:"Could you confirm what time I can access my storage unit each day?",keywords:["confirm","access","each day"],followUp:"Do you need access at weekends?"},
  {id:"d50",level:"基础",title:"说明宠物接种后的反应",scenario:"致电兽医诊所",prompt:"Explain that your dog is unusually tired after vaccination.",model:"My dog had a vaccination yesterday and has been unusually tired since this morning.",keywords:["vaccination","tired","since"],followUp:"Is the dog eating and breathing normally?"},
  {id:"d51",level:"基础",title:"请求无障碍投票帮助",scenario:"在投票站服务台",prompt:"Ask what assistance is available in the voting booth.",model:"Could you tell me what assistance is available for someone who has difficulty holding a pencil?",keywords:["assistance","available","difficulty"],followUp:"Would a pencil grip or a companion be more helpful?"},
  {id:"d52",level:"基础",title:"报告工作场所噪声",scenario:"向主管报告设备问题",prompt:"Report that one machine has become much louder than usual.",model:"The packing machine has become much louder than usual, so I think it should be checked before we continue.",keywords:["louder","checked","before"],followUp:"When did you first notice the change?"},
  {id:"d53",level:"进阶",title:"一次有效的培训",scenario:"Speaking Part 2",prompt:"Describe a training session that taught you something useful.",model:"A workplace first-aid session taught me how to respond calmly to common emergencies. We practised each step in pairs, so I remembered far more than I would have from reading alone.",keywords:["taught","practised","so"],followUp:"How did you use the skill afterward?"},
  {id:"d54",level:"进阶",title:"改变看法的一次交谈",scenario:"Speaking Part 2",prompt:"Describe a conversation that changed your opinion.",model:"I spoke with a neighbour about the new traffic restrictions. I had expected them to be inconvenient, but her experience showed me how much safer the school entrance had become.",keywords:["expected","but","showed"],followUp:"Why was the other person's view convincing?"},
  {id:"d55",level:"进阶",title:"长期保存的实用物品",scenario:"Speaking Part 2",prompt:"Describe a useful object that you have kept for many years.",model:"I have kept a small tool kit that a colleague gave me when I moved home. The case looks old now, but the tools still help me complete simple repairs instead of replacing things.",keywords:["kept","but","instead of"],followUp:"Would you replace the object if it broke?"},
  {id:"d56",level:"进阶",title:"参加志愿活动的一天",scenario:"Speaking Part 2",prompt:"Describe a day when you volunteered in your community.",model:"I joined a park clean-up near the lake. Our group collected ordinary litter and marked dangerous glass for the supervisor, which made the work both useful and safely organised.",keywords:["joined","collected","which"],followUp:"What encouraged you to participate?"},
  {id:"d57",level:"进阶",title:"一次顺利解决的投诉",scenario:"Speaking Part 2",prompt:"Describe a complaint that was handled well.",model:"A delivered shelf arrived with a damaged panel. The adviser listened, checked my photograph and arranged a replacement part within two days, so I did not need to return the whole package.",keywords:["arrived","arranged","so"],followUp:"What makes an apology from a company believable?"},
  {id:"d58",level:"进阶",title:"尝试过的环保改变",scenario:"Speaking Part 2",prompt:"Describe a change you made to reduce waste or energy use.",model:"I began planning meals before shopping because unused food was often thrown away. The habit took only a few minutes, yet it reduced both waste and weekly spending.",keywords:["began","because","yet"],followUp:"Was the change easy to maintain?"},
  {id:"d59",level:"进阶",title:"线下服务是否仍然必要",scenario:"Speaking Part 3",prompt:"Why should some organisations keep face-to-face services?",model:"Digital systems are efficient for routine tasks, whereas complex or sensitive problems may require conversation, accessibility support and a person who can take responsibility.",keywords:["whereas","may","responsibility"],followUp:"Which services can safely become fully digital?"},
  {id:"d60",level:"进阶",title:"城市如何管理夜间活动",scenario:"Speaking Part 3",prompt:"How can cities support nightlife without harming residents?",model:"Cities can set clear delivery and noise rules, provide safe late transport and review evidence by location, instead of treating every evening business as the same problem.",keywords:["can","and","instead of"],followUp:"Should closing times differ between neighbourhoods?"},
  {id:"d61",level:"进阶",title:"学校周边限制车辆",scenario:"Speaking Part 3",prompt:"Are temporary traffic restrictions near schools a good idea?",model:"They can create safer space for walking, but authorities must check whether traffic moves to nearby streets and provide realistic options for families travelling farther.",keywords:["can","but","whether"],followUp:"How should success be measured?"},
  {id:"d62",level:"进阶",title:"购买本地食品的取舍",scenario:"Speaking Part 3",prompt:"Should consumers try to buy more locally produced food?",model:"Local food can support nearby businesses and shorten some journeys; however, imported products provide choice and may be produced more efficiently in a suitable climate.",keywords:["can","however","may"],followUp:"What information should food labels show?"},
  {id:"d63",level:"进阶",title:"谁负责更新工作技能",scenario:"Speaking Part 3",prompt:"Who should pay for workers to update their skills?",model:"Employers should fund training required for a current role, while individuals and governments may share the cost of broader education that improves long-term mobility.",keywords:["should","while","may"],followUp:"Should training happen during paid hours?"},
  {id:"d64",level:"进阶",title:"社区能源的公平性",scenario:"Speaking Part 3",prompt:"How can local energy projects benefit more residents?",model:"Projects can offer low-cost membership, invest part of their income in home efficiency and publish clear evidence showing which households actually receive savings.",keywords:["can","and","showing"],followUp:"Should local residents have voting rights in such projects?"},
];
