import type { SentenceChallenge } from "./sentence-challenges-base";
import type { SpeakingDrill } from "./speaking-drills-base";

export const sentenceChallengeBatch05: SentenceChallenge[] = [
  {id:"g73",title:"规则中的强制要求",level:"基础",principle:"must + 动词原形",segments:[{text:"All visitors",role:"主语"},{text:"must show",role:"强制要求"},{text:"identification",role:"宾语"}],prompt:"All visitors must ___ identification.",options:["show","showed","showing"],correct:"show",explanation:"情态动词 must 后面直接接动词原形。",errorHint:"不要在 must 后使用过去式或 -ing 形式。",model:"All visitors must show identification at the entrance."},
  {id:"g74",title:"说明判断依据",level:"基础",principle:"be based on + 名词",segments:[{text:"The decision",role:"主语"},{text:"is based on",role:"依据关系"},{text:"written evidence",role:"依据"}],prompt:"The decision is based ___ written evidence.",options:["on","at","for"],correct:"on",explanation:"be based on 表示“以……为依据”。",errorHint:"based 后表示依据时固定使用 on。",model:"The decision is based on written evidence."},
  {id:"g75",title:"表达不利条件下仍发生",level:"进阶",principle:"despite + 名词",segments:[{text:"Despite",role:"让步连接"},{text:"the severe rain",role:"名词短语"},{text:"the bus arrived",role:"主句"}],prompt:"___ the severe rain, the bus arrived on time.",options:["Despite","Although","Because"],correct:"Despite",explanation:"despite 后接名词短语；although 后必须接完整从句。",errorHint:"空格后是 the severe rain，不是主语加谓语。",model:"Despite the severe rain, the bus arrived on time."},
  {id:"g76",title:"表达前提条件",level:"进阶",principle:"provided that + 从句",segments:[{text:"You may change the booking",role:"结果"},{text:"provided that",role:"条件连接"},{text:"you give notice",role:"条件"}],prompt:"You may change the booking ___ you give notice.",options:["provided that","despite","besides"],correct:"provided that",explanation:"provided that 相当于“只要／如果”，引出必要条件。",errorHint:"后半句是允许改期的条件，不是让步或补充。",model:"You may change the booking provided that you give notice."},
  {id:"g77",title:"说明动作产生后果",level:"进阶",principle:"lead to + 名词",segments:[{text:"Poor lighting",role:"原因"},{text:"can lead to",role:"因果连接"},{text:"accidents",role:"结果"}],prompt:"Poor lighting can lead ___ accidents.",options:["to","with","from"],correct:"to",explanation:"lead to 表示“导致”，to 后接名词或动名词。",errorHint:"不要受中文“导致于”影响改变固定介词。",model:"Poor lighting can lead to accidents near the rear entrance."},
  {id:"g78",title:"从两项中指后者",level:"进阶",principle:"the latter + 单数动词",segments:[{text:"The latter route",role:"后者"},{text:"is",role:"系动词"},{text:"cheaper",role:"比较结果"}],prompt:"Of the two routes, the latter ___ cheaper.",options:["is","are","be"],correct:"is",explanation:"the latter 指前面两项中的后者，这里 route 是单数。",errorHint:"不要因为前面出现 two routes 就使用复数谓语。",model:"Of the two routes, the latter is cheaper but slower."},
  {id:"g79",title:"表达支持某个方案",level:"进阶",principle:"in favor of + 名词",segments:[{text:"Most residents",role:"主语"},{text:"are in favor of",role:"支持立场"},{text:"the crossing",role:"方案"}],prompt:"Most residents are in favor ___ the new crossing.",options:["of","to","with"],correct:"of",explanation:"in favor of 是“支持／赞成”的固定搭配。",errorHint:"favor 前已有 in，后面仍需要 of 引出对象。",model:"Most residents are in favor of the new crossing."},
  {id:"g80",title:"过去开始并持续增长",level:"进阶",principle:"has grown since + 过去时间",segments:[{text:"Demand",role:"主语"},{text:"has grown",role:"现在完成时"},{text:"since the trial began",role:"起点"}],prompt:"Demand ___ since the trial began.",options:["has grown","grew yesterday","is grow"],correct:"has grown",explanation:"since 引出过去起点，主句常用现在完成时表示持续到现在。",errorHint:"注意 grown 是 grow 的过去分词，前面需要 has。",model:"Demand for flexible work has grown since the trial began."},
];

export const speakingDrillBatch05: SpeakingDrill[] = [
  {id:"d73",level:"基础",title:"确认服务柜台位置",scenario:"在大型车站问工作人员",prompt:"Ask where you can collect a replacement travel card.",model:"Could you tell me which counter I should go to in order to collect my replacement travel card?",keywords:["counter","collect","replacement"],followUp:"Do you have the case reference with you?"},
  {id:"d74",level:"基础",title:"报告租住房屋故障",scenario:"给物业维修部门打电话",prompt:"Report a strange noise and a fault in the heating system.",model:"The boiler made a weird noise last night, and now the heating system appears to have a fault.",keywords:["weird","fault","heating"],followUp:"Is there any smell of gas?"},
  {id:"d75",level:"基础",title:"请求调整工作轮班",scenario:"与主管讨论排班",prompt:"Ask to exchange your Friday night shift and give a reason.",model:"Could I exchange my Friday night shift with a colleague because I have a medical appointment?",keywords:["exchange","shift","because"],followUp:"Which colleague has agreed to cover it?"},
  {id:"d76",level:"进阶",title:"说明诈骗经过",scenario:"向银行安全团队报告",prompt:"Explain why you suspect a payment message was fake.",model:"I suspect the message was fake because it requested my password and used a link that was not on the bank's official website.",keywords:["suspect","fake","official"],followUp:"Did you share any code or make a payment?"},
  {id:"d77",level:"进阶",title:"描述一次现场活动",scenario:"Speaking Part 2",prompt:"Describe a festival or public event that you attended.",model:"I attended a local arts festival beside the river. The live performances drew a large crowd, but the volunteer crew kept the entrances calm and well organised.",keywords:["festival","drew","crowd"],followUp:"Would you attend the event again?"},
  {id:"d78",level:"进阶",title:"评价远程办公",scenario:"Speaking Part 3",prompt:"Do the benefits of working from home outweigh the disadvantages?",model:"For many office workers the flexibility is valuable, provided that employers prevent isolation and judge performance by fair results rather than constant online activity.",keywords:["valuable","provided that","fair"],followUp:"Which workers cannot gain the same benefit?"},
  {id:"d79",level:"进阶",title:"讨论大型活动公共投入",scenario:"Speaking Part 3",prompt:"Should councils use public revenue to support large festivals?",model:"Limited support can be justified when an event creates local revenue and access to the arts, but the decision must also consider safety costs and residents' views.",keywords:["revenue","arts","consider"],followUp:"How could the council measure the outcome?"},
  {id:"d80",level:"进阶",title:"讨论海岸环境保护",scenario:"Speaking Part 3",prompt:"How can popular coastal areas protect marine life while accepting visitors?",model:"Authorities can guide the flow of visitors with marked paths and viewing platforms, then use independent monitoring to check whether damage actually falls.",keywords:["marine","flow","independent"],followUp:"When might a complete closure be necessary?"},
];
