import type{SentenceChallenge}from"./sentence-challenges-base";import type{SpeakingDrill}from"./speaking-drills-base";
export const sentenceChallengeBatch12:SentenceChallenge[]=[
 {id:"g129",title:"从某事获得益处",level:"基础",principle:"derive A from B",segments:[{text:"Residents",role:"主语"},{text:"derive benefit",role:"获得益处"},{text:"from the garden",role:"来源"}],prompt:"Residents derive benefit ___ the garden.",options:["from","to","with"],correct:"from",explanation:"derive A from B 表示从 B 获得 A。",errorHint:"来源使用 from。",model:"Residents derive benefit from the garden."},
 {id:"g130",title:"符合安全标准",level:"基础",principle:"conform to",segments:[{text:"The work",role:"主语"},{text:"must conform to",role:"符合"},{text:"the standard",role:"标准"}],prompt:"The work must conform ___ the standard.",options:["to","at","for"],correct:"to",explanation:"conform to 表示符合标准。",errorHint:"固定介词为 to。",model:"The work must conform to the standard."},
 {id:"g131",title:"使资金面临危险",level:"基础",principle:"put A in jeopardy",segments:[{text:"Delay",role:"主语"},{text:"may put funding",role:"置于"},{text:"in jeopardy",role:"危险"}],prompt:"Delay may put funding ___ jeopardy.",options:["in","on","at"],correct:"in",explanation:"put something in jeopardy 表示使其面临危险。",errorHint:"固定短语使用 in。",model:"Delay may put funding in jeopardy."},
 {id:"g132",title:"致力于一项任务",level:"进阶",principle:"devote A to B",segments:[{text:"The charity",role:"主语"},{text:"devotes funds",role:"投入资源"},{text:"to housing",role:"目标"}],prompt:"The charity devotes funds ___ housing.",options:["to","for being","onto"],correct:"to",explanation:"devote A to B 表示把 A 投入 B。",errorHint:"to 在这里是介词。",model:"The charity devotes funds to housing."},
 {id:"g133",title:"同时发生",level:"进阶",principle:"coincide with",segments:[{text:"The closure",role:"主语"},{text:"will coincide with",role:"同时发生"},{text:"the festival",role:"事件"}],prompt:"The closure will coincide ___ the festival.",options:["with","to","from"],correct:"with",explanation:"coincide with 表示与某事同时发生。",errorHint:"固定介词是 with。",model:"The closure will coincide with the festival."},
 {id:"g134",title:"缓解服务压力",level:"进阶",principle:"alleviate + 名词",segments:[{text:"Extra buses",role:"主语"},{text:"may alleviate",role:"缓解"},{text:"pressure",role:"对象"}],prompt:"Extra buses may ___ pressure.",options:["alleviate","alleviates","be alleviating to"],correct:"alleviate",explanation:"may 后接动词原形 alleviate。",errorHint:"情态动词后不加 s。",model:"Extra buses may alleviate pressure."},
 {id:"g135",title:"承认一个观点",level:"进阶",principle:"concede that + 从句",segments:[{text:"The operator",role:"主语"},{text:"conceded that",role:"承认"},{text:"the plan was unrealistic",role:"内容"}],prompt:"The operator conceded ___ the plan was unrealistic.",options:["that","about","to be that"],correct:"that",explanation:"concede that 后接完整从句。",errorHint:"这里用连接词 that。",model:"The operator conceded that the plan was unrealistic."},
 {id:"g136",title:"调和两种需求",level:"进阶",principle:"reconcile A with B",segments:[{text:"The plan",role:"主语"},{text:"reconciles heritage",role:"第一需求"},{text:"with safety",role:"第二需求"}],prompt:"The plan reconciles heritage ___ safety.",options:["with","against to","from"],correct:"with",explanation:"reconcile A with B 表示调和两者。",errorHint:"搭配使用 with。",model:"The plan reconciles heritage with safety."},
];
export const speakingDrillBatch12:SpeakingDrill[]=[
 {id:"d129",level:"基础",title:"申请紧急旅行证",scenario:"联系领事馆",prompt:"Explain that your passport was stolen and request an urgent appointment.",model:"My passport was stolen, my departure is imminent, and I would like to apply for an emergency travel document.",keywords:["consulate","imminent","expire"],followUp:"Do you have a police report?"},
 {id:"d130",level:"基础",title:"说明食物过敏",scenario:"酒店自助餐",prompt:"Ask whether a buffet dish contains almond or rye.",model:"Could you check the ingredient record and confirm whether this buffet dish contains almond, rye or another allergen?",keywords:["buffet","almond","rye"],followUp:"Do you need the first-aider?"},
 {id:"d131",level:"基础",title:"请求医疗口译",scenario:"诊所接待处",prompt:"Request a bilingual interpreter for a medical appointment.",model:"I can speak some English, but I need a trained bilingual interpreter to comprehend the diagnosis and consent form accurately.",keywords:["bilingual","interpreter","comprehend"],followUp:"Which dialect do you prefer?"},
 {id:"d132",level:"进阶",title:"描述暴风雪撤离",scenario:"Speaking Part 2",prompt:"Describe an emergency evacuation during severe weather.",model:"An impending blizzard triggered a landslide warning, so our team evacuated residents and used a diversion around the blocked road.",keywords:["blizzard","landslide","evacuate"],followUp:"How did people receive warnings?"},
 {id:"d133",level:"进阶",title:"讨论口译公平",scenario:"Speaking Part 3",prompt:"Explain why professional interpreting can be invaluable in healthcare.",model:"Professional interpreters reproduce meaning with fidelity, protect confidentiality and prevent a literal misunderstanding from placing consent in jeopardy.",keywords:["invaluable","fidelity","jeopardy"],followUp:"When can technology assist?"},
 {id:"d134",level:"进阶",title:"评估灾后重建",scenario:"Speaking Part 3",prompt:"Explain how reconstruction should balance heritage and safety.",model:"A pragmatic blueprint should preserve intrinsic cultural value while modifying structures to mitigate future catastrophe.",keywords:["blueprint","intrinsic","mitigate"],followUp:"Who should scrutinise costs?"},
 {id:"d135",level:"进阶",title:"讨论山区韧性",scenario:"Speaking Part 3",prompt:"Describe how a remote community can prepare for cascading hazards.",model:"It can equip bilingual liaison workers, rehearse evacuation, consolidate supplies and acknowledge that forecasts have limitations.",keywords:["equip","liaison","consolidate"],followUp:"What makes a warning effective?"},
 {id:"d136",level:"进阶",title:"分析企业透明度",scenario:"公共听证会",prompt:"Challenge a company that conceals the implications of its proposal.",model:"The company should articulate every financial implication, concede uncertainty and stop using glamour to conceal tangible risks.",keywords:["articulate","implication","conceal"],followUp:"Which evidence should it publish?"},
];
