export type ReadingKind = "functional" | "continuous";
export type ReadingQuestion = {id:string;passageId:string;kind:ReadingKind;level:number;difficulty:number;discrimination:number;prompt:string;options:string[];answer:string;explanation:string};
export type ReadingPassage = {id:string;kind:ReadingKind;level:number;title:string;category:string;text:string;questions:ReadingQuestion[];contentStatus:"reviewed-original";scoringEligible:true;version:"reading-bank-110-v1"};

type FunctionalBase={title:string;category:string;purpose:string;place:string;requirement:string;exception:string;contact:string;consequence:string};
const functionalBases:FunctionalBase[]=[
{title:"Library room booking",category:"community",purpose:"reserve a quiet study room",place:"the second-floor help desk",requirement:"show a library card on arrival",exception:"carers may enter without a separate booking",contact:"the library booking team",consequence:"the room is released after fifteen minutes"},
{title:"Clinic appointment change",category:"health",purpose:"change a routine clinic appointment",place:"the outpatient reception desk",requirement:"quote the patient reference number",exception:"urgent symptoms must be reported by telephone",contact:"the clinic scheduling team",consequence:"a second missed visit requires a new referral"},
{title:"Bus diversion notice",category:"transport",purpose:"explain a temporary bus diversion",place:"the stop outside Central Market",requirement:"use the replacement stop on King Street",exception:"wheelchair users can request an accessible shuttle",contact:"the passenger information line",consequence:"journeys may take twenty minutes longer"},
{title:"Recycling collection change",category:"housing",purpose:"announce a revised recycling collection",place:"the neighbourhood collection point",requirement:"separate glass from paper and cardboard",exception:"large electrical items require a separate request",contact:"the council waste service",consequence:"contaminated containers will be left unemptied"},
{title:"Workplace safety refresher",category:"work",purpose:"book compulsory safety refresher training",place:"Training Room B",requirement:"complete the online preparation module",exception:"staff on certified leave may attend the next session",contact:"the health and safety coordinator",consequence:"site access is suspended until training is complete"},
{title:"Staff expense claim",category:"work",purpose:"submit a staff travel expense claim",place:"the Finance self-service portal",requirement:"attach an itemised receipt",exception:"a lost receipt may be replaced by a signed declaration",contact:"the expenses support desk",consequence:"late claims may be refused"},
{title:"Community hall hire",category:"community",purpose:"confirm a community hall reservation",place:"Riverside Community Hall",requirement:"pay the refundable security deposit",exception:"registered charities receive a reduced deposit",contact:"the hall bookings officer",consequence:"the reservation is cancelled if payment is late"},
{title:"Ferry ticket amendment",category:"transport",purpose:"amend a vehicle ferry booking",place:"the harbour ticket office",requirement:"provide the booking code and vehicle plate",exception:"weather cancellations can be changed without a fee",contact:"the ferry reservations desk",consequence:"same-day changes lose the original fare"},
{title:"Cold-weather shelter",category:"community",purpose:"give instructions for an overnight shelter",place:"the Civic Hall side entrance",requirement:"bring essential medication and one small bag",exception:"assistance dogs are permitted in the sleeping area",contact:"the emergency housing line",consequence:"unattended belongings may be removed"},
{title:"Pharmacy delivery service",category:"health",purpose:"arrange delivery of repeat medicine",place:"the neighbourhood pharmacy",requirement:"order before the daily cut-off",exception:"controlled medicine must be collected in person",contact:"the pharmacy delivery desk",consequence:"failed deliveries return to the pharmacy"},
{title:"Childcare registration",category:"family",purpose:"register a child for an after-school club",place:"the primary school office",requirement:"provide two emergency contacts",exception:"children with medical needs may submit an additional care plan",contact:"the club administrator",consequence:"incomplete forms cannot secure a place"},
{title:"Fitness membership pause",category:"health",purpose:"pause a fitness centre membership",place:"the membership counter",requirement:"submit evidence for pauses longer than one month",exception:"annual maintenance closures do not use pause allowance",contact:"the membership services team",consequence:"fees continue until the request is approved"},
{title:"Rental property inspection",category:"housing",purpose:"prepare tenants for a routine inspection",place:"the rented property",requirement:"ensure every room can be entered safely",exception:"tenants may request a different time for religious observance",contact:"the property management office",consequence:"an obstructed inspection must be rearranged"},
{title:"Festival volunteer shift",category:"community",purpose:"confirm a festival volunteer shift",place:"the north entrance welcome tent",requirement:"attend the safety briefing before work",exception:"volunteers under eighteen must work with an adult",contact:"the volunteer coordinator",consequence:"late arrivals may be moved to another role"},
{title:"Language exam check-in",category:"education",purpose:"explain check-in for a language examination",place:"the college sports hall",requirement:"bring approved photographic identification",exception:"religious head coverings may remain in place during identity checks",contact:"the examinations office",consequence:"candidates arriving after check-in closes cannot enter"},
{title:"Parcel collection",category:"services",purpose:"collect a parcel from a service locker",place:"the station concourse lockers",requirement:"enter the six-digit collection code",exception:"oversized parcels are held at the staffed counter",contact:"the parcel support team",consequence:"uncollected parcels are returned after seven days"},
{title:"Resident parking permit",category:"housing",purpose:"renew a resident parking permit",place:"the council permit portal",requirement:"upload current address evidence",exception:"blue-badge holders do not pay the administration fee",contact:"the parking permits team",consequence:"an expired permit may result in a penalty notice"},
{title:"Pet vaccination visit",category:"health",purpose:"prepare for a pet vaccination visit",place:"Green Lane Veterinary Clinic",requirement:"bring the vaccination record",exception:"animals with breathing difficulty should be taken directly to emergency care",contact:"the veterinary reception team",consequence:"late arrivals may need a new appointment"},
{title:"Repair workshop booking",category:"community",purpose:"book a place at a household repair workshop",place:"the Makers Centre",requirement:"describe the item and fault in advance",exception:"microwave ovens and gas appliances are not accepted",contact:"the workshop organiser",consequence:"unconfirmed places are offered to the waiting list"},
{title:"Museum evening event",category:"culture",purpose:"explain entry to a museum evening event",place:"the museum east entrance",requirement:"show the digital ticket at security",exception:"personal assistants enter without an additional ticket",contact:"the visitor services desk",consequence:"re-entry is not allowed after leaving the building"},
];
const deadlines=[["5 p.m. on Monday","noon on Wednesday","4 p.m. on Friday"],["10 a.m. on 6 September","2 p.m. on 14 October","11 a.m. on 22 November"],["three working days before the visit","two working days before the visit","by the previous working day"],["seven days before the booking","fourteen days before the booking","forty-eight hours before the booking"]];
const functionalTemplates=[
(b:FunctionalBase,d:string)=>`${b.title.toUpperCase()}\nThis notice explains how to ${b.purpose}. Requests must be completed by ${d}. Go to ${b.place} and ${b.requirement}. ${b.exception}. For help, contact ${b.contact}. If the stated procedure is not followed, ${b.consequence}.`,
(b:FunctionalBase,d:string)=>`${b.title.toUpperCase()}\nAnyone who needs to ${b.purpose} should act by ${d}. The service is handled at ${b.place}. Before attending, remember to ${b.requirement}. Please note that ${b.exception}. Questions should be directed to ${b.contact}. Otherwise, ${b.consequence}.`,
(b:FunctionalBase,d:string)=>`${b.title.toUpperCase()}\nLocation: ${b.place}. Deadline: ${d}. The arrangement is intended to ${b.purpose}. Users must ${b.requirement}; however, ${b.exception}. Contact ${b.contact} if the instructions are unclear. Failure to meet the conditions means that ${b.consequence}.`,
(b:FunctionalBase,d:string)=>`${b.title.toUpperCase()}\nTo ${b.purpose}, apply no later than ${d}. Attend ${b.place} and be ready to ${b.requirement}. An exception applies because ${b.exception}. ${b.contact} can answer questions before the deadline. After that point, ${b.consequence}.`,
(b:FunctionalBase,d:string)=>`${b.title.toUpperCase()}\nThe following procedure applies at ${b.place}. It allows users to ${b.purpose}, provided they ${b.requirement} by ${d}. Remember that ${b.exception}. Seek advice from ${b.contact} rather than guessing. When the procedure is ignored, ${b.consequence}.`,
(b:FunctionalBase,d:string)=>`${b.title.toUpperCase()}\nPlease read before trying to ${b.purpose}. The relevant location is ${b.place}, and the final time for action is ${d}. You are expected to ${b.requirement}. Nevertheless, ${b.exception}. Contact ${b.contact} with any accessibility or procedural question. If no action is taken, ${b.consequence}.`,
];
const thetaByLevel=[-2.35,-1.45,-.55,.35,1.25,2.15];
const rotate=<T,>(values:T[],amount:number)=>values.map((_,index)=>values[(index+amount)%values.length]);
const makeQuestion=(passageId:string,kind:ReadingKind,level:number,index:number,prompt:string,answer:string,distractors:string[],explanation:string):ReadingQuestion=>({id:`${passageId}-q${index+1}`,passageId,kind,level,difficulty:Number((thetaByLevel[level-1]+(index-2.5)*.07).toFixed(2)),discrimination:Number((.92+level*.045+(index%2)*.06).toFixed(2)),prompt,options:rotate([answer,...distractors],index%3),answer,explanation});
function buildFunctional():ReadingPassage[]{return Array.from({length:60},(_,index)=>{const base=functionalBases[index%20];const variant=Math.floor(index/20);const id=`rf-${String(index+1).padStart(3,"0")}`;const level=1+Math.floor(index/15);const deadline=deadlines[index%4][variant];const title=`${base.title} ${["instructions","update","reminder"][variant]}`;const questions=[makeQuestion(id,"functional",level,0,`What is the main purpose of “${title}”?`,base.purpose,["advertise permanent employment","publish an annual performance report"],"开头明确说明了通知要帮助读者完成的事项。"),makeQuestion(id,"functional",level,1,"When must the reader act?",deadline,[deadlines[(index+1)%4][variant],deadlines[(index+2)%4][variant]],"通知中的时间句直接给出答案。"),makeQuestion(id,"functional",level,2,"What must the reader do?",base.requirement,[functionalBases[(index+3)%20].requirement,functionalBases[(index+7)%20].requirement],"must、required 或 expected 后面的内容是必要条件。"),makeQuestion(id,"functional",level,3,"Which exception is stated?",base.exception,[functionalBases[(index+5)%20].exception,"no exception is available in any situation"],"however 或 exception 引出的句子说明例外。"),makeQuestion(id,"functional",level,4,"Who should be contacted for help?",base.contact,[functionalBases[(index+2)%20].contact,functionalBases[(index+11)%20].contact],"帮助和咨询句直接指出负责团队。"),makeQuestion(id,"functional",level,5,"What may happen if the procedure is not followed?",base.consequence,[functionalBases[(index+4)%20].consequence,functionalBases[(index+9)%20].consequence],"最后一句说明没有按程序操作的后果。")];return{id,kind:"functional",level,title,category:base.category,text:functionalTemplates[index%6](base,deadline),questions,contentStatus:"reviewed-original",scoringEligible:true,version:"reading-bank-110-v1"};});}

type Topic={title:string;category:string;intervention:string;benefit:string;evidence:string;risk:string;safeguard:string;conclusion:string;term:string;definition:string};
const rows=[
"Repair cafés and local skills|community|support volunteer repair cafés|keep usable goods out of landfill|one district recorded fewer discarded small appliances after monthly sessions|repairs may be unsafe when volunteers exceed their competence|publish clear limits and refer dangerous jobs to qualified tradespeople|repair cafés work best as gateways to skilled repair rather than replacements for it|gateway|a route that provides access to something",
"Night buses and access to work|transport|extend night-bus routes to major employment areas|connect shift workers with jobs outside daytime hours|hospitality employers reported fewer late arrivals after a trial route opened|lightly used services can become expensive|review passenger data while protecting essential journeys|night buses should be judged by access as well as passenger totals|essential|completely necessary",
"Temporary use of vacant shops|economy|offer short leases on empty high-street units|allow new businesses to test demand cheaply|several traders moved into permanent premises after six-month trials|frequent turnover can make a street feel unstable|combine flexible leases with basic quality standards|temporary use can support renewal when it forms part of a longer plan|turnover|the rate at which occupants are replaced",
"Shared gardens on housing estates|housing|convert neglected corners into shared gardens|create social contact and improve local surroundings|residents in one estate organised weekly sessions across three age groups|a small group may dominate decisions|rotate coordinators and publish simple participation rules|shared gardens need inclusive management more than elaborate design|inclusive|welcoming participation from different people",
"Floodable streets|environment|design selected streets to hold storm water temporarily|reduce pressure on underground drains during intense rain|sensors showed a lower peak flow after planted channels were installed|parking and deliveries may be disrupted|consult users and preserve clearly marked access routes|floodable streets are useful when water management and daily access are planned together|peak|the highest point or level",
"Hybrid induction for new staff|work|combine online preparation with supervised office time|give new employees flexibility without removing personal support|new starters completed routine modules earlier and asked better questions in person|remote recruits may struggle to build informal relationships|assign a named colleague and schedule small-group meetings|hybrid induction succeeds when online efficiency is paired with human contact|paired|combined with another thing",
"Four-day work trials|work|test shorter working weeks without reducing service targets|improve recovery time and encourage process review|two teams maintained output after cutting unnecessary meetings|work may simply be compressed into exhausting days|track workload and allow teams to redesign tasks|shorter weeks require operational change rather than a new timetable alone|compressed|forced into a smaller amount of time",
"Paid apprenticeships for career changers|education|expand paid apprenticeships for adults changing careers|let learners gain skills without losing all income|employers retained many participants after the training year|small firms may lack time to supervise beginners|share specialist teaching across a local training partnership|adult apprenticeships grow when supervision costs are recognised|retained|continued to employ or keep",
"Quiet zones in open offices|work|create bookable quiet zones within open offices|support focused work without rebuilding the whole workplace|staff used the zones most during writing and analysis tasks|popular rooms may be occupied by the same people|limit long bookings and monitor unmet demand|quiet zones help only when access is managed fairly|unmet|not satisfied or fulfilled",
"Structured shift handovers|work|use a short standard checklist at every shift change|reduce missing information and repeated work|a care team reported fewer medication queries after adopting the checklist|staff may read mechanically without discussing unusual cases|reserve time for questions and exceptions|a checklist should support professional conversation rather than replace it|mechanically|without thought or personal judgement",
"Refill shops and packaging|environment|make household refill systems easier to use|reduce disposable packaging through repeated container use|regular customers produced less packaging waste over six months|travel and cleaning can reduce the environmental gain|measure the full process and provide convenient local collection|refill systems need evidence about the whole supply chain|chain|a connected series of stages",
"Urban tree canopy|environment|prioritise tree planting in overheated neighbourhoods|provide shade and reduce exposure to extreme heat|street measurements found lower afternoon temperatures below mature trees|young trees can fail without long-term watering|fund maintenance before announcing planting totals|tree policy should value survival and location, not only the number planted|canopy|the upper layer formed by branches and leaves",
"Restoring small wetlands|environment|restore small wetlands beside developed areas|store water while creating habitat|a restored site held runoff that previously reached nearby roads|poorly planned paths can disturb wildlife|separate sensitive zones from durable public routes|wetland projects must balance access with ecological function|runoff|water flowing over land after rain",
"Reducing commercial food waste|environment|require large kitchens to measure discarded food|identify preventable waste before buying new technology|one group reduced purchasing costs after recording waste by category|staff may manipulate figures if they fear blame|use the data for improvement rather than punishment|measurement changes behaviour only when reporting is trusted|manipulate|alter something unfairly to produce a desired result",
"Textile repair services|economy|support local clothing repair services|extend garment life and preserve practical skills|a pilot voucher increased repairs of coats and workwear|subsidies may fund repairs that customers would have purchased anyway|target first-time users and publish additionality data|repair incentives should prove that they create extra activity|additionality|the amount of activity caused by an intervention",
"Tool-lending libraries|community|lend household tools through public libraries|give occasional users access without requiring ownership|borrowers reported completing small home repairs at lower cost|missing parts and unsafe use can raise costs|inspect returns and provide brief operating guidance|tool libraries are viable when maintenance is treated as a core service|viable|capable of working successfully",
"Local street markets|economy|protect space for regular street markets|support small traders and keep town centres active|footfall rose on market days in several side streets|nearby shops may object to delivery restrictions|coordinate loading times and measure effects on all businesses|markets work best when surrounding traders share in the planning|footfall|the number of people visiting a place",
"Public seating networks|community|plan public seating as a connected network|make walking possible for people who need regular rests|older residents travelled farther when reliable benches were available|poorly placed seats may obstruct movement|use access audits and involve mobility-impaired residents|seating should be treated as transport infrastructure, not decoration|audit|a systematic examination",
"Community kitchens|community|open shared kitchens for training and community meals|combine practical learning with social support|participants moved from basic sessions into food-safety qualifications|projects can depend too heavily on short grants|develop paid services alongside protected free places|community kitchens need a stable operating model as well as goodwill|operating model|the way an organisation delivers and funds its work",
"Multilingual public notices|services|provide essential public notices in several languages|help residents act correctly during unfamiliar procedures|translated waste guidance reduced sorting errors in one area|literal translation may hide important local meaning|test wording with speakers who understand the service context|effective translation requires user testing, not substitution alone|literal|following the exact words without adapting meaning",
"Digital medical appointments|health|retain digital appointments for suitable consultations|save travel while preserving clinical access|follow-up discussions were often completed effectively by video|some symptoms are difficult to assess remotely|publish clear rules for switching to face-to-face care|digital appointments should expand choice rather than become a barrier|barrier|something that prevents access or progress",
"Smart household meters|technology|give residents timely information from smart meters|help households notice unusual energy use|some users changed routines after receiving weekly comparisons|data can confuse people when explanations are poor|pair alerts with plain-language guidance and support|information is useful only when households can interpret and act on it|interpret|understand the meaning of information",
"Automated recruitment screening|technology|limit automated screening to transparent supporting tasks|process applications consistently while keeping accountable judgement|structured tools reduced some clerical inconsistencies|historical data may reproduce earlier discrimination|audit outcomes and provide meaningful human review|automation must remain contestable when it affects opportunity|contestable|open to challenge or review",
"Online compliance training|education|redesign online compliance training around realistic decisions|help staff apply rules instead of clicking through slides|scenario-based modules produced better delayed recall|complex screens can distract from the rule being learned|use short cases followed by feedback and later retrieval|digital training should rehearse judgement, not merely record attendance|retrieval|the act of recalling stored information",
"Cashless public services|services|keep non-digital payment routes in increasingly cashless services|avoid excluding people without reliable banking access|service centres still processed a significant minority of cash payments|parallel systems add administrative cost|concentrate assisted payment at accessible locations|efficiency gains should not remove a workable route for vulnerable users|parallel|existing or operating at the same time",
"Cargo bikes for local deliveries|transport|use cargo bikes for suitable short urban deliveries|reduce congestion and parking pressure|operators completed dense delivery rounds faster in restricted streets|large loads and long distances remain unsuitable|match vehicles to routes instead of imposing a single solution|cargo bikes are a targeted logistics tool, not a universal replacement|targeted|directed at a particular need",
"Demand-responsive rural buses|transport|use booking data to route rural buses flexibly|serve dispersed passengers more efficiently|a trial connected villages that had lost fixed evening services|short booking windows can exclude spontaneous travel|retain some guaranteed journeys and accept telephone bookings|flexibility must not make the service unpredictable|dispersed|spread across a wide area",
"Flexible rail fares|transport|offer discounted rail fares outside traditional peak periods|reflect changing work patterns and spread demand|midweek travel increased after restrictions were simplified|too many fare categories can confuse passengers|publish a small number of stable rules|flexible fares should make decisions easier, not merely create more prices|stable|unlikely to change suddenly",
"School streets|transport|restrict motor traffic near schools at opening and closing times|reduce immediate danger and encourage active travel|observations found fewer vehicles at school gates during trials|traffic may shift to neighbouring streets|monitor a wider area and adjust exemptions|school streets require area-wide evaluation rather than gate counts alone|shift|move from one place to another",
"Accessible walking maps|transport|publish walking maps that include gradients and resting places|let users judge whether a route suits their mobility|test users chose different routes when slope data was available|conditions may change after construction work|date every survey and offer a simple correction channel|access information must be current enough to support real decisions|gradient|the steepness of a slope",
"Social prescribing|health|connect suitable patients with non-clinical community activities|address isolation and practical problems alongside medical care|some participants reported improved confidence and routine|referrals fail when local activities lack capacity|fund link workers and map available places accurately|social prescribing depends on the strength of the community services behind it|capacity|the amount that a service can provide",
"Fatigue on night shifts|health|redesign night-shift schedules around fatigue risk|protect judgement before workers feel visibly sleepy|incident reviews linked several errors to repeated long shifts|individual preferences differ and rigid rules may frustrate staff|combine maximum limits with confidential reporting|fatigue management is a system responsibility, not a test of toughness|rigid|unable or unwilling to change",
"Preventive health screening|health|target screening invitations using clear risk information|help people make informed choices about early checks|simplified invitations increased attendance in underserved groups|messages may exaggerate benefits and hide false alarms|present benefits limitations and follow-up steps together|screening communication should support informed consent rather than pressure|consent|agreement based on adequate information",
"Outdoor exercise referrals|health|offer supported outdoor exercise alongside indoor programmes|provide a low-cost route into regular activity|beginners attended more consistently when leaders adapted pace|poor weather and inaccessible paths can exclude participants|maintain alternative sessions and audit routes|outdoor programmes need flexible delivery to remain inclusive|adapted|changed to suit a particular need",
"Clear emergency health messages|health|pre-test emergency health messages with intended audiences|make urgent instructions understandable under stress|short action-led messages were recalled more accurately|oversimplification can remove important exceptions|put the main action first and link to fuller guidance|clarity requires prioritising information not deleting every detail|prioritising|deciding what is most important",
"Adult micro-courses|education|offer short stackable courses for working adults|allow learners to build skills in manageable stages|participants returned for further modules after completing an initial course|small certificates may have little value to employers|agree learning outcomes with local industries|micro-courses need credible progression routes not isolated badges|credible|believable and worthy of trust",
"Library study rooms|education|extend bookable study space in public libraries|support learners who lack quiet space at home|evening rooms were heavily used during examination periods|booking systems may favour users with constant internet access|keep some walk-in places and monitor repeated no-shows|study-space policy should balance certainty with open access|certainty|the state of being sure or guaranteed",
"Workplace literacy support|education|provide confidential workplace literacy support|help employees handle changing documents and systems|participants completed safety records more accurately after coaching|workers may avoid support if they fear stigma|separate learning records from performance discipline|trust is essential for adults to disclose learning needs|stigma|a negative social judgement",
"Peer mentoring for new learners|education|train experienced learners as peer mentors|give newcomers practical guidance from someone with recent experience|mentees were more likely to attend the first month consistently|mentors may give advice beyond their role|define boundaries and provide professional supervision|peer support complements qualified teaching but cannot replace it|complements|adds to something in a useful way",
"Practical assessment|education|use practical demonstrations alongside written assessment|capture skills that are difficult to describe on paper|trainers found different strengths through observed tasks|assessors may judge inconsistently|use shared criteria and moderation samples|practical assessment is fairer only when judgement is standardised|moderation|checking judgements for consistency",
"Modular housing|housing|use modular construction for selected housing projects|shorten on-site building time and improve factory quality control|one project enclosed homes before the wet season|standard units may fit sites or households poorly|allow controlled variation before factory production|modular methods work when standardisation does not erase local needs|standardisation|making things follow a common form",
"Home energy retrofit|housing|coordinate insulation and heating upgrades as one retrofit plan|avoid solving one problem while creating another|whole-home surveys identified ventilation needs before work began|poor sequencing can trap moisture or waste money|require an independent plan and post-work checks|retrofit quality depends on interaction between measures|sequencing|arranging actions in the right order",
"Housing cooperatives|housing|support resident-controlled housing cooperatives|keep decisions and long-term value within a community|members maintained lower turnover in several established schemes|meetings can be dominated by confident participants|provide governance training and accessible voting methods|cooperation needs durable rules as well as shared ideals|governance|the system used to direct and control an organisation",
"Rental inspection systems|housing|use risk-based rental inspections|focus limited staff on properties most likely to be unsafe|repeat complaints helped inspectors identify recurring landlords|tenants may fear retaliation after reporting problems|allow confidential reports and enforce protection against retaliation|inspection data is valuable only when tenants can report safely|retaliation|harmful action taken in response to a complaint",
"Converting offices to homes|housing|convert suitable empty offices into housing|reuse buildings and add homes in central locations|some shallow buildings adapted well around existing windows|deep floor plans may produce dark or awkward rooms|apply residential standards before granting permission|conversion is useful where buildings genuinely support healthy homes|genuinely|in a real and authentic way",
"Local public procurement|economy|divide suitable public contracts into accessible lots|let smaller local suppliers compete|more small firms bid after documentation was simplified|fragmented contracts can increase coordination work|retain common standards and a lead coordinator|local procurement must preserve value and accountability|fragmented|broken into separate parts",
"Visitor levies|economy|use a modest visitor levy for heavily used destinations|fund services affected by tourism|earmarked revenue supported public toilets and trail repairs|poorly designed charges may burden low-cost travellers|publish spending and include proportionate exemptions|a levy gains legitimacy when residents and visitors can see its purpose|legitimacy|public acceptance that something is proper",
"Flexible workspace in small towns|economy|support shared workspaces in well-connected small towns|give remote workers professional space near home|members valued reliable internet and informal contact|desk demand may fluctuate sharply|combine memberships with meeting and training services|shared workspace needs several uses to remain financially stable|fluctuate|rise and fall unpredictably",
"Independent repair businesses|economy|improve access to parts and repair information|help independent repair firms compete with replacement sales|technicians completed more repairs when manuals were available|unsafe modifications can create liability|distinguish repair access from permission to bypass safety controls|repair rights should expand legitimate work while preserving safety|liability|legal responsibility for damage or loss",
"Seasonal employment pathways|economy|link seasonal jobs with recognised training|turn temporary work into a route toward broader employment|workers who completed accredited modules returned in higher-skilled roles|training scheduled during peak work may be inaccessible|offer paid learning during quieter periods|seasonal work becomes more valuable when skills remain portable|portable|usable in different places or jobs",
] as const;
const topics:Topic[]=rows.map(row=>{const [title,category,intervention,benefit,evidence,risk,safeguard,conclusion,term,definition]=row.split("|");return{title,category,intervention,benefit,evidence,risk,safeguard,conclusion,term,definition};});
const essayTemplates=[
(t:Topic)=>`${t.title} is often discussed as a simple idea, but implementation matters. Supporters argue that authorities should ${t.intervention}. The main expected benefit is to ${t.benefit}.\n\nEarly evidence is useful but limited: ${t.evidence}. This does not prove that every location will obtain the same result, although it shows that the proposal is plausible.\n\nA serious concern remains. ${t.risk}. A practical response is to ${t.safeguard}. That safeguard does not remove every difficulty, but it makes performance visible and correctable.\n\nThe strongest conclusion is therefore conditional: ${t.conclusion}. In this context, “${t.term}” means ${t.definition}.`,
(t:Topic)=>`Policies concerning ${t.title.toLowerCase()} can attract enthusiasm before their operating details are understood. One practical proposal is to ${t.intervention}, principally to ${t.benefit}.\n\nThere is some supporting evidence. ${t.evidence}. Yet a result from one trial is a reason to investigate further, not permission to assume universal success.\n\nCritics point out that ${t.risk}. This objection is material rather than fatal. Decision-makers can ${t.safeguard}, then report whether the response actually reduces the risk.\n\nOverall, ${t.conclusion}. The word “${t.term}” is used here to mean ${t.definition}.`,
(t:Topic)=>`A useful debate about ${t.title.toLowerCase()} begins with the problem it is meant to solve. The case for action is that organisations could ${t.intervention} and thereby ${t.benefit}.\n\nThe claim is not entirely theoretical: ${t.evidence}. Even so, evidence of improvement should not be confused with proof that the intervention is sufficient by itself.\n\nImplementation can fail because ${t.risk}. For that reason, a responsible scheme would ${t.safeguard}. Monitoring should examine both intended gains and displaced costs.\n\nOn balance, ${t.conclusion}. Within this argument, “${t.term}” describes something ${t.definition}.`,
(t:Topic)=>`Whether to invest in ${t.title.toLowerCase()} should not be decided by slogans. Advocates want institutions to ${t.intervention}; if it works, this could ${t.benefit}.\n\nObserved experience offers cautious encouragement. ${t.evidence}. The finding matters, but local conditions and the way outcomes are measured may influence it.\n\nThe main warning is that ${t.risk}. Rather than abandoning the proposal, managers should ${t.safeguard}. This makes the trade-off open to examination.\n\nConsequently, ${t.conclusion}. Here, “${t.term}” means ${t.definition}.`,
(t:Topic)=>`${t.title} illustrates why public decisions need both ambition and restraint. A proposed course of action is to ${t.intervention}, with the aim of helping communities to ${t.benefit}.\n\nOne reported result is that ${t.evidence}. It supplies a credible starting point, although longer observation and comparison would strengthen the case.\n\nThere is also a risk: ${t.risk}. The most relevant protection would be to ${t.safeguard}. Without such a measure, headline success could conceal unequal or temporary effects.\n\nThe evidence therefore supports a qualified position: ${t.conclusion}. The term “${t.term}” refers to something ${t.definition}.`,
];
function buildContinuous():ReadingPassage[]{return topics.map((topic,index)=>{const id=`rc-${String(index+1).padStart(3,"0")}`;const level=index<5?3:index<20?4:index<35?5:6;const count=index<10?8:7;const questions=[makeQuestion(id,"continuous",level,0,`What is the writer's main conclusion about ${topic.title.toLowerCase()}?`,topic.conclusion,["the proposal should be adopted everywhere without conditions","the available evidence proves that no action is useful"],"结尾段给出带条件的总判断。"),makeQuestion(id,"continuous",level,1,"What benefit do supporters expect?",topic.benefit,[topics[(index+7)%50].benefit,topics[(index+19)%50].benefit],"首段说明提议希望实现的主要收益。"),makeQuestion(id,"continuous",level,2,"Which evidence is mentioned?",topic.evidence,[topics[(index+4)%50].evidence,topics[(index+13)%50].evidence],"第二段给出了观察或试点证据。"),makeQuestion(id,"continuous",level,3,"What concern does the writer recognise?",topic.risk,[topics[(index+6)%50].risk,topics[(index+21)%50].risk],"第三段明确承认了实施风险。"),makeQuestion(id,"continuous",level,4,"What response to the concern is proposed?",topic.safeguard,[topics[(index+8)%50].safeguard,topics[(index+17)%50].safeguard],"风险之后紧接着给出防护或改进措施。"),makeQuestion(id,"continuous",level,5,`What does “${topic.term}” mean in this passage?`,topic.definition,[topics[(index+5)%50].definition,topics[(index+11)%50].definition],"末句直接界定了目标词在本文中的含义。"),makeQuestion(id,"continuous",level,6,"Which statement best describes the writer's attitude?","cautiously supportive and conditional",["completely opposed and unwilling to consider evidence","certain that every trial will produce identical results"],"作者承认证据和收益，同时强调限制、保障和条件。"),makeQuestion(id,"continuous",level,7,"Why does the writer discuss evidence from a trial?","to show promise without claiming universal proof",["to prove that local conditions never matter","to replace the need for future evaluation"],"第二段区分有希望的证据和普遍证明。")].slice(0,count);return{id,kind:"continuous",level,title:topic.title,category:topic.category,text:essayTemplates[index%5](topic),questions,contentStatus:"reviewed-original",scoringEligible:true,version:"reading-bank-110-v1"};});}
export const readingAssessmentPassages:ReadingPassage[]=[...buildFunctional(),...buildContinuous()];
export const readingAssessmentQuestions=readingAssessmentPassages.flatMap(passage=>passage.questions);
export const readingAssessmentStats={passages:readingAssessmentPassages.length,questions:readingAssessmentQuestions.length,functionalPassages:readingAssessmentPassages.filter(item=>item.kind==="functional").length,continuousPassages:readingAssessmentPassages.filter(item=>item.kind==="continuous").length,byLevel:Object.fromEntries(Array.from({length:6},(_,index)=>[`L${index+1}`,readingAssessmentPassages.filter(item=>item.level===index+1).length])),version:"reading-bank-110-v1"};
