export type SentenceChallenge = {
  id: string;
  title: string;
  level: "基础" | "进阶";
  principle: string;
  segments: { text: string; role: string }[];
  prompt: string;
  options: string[];
  correct: string;
  explanation: string;
  errorHint: string;
  model: string;
};

export const sentenceChallenges: SentenceChallenge[] = [
  {id:"g01",title:"名词前需要谁的？",level:"基础",principle:"形容词性物主代词",segments:[{text:"I",role:"主语"},{text:"would like",role:"表达意愿"},{text:"to confirm",role:"动作"},{text:"my appointment",role:"对象"}],prompt:"I would like to confirm ___ appointment.",options:["my","me","mine"],correct:"my",explanation:"appointment 是名词，前面用形容词性物主代词 my。",errorHint:"空格后面紧跟名词 appointment。",model:"I would like to confirm my appointment."},
  {id:"g02",title:"现在的习惯",level:"基础",principle:"一般现在时",segments:[{text:"The library",role:"主语"},{text:"opens",role:"动词"},{text:"at nine",role:"时间"}],prompt:"The library ___ at nine every weekday.",options:["open","opens","is opening"],correct:"opens",explanation:"every weekday 表示固定安排，第三人称单数主语后用 opens。",errorHint:"看主语是单数还是复数。",model:"The library opens at nine every weekday."},
  {id:"g03",title:"已经发生的事情",level:"基础",principle:"一般过去时",segments:[{text:"I",role:"主语"},{text:"missed",role:"过去动作"},{text:"the bus",role:"对象"},{text:"yesterday",role:"时间"}],prompt:"I ___ the bus yesterday morning.",options:["miss","missed","have missed"],correct:"missed",explanation:"yesterday 给出明确过去时间，用一般过去时 missed。",errorHint:"找句中的过去时间标志。",model:"I missed the bus yesterday morning."},
  {id:"g04",title:"正在发生的动作",level:"基础",principle:"现在进行时",segments:[{text:"They",role:"主语"},{text:"are repairing",role:"正在进行"},{text:"the road",role:"对象"}],prompt:"They ___ the road at the moment.",options:["repair","are repairing","repaired"],correct:"are repairing",explanation:"at the moment 表示此刻正在发生，用 are repairing。",errorHint:"be 动词和 -ing 要一起出现。",model:"They are repairing the road at the moment."},
  {id:"g05",title:"可以做什么",level:"基础",principle:"情态动词 can",segments:[{text:"Members",role:"主语"},{text:"can borrow",role:"能力／许可"},{text:"eight books",role:"对象"}],prompt:"Members can ___ up to eight books.",options:["borrow","borrows","borrowed"],correct:"borrow",explanation:"情态动词 can 后面接动词原形。",errorHint:"can 后面的动词不加 s，也不变过去式。",model:"Members can borrow up to eight books."},
  {id:"g06",title:"必须遵守的规则",level:"基础",principle:"must + 动词原形",segments:[{text:"Visitors",role:"主语"},{text:"must show",role:"强制要求"},{text:"valid identification",role:"对象"}],prompt:"Visitors must ___ valid identification.",options:["show","shows","showing"],correct:"show",explanation:"must 后接动词原形 show。",errorHint:"must 和 can 的后接形式相同。",model:"Visitors must show valid identification."},
  {id:"g07",title:"数量有多少",level:"基础",principle:"可数与不可数",segments:[{text:"How much",role:"询问不可数数量"},{text:"is",role:"系动词"},{text:"the rent",role:"不可数费用"}],prompt:"___ is the monthly rent?",options:["How many","How much","How often"],correct:"How much",explanation:"rent 在这里表示租金金额，用 How much 询问。",errorHint:"不是问次数，也不是问可数物品数量。",model:"How much is the monthly rent?"},
  {id:"g08",title:"一个还是一些",level:"基础",principle:"冠词 a/an",segments:[{text:"I need",role:"主干"},{text:"an appointment",role:"单数名词"},{text:"with a doctor",role:"补充信息"}],prompt:"I need ___ appointment with a doctor.",options:["a","an","some"],correct:"an",explanation:"appointment 以元音音素开头，单数前用 an。",errorHint:"判断发音，不只看字母。",model:"I need an appointment with a doctor."},
  {id:"g09",title:"地点在哪里",level:"基础",principle:"地点介词",segments:[{text:"The computers",role:"主语"},{text:"are",role:"系动词"},{text:"on the first floor",role:"地点"}],prompt:"The computers are ___ the first floor.",options:["at","on","to"],correct:"on",explanation:"表示在某一楼层用介词 on。",errorHint:"英语把楼层理解为一个平面。",model:"The computers are on the first floor."},
  {id:"g10",title:"具体时间点",level:"基础",principle:"时间介词",segments:[{text:"The office",role:"主语"},{text:"closes",role:"动作"},{text:"at five thirty",role:"具体时间"}],prompt:"The office closes ___ five thirty.",options:["at","on","in"],correct:"at",explanation:"具体钟点前用 at。",errorHint:"on 多用于日期，in 多用于月份、年份或较长时段。",model:"The office closes at five thirty."},
  {id:"g11",title:"从什么时候开始",level:"基础",principle:"since 与 for",segments:[{text:"The heating",role:"主语"},{text:"has been broken",role:"持续状态"},{text:"for a week",role:"持续时长"}],prompt:"The heating has been broken ___ a week.",options:["since","for","from"],correct:"for",explanation:"a week 是持续时间长度，用 for。",errorHint:"since 后通常接起点，for 后接时长。",model:"The heating has been broken for a week."},
  {id:"g12",title:"谁来完成动作",level:"基础",principle:"被动语态",segments:[{text:"Protective shoes",role:"承受动作"},{text:"are provided",role:"被动结构"},{text:"by the company",role:"执行者"}],prompt:"Protective shoes ___ by the company.",options:["provide","are provided","provided"],correct:"are provided",explanation:"鞋是被提供的，用 are + 过去分词 provided。",errorHint:"主语不是动作的执行者。",model:"Protective shoes are provided by the company."},
  {id:"g13",title:"更便宜的选择",level:"基础",principle:"比较级",segments:[{text:"The bus",role:"比较对象一"},{text:"is cheaper than",role:"比较"},{text:"a taxi",role:"比较对象二"}],prompt:"The bus is ___ than a taxi.",options:["cheap","cheaper","cheapest"],correct:"cheaper",explanation:"than 前使用比较级 cheaper。",errorHint:"两个对象比较，不用最高级。",model:"The bus is cheaper than a taxi."},
  {id:"g14",title:"最可靠的方式",level:"基础",principle:"最高级",segments:[{text:"The train",role:"主语"},{text:"is the most reliable",role:"最高级"},{text:"option",role:"类别"}],prompt:"The train is ___ reliable option.",options:["more","the most","most"],correct:"the most",explanation:"在多个选择中指出最可靠的一个，用 the most。",errorHint:"最高级前通常需要 the。",model:"The train is the most reliable option."},
  {id:"g15",title:"给出原因",level:"基础",principle:"because 从句",segments:[{text:"I chose the course",role:"结果"},{text:"because",role:"原因连接"},{text:"it fits my schedule",role:"原因"}],prompt:"I chose the course ___ it fits my schedule.",options:["because","so","although"],correct:"because",explanation:"后半句解释选择课程的原因，用 because。",errorHint:"判断空格后是原因还是结果。",model:"I chose the course because it fits my schedule."},
  {id:"g16",title:"说明结果",level:"基础",principle:"so 连接结果",segments:[{text:"The bus was late",role:"原因"},{text:"so",role:"结果连接"},{text:"I missed the meeting",role:"结果"}],prompt:"The bus was late, ___ I missed the meeting.",options:["because","so","but"],correct:"so",explanation:"后半句是前面造成的结果，用 so。",errorHint:"because 引出原因，so 引出结果。",model:"The bus was late, so I missed the meeting."},
  {id:"g17",title:"虽然但是",level:"基础",principle:"although 让步",segments:[{text:"Although the rent is high",role:"让步"},{text:"the flat",role:"主语"},{text:"is convenient",role:"主要观点"}],prompt:"___ the rent is high, the flat is convenient.",options:["Because","Although","Therefore"],correct:"Although",explanation:"两部分意义形成让步对比，用 Although。",errorHint:"高租金通常是不利条件，但结论仍然积极。",model:"Although the rent is high, the flat is convenient."},
  {id:"g18",title:"提出礼貌请求",level:"基础",principle:"could 礼貌请求",segments:[{text:"Could you",role:"礼貌开头"},{text:"send",role:"动作原形"},{text:"the details",role:"对象"}],prompt:"Could you ___ me the details by email?",options:["send","sent","sending"],correct:"send",explanation:"Could you 后用动词原形 send。",errorHint:"这里的 could 用来礼貌请求，不表示过去。",model:"Could you send me the details by email?"},
  {id:"g19",title:"表达愿望",level:"基础",principle:"would like to",segments:[{text:"I would like",role:"礼貌意愿"},{text:"to change",role:"不定式动作"},{text:"my booking",role:"对象"}],prompt:"I would like ___ my booking.",options:["change","to change","changing"],correct:"to change",explanation:"would like 后接 to + 动词原形。",errorHint:"这个结构中 to 不能省略。",model:"I would like to change my booking."},
  {id:"g20",title:"建议怎么做",level:"基础",principle:"should 建议",segments:[{text:"You",role:"主语"},{text:"should arrive",role:"建议"},{text:"ten minutes early",role:"时间方式"}],prompt:"You ___ arrive ten minutes early.",options:["should","should to","are should"],correct:"should",explanation:"should 直接接动词原形，不加 to。",errorHint:"情态动词后不再加另一个 be 或 to。",model:"You should arrive ten minutes early."},
  {id:"g21",title:"条件会带来结果",level:"进阶",principle:"第一条件句",segments:[{text:"If you book early",role:"真实条件"},{text:"you will get",role:"可能结果"},{text:"a lower fare",role:"对象"}],prompt:"If you book early, you ___ a lower fare.",options:["get","will get","would get"],correct:"will get",explanation:"真实未来条件使用 if + 一般现在时，主句用 will。",errorHint:"if 从句里不放 will。",model:"If you book early, you will get a lower fare."},
  {id:"g22",title:"不太现实的假设",level:"进阶",principle:"第二条件句",segments:[{text:"If I lived closer",role:"假设条件"},{text:"I would cycle",role:"假设结果"},{text:"to work",role:"方向"}],prompt:"If I lived closer, I ___ to work.",options:["cycle","will cycle","would cycle"],correct:"would cycle",explanation:"与现在事实不同的假设，用 if + 过去式，主句 would + 动词原形。",errorHint:"lived 在这里不是讲过去经历。",model:"If I lived closer, I would cycle to work."},
  {id:"g23",title:"已经做完了吗",level:"进阶",principle:"现在完成时",segments:[{text:"I",role:"主语"},{text:"have completed",role:"已完成"},{text:"the form",role:"对象"}],prompt:"I ___ the application form already.",options:["complete","completed","have completed"],correct:"have completed",explanation:"already 强调截至现在已经完成，使用现在完成时。",errorHint:"动作结果与现在有关。",model:"I have completed the application form already."},
  {id:"g24",title:"过去之前已经发生",level:"进阶",principle:"过去完成时",segments:[{text:"The train",role:"主语"},{text:"had left",role:"更早的过去"},{text:"before I arrived",role:"后发生的过去"}],prompt:"The train ___ before I reached the platform.",options:["left","had left","has left"],correct:"had left",explanation:"火车离开发生在我到达之前，用过去完成时 had left。",errorHint:"句中有两个过去动作，要区分先后。",model:"The train had left before I reached the platform."},
  {id:"g25",title:"正在进行时被打断",level:"进阶",principle:"过去进行时",segments:[{text:"I was waiting",role:"持续背景"},{text:"when",role:"时间连接"},{text:"the bus arrived",role:"短动作"}],prompt:"I ___ when the bus finally arrived.",options:["waited","was waiting","have waited"],correct:"was waiting",explanation:"等待是持续背景，arrived 是打断它的短动作。",errorHint:"when 前后常出现“持续动作 + 短动作”。",model:"I was waiting when the bus finally arrived."},
  {id:"g26",title:"把两个信息连起来",level:"进阶",principle:"定语从句 who",segments:[{text:"Employees",role:"先行词"},{text:"who work nights",role:"修饰人"},{text:"receive extra pay",role:"主句"}],prompt:"Employees ___ work nights receive extra pay.",options:["which","who","where"],correct:"who",explanation:"先行词 Employees 指人，关系代词用 who。",errorHint:"which 通常指物，where 指地点。",model:"Employees who work nights receive extra pay."},
  {id:"g27",title:"修饰一个地方",level:"进阶",principle:"定语从句 where",segments:[{text:"This is the centre",role:"地点先行词"},{text:"where",role:"地点关系词"},{text:"the course is held",role:"修饰信息"}],prompt:"This is the centre ___ the course is held.",options:["who","where","what"],correct:"where",explanation:"先行词 centre 是地点，用 where 引出发生在那里的事情。",errorHint:"空格相当于“在这个地方”。",model:"This is the centre where the course is held."},
  {id:"g28",title:"动作变成名词",level:"进阶",principle:"动名词作主语",segments:[{text:"Using public transport",role:"动名词主语"},{text:"can reduce",role:"谓语"},{text:"traffic",role:"对象"}],prompt:"___ public transport can reduce traffic.",options:["Use","Using","Used"],correct:"Using",explanation:"一个动作作为句子的主语时，可使用动名词 Using。",errorHint:"空格后的短语整体是主语。",model:"Using public transport can reduce traffic."},
  {id:"g29",title:"做事的目的",level:"进阶",principle:"in order to",segments:[{text:"The council added buses",role:"行动"},{text:"in order to reduce",role:"目的"},{text:"congestion",role:"对象"}],prompt:"The council added buses ___ reduce congestion.",options:["because","in order to","so that to"],correct:"in order to",explanation:"后面是动词原形 reduce，in order to 清楚表达目的。",errorHint:"because 后面通常需要完整从句。",model:"The council added buses in order to reduce congestion."},
  {id:"g30",title:"不仅因为一件事",level:"进阶",principle:"as well as",segments:[{text:"The fee covers",role:"主干"},{text:"materials",role:"对象一"},{text:"as well as support",role:"并列对象二"}],prompt:"The fee covers materials ___ online support.",options:["as well as","instead","despite"],correct:"as well as",explanation:"这里把 materials 和 online support 并列连接。",errorHint:"句意是两者都包含，不是二选一。",model:"The fee covers materials as well as online support."},
  {id:"g31",title:"一个原因造成的结果",level:"进阶",principle:"due to + 名词",segments:[{text:"The service was cancelled",role:"结果"},{text:"due to",role:"原因介词"},{text:"heavy snow",role:"名词原因"}],prompt:"The service was cancelled ___ heavy snow.",options:["because","due to","therefore"],correct:"due to",explanation:"heavy snow 是名词短语，前面可用 due to。",errorHint:"because 后面应接完整句子。",model:"The service was cancelled due to heavy snow."},
  {id:"g32",title:"正式说明要求",level:"进阶",principle:"be required to",segments:[{text:"Applicants",role:"承受要求"},{text:"are required",role:"被动要求"},{text:"to provide references",role:"具体动作"}],prompt:"Applicants are required ___ two references.",options:["provide","to provide","providing"],correct:"to provide",explanation:"be required 后接 to + 动词原形。",errorHint:"required 在这里后面需要不定式。",model:"Applicants are required to provide two references."},
  {id:"g33",title:"避免绝对化",level:"进阶",principle:"may 表示可能",segments:[{text:"This change",role:"主语"},{text:"may improve",role:"谨慎判断"},{text:"access",role:"对象"}],prompt:"This change ___ improve access for older residents.",options:["may","must","always"],correct:"may",explanation:"没有足够证据保证必然结果时，用 may 表示可能，更符合议论文语气。",errorHint:"IELTS 写作中要区分“可能”和“必然”。",model:"This change may improve access for older residents."},
  {id:"g34",title:"比较两个方案",level:"进阶",principle:"whereas 对比",segments:[{text:"Buses are flexible",role:"观点一"},{text:"whereas",role:"对比连接"},{text:"trains carry more people",role:"观点二"}],prompt:"Buses are flexible, ___ trains carry more people.",options:["because","whereas","therefore"],correct:"whereas",explanation:"两个完整分句形成直接对比，用 whereas。",errorHint:"不是因果关系。",model:"Buses are flexible, whereas trains carry more people."},
  {id:"g35",title:"先让步再表态",level:"进阶",principle:"even though",segments:[{text:"Even though it costs more",role:"让步事实"},{text:"I prefer",role:"主要观点"},{text:"the reliable service",role:"对象"}],prompt:"___ it costs more, I prefer the reliable service.",options:["Even though","As a result","In order to"],correct:"Even though",explanation:"价格更高与仍然选择形成让步关系。",errorHint:"主句没有表达结果或目的。",model:"Even though it costs more, I prefer the reliable service."},
  {id:"g36",title:"完整总结观点",level:"进阶",principle:"总结句结构",segments:[{text:"To sum up",role:"总结标记"},{text:"reliable services",role:"主语"},{text:"benefit the whole community",role:"结论"}],prompt:"___, reliable services benefit the whole community.",options:["For example","To sum up","On the other hand"],correct:"To sum up",explanation:"句子概括前文观点，使用 To sum up。",errorHint:"这里不是举例，也没有提出相反观点。",model:"To sum up, reliable services benefit the whole community."},
];
