import { sentenceChallenges as foundationChallenges } from "./sentence-challenges-base";
import { sentenceChallengeBatch02 } from "./foundation-batch-02";
import { sentenceChallengeBatch03 } from "./foundation-batch-03";
import { sentenceChallengeBatch04 } from "./foundation-batch-04";
import { sentenceChallengeBatch05 } from "./foundation-batch-05";
import { sentenceChallengeBatch06 } from "./foundation-batch-06";
import { sentenceChallengeBatch07 } from "./foundation-batch-07";
import { sentenceChallengeBatch08 } from "./foundation-batch-08";
import { sentenceChallengeBatch09 } from "./foundation-batch-09";
import { sentenceChallengeBatch10 } from "./foundation-batch-10";
import { sentenceChallengeBatch11 } from "./foundation-batch-11";
import { sentenceChallengeBatch12 } from "./foundation-batch-12";
import { sentenceChallengeBatch13 } from "./foundation-batch-13";
import { sentenceChallengeBatch14 } from "./foundation-batch-14";
import { sentenceChallengeBatch15 } from "./foundation-batch-15";
import { sentenceChallengeBatch16 } from "./foundation-batch-16";
import { sentenceChallengeBatch17 } from "./foundation-batch-17";
import { sentenceChallengeBatch18 } from "./foundation-batch-18";

export type { SentenceChallenge } from "./sentence-challenges-base";
export const sentenceChallenges = [...foundationChallenges, ...sentenceChallengeBatch02, ...sentenceChallengeBatch03, ...sentenceChallengeBatch04, ...sentenceChallengeBatch05, ...sentenceChallengeBatch06, ...sentenceChallengeBatch07, ...sentenceChallengeBatch08, ...sentenceChallengeBatch09, ...sentenceChallengeBatch10, ...sentenceChallengeBatch11, ...sentenceChallengeBatch12, ...sentenceChallengeBatch13, ...sentenceChallengeBatch14, ...sentenceChallengeBatch15, ...sentenceChallengeBatch16, ...sentenceChallengeBatch17, ...sentenceChallengeBatch18];
