import type { CourseLesson } from "./curriculum-v2";

export const speakingLessons: CourseLesson[] = [
  {id:"s1",skill:"speaking",section:"Part 1",title:"家与居住地",level:"基础",minutes:9,focus:"直接回答并补一个细节",prompts:["Where do you live now?","What do you like about your neighbourhood?","Is there anything you would change about your home?","Do you think you will live there for a long time?"],keywords:["because","usually","near","would"]},
  {id:"s2",skill:"speaking",section:"Part 1",title:"工作与日常安排",level:"基础",minutes:9,focus:"现在时、频率和理由",prompts:["What kind of work do you do?","What is a typical working day like for you?","Which part of your day do you enjoy most?","Would you like to change your working hours?"],keywords:["work","usually","enjoy","change"]},
  {id:"s3",skill:"speaking",section:"Part 1",title:"交通与通勤",level:"基础",minutes:9,focus:"比较方式并解释选择",prompts:["How do you usually travel to work or study?","How long does the journey take?","What problems do you sometimes experience?","How could transport in your area improve?"],keywords:["usually","takes","problem","improve"]},
  {id:"s4",skill:"speaking",section:"Part 1",title:"学习英语",level:"基础",minutes:9,focus:"原因、习惯和困难",prompts:["Why are you learning English?","How often do you study it?","Which English skill is most difficult for you?","What has helped you make progress?"],keywords:["because","often","difficult","helped"]},
  {id:"s5",skill:"speaking",section:"Part 1",title:"购物与服务",level:"基础",minutes:9,focus:"过去经历与偏好",prompts:["Do you prefer shopping online or in stores?","What do you usually buy online?","Have you ever returned an item?","What makes customer service good?"],keywords:["prefer","usually","returned","service"]},
  {id:"s6",skill:"speaking",section:"Part 1",title:"健康与运动",level:"基础",minutes:9,focus:"频率、变化和计划",prompts:["What do you do to stay healthy?","Do you exercise regularly?","Were you more active as a child?","Is there a new activity you would like to try?"],keywords:["healthy","regularly","child","would"]},
  {id:"s7",skill:"speaking",section:"Part 2",title:"一次有帮助的谈话",level:"进阶",minutes:13,focus:"准备一分钟、连续说两分钟",task:"Describe a conversation that helped you make a decision.",bullets:["who you spoke with","when and where it happened","what you discussed","why the conversation was helpful"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["spoke","discussed","decided","helpful"]},
  {id:"s8",skill:"speaking",section:"Part 2",title:"一项想学习的技能",level:"进阶",minutes:13,focus:"过去、现在和未来时态",task:"Describe a skill you would like to learn.",bullets:["what the skill is","why you want to learn it","how you would learn it","how it might help you"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["learn","because","plan","help"]},
  {id:"s9",skill:"speaking",section:"Part 2",title:"一次服务问题",level:"进阶",minutes:13,focus:"按时间顺序讲清问题和结果",task:"Describe a time when you received poor service.",bullets:["where and when it happened","what service you expected","what went wrong","how the situation ended"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["expected","problem","contacted","result"]},
  {id:"s10",skill:"speaking",section:"Part 2",title:"常去的公共场所",level:"进阶",minutes:13,focus:"空间描述与个人意义",task:"Describe a public place that you often visit.",bullets:["where it is","what it looks like","what you do there","why it is useful to you"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["located","usually","useful","because"]},
  {id:"s11",skill:"speaking",section:"Part 2",title:"克服的一次困难",level:"进阶",minutes:13,focus:"问题—行动—结果—反思",task:"Describe a difficulty that you successfully dealt with.",bullets:["what the difficulty was","why it was challenging","what you did","what you learned from it"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["challenge","decided","managed","learned"]},
  {id:"s12",skill:"speaking",section:"Part 3",title:"成年人学习",level:"进阶",minutes:15,focus:"观点—原因—例子—回扣",prompts:["Why do some adults stop learning new skills?","Should employers give workers time for training?","How has technology changed adult education?","Are online courses suitable for everyone?"],keywords:["reason","example","however","therefore"]},
  {id:"s13",skill:"speaking",section:"Part 3",title:"城市交通与公平",level:"进阶",minutes:15,focus:"比较、让步和抽象讨论",prompts:["Why do people choose cars when public transport is available?","How can cities encourage walking or cycling?","Should older people receive cheaper transport?","What might city transport look like in twenty years?"],keywords:["compared","although","access","future"]},
  {id:"s14",skill:"speaking",section:"Part 3",title:"工作方式的变化",level:"进阶",minutes:15,focus:"多方影响与条件",prompts:["Why has remote work become more common?","What problems can remote workers experience?","How should managers judge performance?","Will offices remain important in the future?"],keywords:["because","however","depends","future"]},
  {id:"s15",skill:"speaking",section:"Part 3",title:"社区与志愿服务",level:"进阶",minutes:15,focus:"政策建议与现实限制",prompts:["Why do people volunteer in their communities?","How can organisations attract more volunteers?","Should young people be required to do community work?","Which local services depend most on volunteers?"],keywords:["reason","encourage","although","example"]},
  {id:"s16",skill:"speaking",section:"Part 3",title:"消费与环境",level:"进阶",minutes:15,focus:"原因、责任和解决方案",prompts:["Why do people replace products instead of repairing them?","Should manufacturers provide spare parts for longer?","How can consumers identify durable products?","Who should pay for the cost of recycling?"],keywords:["cost","responsibility","because","solution"]},
];
