export type SpeakingDrill = {
  id: string;
  level: "基础" | "进阶";
  title: string;
  scenario: string;
  prompt: string;
  model: string;
  keywords: string[];
  followUp: string;
};

export const speakingDrills: SpeakingDrill[] = [
  {id:"d01",level:"基础",title:"确认预约",scenario:"给诊所打电话",prompt:"Confirm your appointment for tomorrow.",model:"I would like to confirm my appointment for tomorrow.",keywords:["confirm","appointment","tomorrow"],followUp:"What time is the appointment?"},
  {id:"d02",level:"基础",title:"修改预订",scenario:"联系酒店前台",prompt:"Ask to change your booking to Friday.",model:"Could I change my booking to Friday, please?",keywords:["change","booking","Friday"],followUp:"Why do you need to change it?"},
  {id:"d03",level:"基础",title:"询问营业时间",scenario:"致电社区图书馆",prompt:"Ask what time the library closes today.",model:"Could you tell me what time the library closes today?",keywords:["time","library","closes"],followUp:"Is it open at the weekend?"},
  {id:"d04",level:"基础",title:"报告维修问题",scenario:"联系房屋中介",prompt:"Report that the heating is not working.",model:"I am calling because the heating is not working.",keywords:["heating","not","working"],followUp:"How long has the problem continued?"},
  {id:"d05",level:"基础",title:"申请退款",scenario:"在商店服务台",prompt:"Ask for a refund for a damaged item.",model:"I would like to apply for a refund because this item is damaged.",keywords:["refund","item","damaged"],followUp:"Do you have proof of purchase?"},
  {id:"d06",level:"基础",title:"问路",scenario:"在火车站",prompt:"Ask which platform the train leaves from.",model:"Could you tell me which platform the train leaves from?",keywords:["platform","train","leaves"],followUp:"What is the departure time?"},
  {id:"d07",level:"基础",title:"说明迟到",scenario:"给经理打电话",prompt:"Explain that a traffic delay will make you late.",model:"There is a serious traffic delay, so I will be about twenty minutes late.",keywords:["traffic","delay","late"],followUp:"When do you expect to arrive?"},
  {id:"d08",level:"基础",title:"请假",scenario:"与经理沟通",prompt:"Ask for one day of annual leave next week.",model:"I would like to request one day of annual leave next Wednesday.",keywords:["request","annual leave","Wednesday"],followUp:"Who can cover your work?"},
  {id:"d09",level:"基础",title:"说明身体不适",scenario:"与护士交谈",prompt:"Say that you have felt unwell since yesterday.",model:"I have felt unwell since yesterday and I have a bad headache.",keywords:["unwell","yesterday","headache"],followUp:"Have you taken any medicine?"},
  {id:"d10",level:"基础",title:"加入活动",scenario:"在社区中心",prompt:"Say that you want to take part in a weekend class.",model:"I would like to take part in the weekend cooking class.",keywords:["take part","weekend","class"],followUp:"Why are you interested in it?"},
  {id:"d11",level:"基础",title:"核对个人信息",scenario:"填写登记表",prompt:"Give your name and spell it clearly.",model:"My name is Naran Bat. That is N-A-R-A-N, B-A-T.",keywords:["name","N-A-R-A-N","B-A-T"],followUp:"What is your date of birth?"},
  {id:"d12",level:"基础",title:"请求重复",scenario:"没有听清一个日期",prompt:"Politely ask the speaker to repeat the date.",model:"Could you repeat the date, please? I did not hear it clearly.",keywords:["repeat","date","please"],followUp:"Can you confirm the month as well?"},
  {id:"d13",level:"基础",title:"介绍居住地",scenario:"Speaking Part 1",prompt:"Where do you live now?",model:"I live in a quiet area near the city centre, and it is convenient for work.",keywords:["live","near","because"],followUp:"What do you like most about the area?"},
  {id:"d14",level:"基础",title:"谈论住房",scenario:"Speaking Part 1",prompt:"What kind of home do you live in?",model:"I live in a small flat with two bedrooms, and I share it with my family.",keywords:["flat","bedrooms","family"],followUp:"Would you like to move in the future?"},
  {id:"d15",level:"基础",title:"介绍工作",scenario:"Speaking Part 1",prompt:"What kind of work do you do?",model:"I work in engineering, and most of my job involves checking technical documents.",keywords:["work","job","involves"],followUp:"Which part of your work do you enjoy?"},
  {id:"d16",level:"基础",title:"日常安排",scenario:"Speaking Part 1",prompt:"What is a typical weekday like for you?",model:"I usually start work early, finish in the evening and study English after dinner.",keywords:["usually","work","study"],followUp:"Is your weekend routine different?"},
  {id:"d17",level:"基础",title:"通勤方式",scenario:"Speaking Part 1",prompt:"How do you usually travel to work?",model:"I usually take the train because it is more reliable than driving.",keywords:["usually","train","because"],followUp:"What would improve your journey?"},
  {id:"d18",level:"基础",title:"购物习惯",scenario:"Speaking Part 1",prompt:"Do you prefer shopping online or in stores?",model:"I prefer shopping online because I can compare prices and save time.",keywords:["prefer","because","time"],followUp:"What do you normally buy online?"},
  {id:"d19",level:"基础",title:"运动习惯",scenario:"Speaking Part 1",prompt:"Do you do any regular exercise?",model:"I walk for about thirty minutes most days because it helps me relax.",keywords:["walk","days","because"],followUp:"Did you exercise more when you were younger?"},
  {id:"d20",level:"基础",title:"使用图书馆",scenario:"Speaking Part 1",prompt:"How often do you use a library?",model:"I use the local library once or twice a month to borrow books and study quietly.",keywords:["library","month","borrow"],followUp:"What services should libraries provide?"},
  {id:"d21",level:"基础",title:"学习英语",scenario:"Speaking Part 1",prompt:"Why are you learning English?",model:"I am learning English because I want to reach IELTS 6 and communicate more confidently.",keywords:["English","because","IELTS"],followUp:"Which skill is most difficult for you?"},
  {id:"d22",level:"基础",title:"使用手机",scenario:"Speaking Part 1",prompt:"What do you mainly use your phone for?",model:"I mainly use my phone for messages, maps and short English practice.",keywords:["phone","use","English"],followUp:"Could you live without a smartphone?"},
  {id:"d23",level:"基础",title:"周末活动",scenario:"Speaking Part 1",prompt:"What do you usually do at weekends?",model:"I usually spend time with my family, do some shopping and prepare for the next week.",keywords:["usually","family","week"],followUp:"Would you like to change your weekends?"},
  {id:"d24",level:"基础",title:"家乡变化",scenario:"Speaking Part 1",prompt:"Has your hometown changed in recent years?",model:"Yes, it has grown quickly, and there are now more shops and better roads.",keywords:["grown","shops","roads"],followUp:"Has every change been positive?"},
  {id:"d25",level:"进阶",title:"公共交通",scenario:"Speaking Part 3",prompt:"Why do some people still drive when public transport is available?",model:"The main reason is that a car can be more convenient, especially when services are unreliable or homes are far from a stop.",keywords:["reason","convenient","reliable"],followUp:"How could cities change this choice?"},
  {id:"d26",level:"进阶",title:"成年人学习",scenario:"Speaking Part 3",prompt:"Why do some adults stop learning new skills?",model:"Some adults lack time or confidence; however, flexible courses and clear goals can make learning easier.",keywords:["time","confidence","however"],followUp:"Should employers help workers learn?"},
  {id:"d27",level:"进阶",title:"远程工作",scenario:"Speaking Part 3",prompt:"What are the main advantages of working from home?",model:"Working from home saves commuting time and may improve flexibility, although it can also reduce social contact.",keywords:["time","flexibility","although"],followUp:"Who is not suited to remote work?"},
  {id:"d28",level:"进阶",title:"社区活动",scenario:"Speaking Part 3",prompt:"How can communities encourage people to volunteer?",model:"They can offer short, practical opportunities and explain clearly how each volunteer's work helps local residents.",keywords:["opportunities","volunteer","residents"],followUp:"Should schools require volunteer work?"},
  {id:"d29",level:"进阶",title:"健康责任",scenario:"Speaking Part 3",prompt:"Should governments or individuals be more responsible for public health?",model:"Both have a role: governments provide safe services, while individuals make daily choices about diet and exercise.",keywords:["governments","individuals","choices"],followUp:"How can unhealthy habits be changed?"},
  {id:"d30",level:"进阶",title:"住房成本",scenario:"Speaking Part 3",prompt:"Why is housing expensive in many large cities?",model:"Demand often grows faster than supply, and jobs are concentrated in areas where there is limited space to build.",keywords:["demand","supply","space"],followUp:"What could local government do?"},
  {id:"d31",level:"进阶",title:"网络购物",scenario:"Speaking Part 3",prompt:"How has online shopping changed customer behaviour?",model:"People compare prices more easily and expect faster service, but they may also buy things they do not need.",keywords:["prices","service","but"],followUp:"Will physical shops disappear?"},
  {id:"d32",level:"进阶",title:"公共图书馆未来",scenario:"Speaking Part 3",prompt:"Are public libraries still necessary in the digital age?",model:"Yes. Besides lending books, libraries provide quiet study space, internet access and support for people who need help.",keywords:["libraries","access","support"],followUp:"How should libraries change?"},
  {id:"d33",level:"进阶",title:"环境选择",scenario:"Speaking Part 3",prompt:"Why is it difficult for people to reduce household waste?",model:"Convenient products often use extra packaging, and people may not know which materials can be recycled locally.",keywords:["packaging","know","recycled"],followUp:"Should companies carry more responsibility?"},
  {id:"d34",level:"进阶",title:"城市压力",scenario:"Speaking Part 3",prompt:"What causes stress for people living in large cities?",model:"Long journeys, high housing costs and crowded public spaces can create constant pressure for city residents.",keywords:["journeys","costs","pressure"],followUp:"Which solution would have the greatest effect?"},
  {id:"d35",level:"进阶",title:"技术与教育",scenario:"Speaking Part 3",prompt:"Has technology made education more equal?",model:"It has improved access to information, although people without reliable devices or internet connections may still be excluded.",keywords:["access","although","excluded"],followUp:"Will teachers become less important?"},
  {id:"d36",level:"进阶",title:"老龄化社会",scenario:"Speaking Part 3",prompt:"How can cities support an ageing population?",model:"Cities need accessible transport, nearby health services and safe public spaces so that older people can remain independent.",keywords:["transport","services","independent"],followUp:"Should families or governments lead this support?"},
];
