import type { CourseLesson } from "./curriculum-v2";

const task1Checklist = ["开头直接说明写信目的","三个任务点都有具体信息","语气与收信人关系一致","检查时态、单复数和拼写"];
const task2Checklist = ["引言完整回应题目","每个主体段只有一个中心重点","观点后有解释或例子","结论不加入全新观点"];

export const writingLessons: CourseLesson[] = [
  {id:"w1",skill:"writing",section:"Task 1 · 正式信",title:"投诉租住房屋供暖",level:"基础",minutes:24,focus:"目的明确、覆盖三点、正式语气",task:"You rent a flat through an agency. The heating has not worked for one week. Write a letter to the agency. Write at least 150 words.",bullets:["describe the problem and say how long it has continued","explain how the problem is affecting you","say what action you want the agency to take"],checklist:task1Checklist},
  {id:"w2",skill:"writing",section:"Task 1 · 半正式信",title:"向经理申请调班",level:"基础",minutes:24,focus:"解释原因、提出替代方案",task:"You need to change one of your work shifts next month. Write a letter to your manager. Write at least 150 words.",bullets:["say which shift you need to change","explain why you need the change","suggest how you could make up the working time"],checklist:task1Checklist},
  {id:"w3",skill:"writing",section:"Task 1 · 私人信",title:"邀请朋友来家乡",level:"基础",minutes:24,focus:"自然语气、活动安排",task:"A friend is planning to visit your home town. Write a letter inviting your friend to stay with you. Write at least 150 words.",bullets:["describe the accommodation you can offer","recommend two things you can do together","tell your friend what to bring"],checklist:task1Checklist},
  {id:"w4",skill:"writing",section:"Task 1 · 正式信",title:"询问职业培训课程",level:"基础",minutes:24,focus:"提出清楚具体的问题",task:"You saw an advertisement for a weekend professional training course, but some information was missing. Write a letter to the course organiser. Write at least 150 words.",bullets:["explain why you are interested in the course","ask about the timetable and class size","ask what the fee includes"],checklist:task1Checklist},
  {id:"w5",skill:"writing",section:"Task 1 · 半正式信",title:"感谢同事并归还物品",level:"基础",minutes:24,focus:"感谢、解释与安排",task:"A colleague helped you when you were ill and lent you some equipment. Write a letter to your colleague. Write at least 150 words.",bullets:["thank your colleague for the help","explain how the equipment was useful","arrange when and where you will return it"],checklist:task1Checklist},
  {id:"w6",skill:"writing",section:"Task 1 · 私人信",title:"取消朋友旅行计划",level:"基础",minutes:24,focus:"道歉、原因与新安排",task:"You planned a short trip with a friend, but you can no longer go on the agreed dates. Write a letter to your friend. Write at least 150 words.",bullets:["apologise for changing the plan","explain why you cannot travel then","suggest different dates and activities"],checklist:task1Checklist},
  {id:"w7",skill:"writing",section:"Task 1 · 正式信",title:"投诉损坏的网购物品",level:"进阶",minutes:25,focus:"事实顺序、证据和合理诉求",task:"An item you ordered online arrived damaged, and the seller has not answered your first message. Write a letter to the customer service manager. Write at least 150 words.",bullets:["give the order details and describe the damage","explain what happened after you first contacted the seller","state the solution and response time you expect"],checklist:task1Checklist},
  {id:"w8",skill:"writing",section:"Task 1 · 半正式信",title:"建议改善员工休息区",level:"进阶",minutes:25,focus:"问题—影响—建议",task:"The staff break area at your workplace needs improvement. Write a letter to your manager. Write at least 150 words.",bullets:["describe the present problems","explain how they affect staff","suggest two practical improvements"],checklist:task1Checklist},
  {id:"w9",skill:"writing",section:"Task 2 · 观点",title:"公共交通是否应免费",level:"进阶",minutes:42,focus:"明确立场、解释与例子",task:"Some people think public transport should be free for everyone. To what extent do you agree or disagree? Write at least 250 words.",bullets:["state the degree of your agreement clearly","explain two main reasons","support the reasons with realistic examples"],checklist:task2Checklist},
  {id:"w10",skill:"writing",section:"Task 2 · 双边讨论",title:"独居还是与家人同住",level:"进阶",minutes:42,focus:"讨论双方并给出观点",task:"Some adults prefer to live alone, while others prefer to live with family. Discuss both views and give your own opinion. Write at least 250 words.",bullets:["explain benefits of living alone","explain benefits of living with family","give and justify your own view"],checklist:task2Checklist},
  {id:"w11",skill:"writing",section:"Task 2 · 原因与解决",title:"城市生活压力",level:"进阶",minutes:42,focus:"原因与方案一一对应",task:"Many people living in large cities experience high levels of stress. What are the causes, and what solutions can you suggest? Write at least 250 words.",bullets:["analyse at least two causes","propose a realistic solution for each cause","explain why the solutions could work"],checklist:task2Checklist},
  {id:"w12",skill:"writing",section:"Task 2 · 优缺点",title:"在家办公成为常态",level:"进阶",minutes:42,focus:"权衡影响并形成结论",task:"In many jobs, working from home is becoming more common. Do the advantages of this development outweigh the disadvantages? Write at least 250 words.",bullets:["explain significant advantages","explain significant disadvantages","make a clear overall judgement"],checklist:task2Checklist},
  {id:"w13",skill:"writing",section:"Task 2 · 双问题",title:"成年人频繁更换工作",level:"进阶",minutes:42,focus:"完整回答两个问题",task:"More adults now change jobs several times during their working lives. Why is this happening? Is this a positive or negative development? Write at least 250 words.",bullets:["explain reasons for more frequent job changes","evaluate positive and negative effects","state a consistent final position"],checklist:task2Checklist},
  {id:"w14",skill:"writing",section:"Task 2 · 观点",title:"政府是否应资助公共图书馆",level:"进阶",minutes:42,focus:"回应反方并维护立场",task:"Some people say governments should stop funding public libraries because information is available online. To what extent do you agree or disagree? Write at least 250 words.",bullets:["explain what online information can replace","identify services that libraries still provide","reach a clear judgement about public funding"],checklist:task2Checklist},
  {id:"w15",skill:"writing",section:"Task 2 · 双边讨论",title:"环保责任属于个人还是企业",level:"进阶",minutes:42,focus:"比较责任范围",task:"Some people believe individuals should change their behaviour to protect the environment, while others think businesses and governments must take the main responsibility. Discuss both views and give your own opinion. Write at least 250 words.",bullets:["explain what individuals can realistically do","explain the power of institutions and businesses","justify how responsibility should be shared"],checklist:task2Checklist},
  {id:"w16",skill:"writing",section:"Task 2 · 原因与解决",title:"可修理物品被过早丢弃",level:"进阶",minutes:42,focus:"分析机制与政策方案",task:"Many household products are thrown away even when they could be repaired. Why does this happen, and how can the amount of waste be reduced? Write at least 250 words.",bullets:["analyse economic and practical reasons","suggest actions by manufacturers or government","explain how consumers could be supported"],checklist:task2Checklist},
];
