import asyncio
from pathlib import Path
import edge_tts
TEXTS={
125:"Assistant. Harbour Work Hub. Applicant. I need a desk three mornings a week. Assistant. The flexitime membership covers any twelve half-days per month. It costs sixty-eight pounds. A fixed weekday plan is fifty-four pounds but cannot be changed after the first booking. Applicant. I will take the flexible plan. Assistant. It includes Wi-Fi, lockers and printing up to forty pages. Meeting rooms cost six pounds an hour. Applicant. Can I start next Tuesday? Assistant. Yes. Bring photo identification and a bank card. Your access code will be sent by email after payment. The centre opens at seven thirty, but reception is staffed from eight thirty.",
126:"Today we will revegetate the northern dune, where overgrazed ground has begun to erode. Team one will collect litter between markers one and four. Team two will plant native grass behind the temporary fence, and team three will photograph each plot before and after work. Do not spread across the open sand; use the roped path so young roots are not crushed. Gloves and tools are in the green trailer. Drinking water is beside the first-aid tent. At eleven forty-five, everyone should return to the shelter for a safety count. The tide will cover the lower path after twelve thirty, so no volunteer may remain beyond marker four after noon.",
127:"Tutor. Your project links census data with commuting time in three districts. Hana. The census gives household size, age and employment, but not daily travel time. Omar. We will combine it with the transport survey. Tutor. Good. Make sure both datasets use the same geographic boundaries. Hana. One survey excludes people working from home. Tutor. Then state that limitation rather than imputing their travel pattern. Omar. Should we compare twenty eleven and twenty twenty-one? Tutor. Yes, but the pandemic may distort the later figure. Begin with descriptive maps, then test whether housing cost and journey length remain related after income is considered. Submit your variable table on Thursday and the first map next Monday.",
128:"A megacity creates heat through dense construction, traffic and limited vegetation, but exposure is not evenly distributed. Census data may reveal where older people live alone, yet a ten-year count can quickly become outdated. Health planners should interweave census records with recent clinic, housing and temperature data. Air-conditioning can mollify immediate discomfort, but widespread use raises electricity demand and may intensify outdoor heat. It can also impoverish households facing high tariffs. More durable measures include shade, ventilation, reflective surfaces and programmes to revegetate public land. Authorities must not trivialize residents' knowledge: people often know which bus stops, flats and workplaces become dangerous first. Nor should planners presuppose that every vulnerable resident can use a smartphone warning. Effective adaptation combines physical design, accessible communication and services that check directly on isolated people."
}
async def main():
    output=Path(__file__).resolve().parents[1]/"public"/"audio";output.mkdir(parents=True,exist_ok=True)
    for lesson_id,text in TEXTS.items():
        destination=output/f"l{lesson_id}.mp3";await edge_tts.Communicate(text,"en-GB-SoniaNeural",rate="-8%").save(str(destination))
        if destination.stat().st_size<=100_000:raise RuntimeError(f"Audio too small: {destination}")
        print(destination.name,destination.stat().st_size)
asyncio.run(main())
