import asyncio
from pathlib import Path
import edge_tts
TEXTS={
105:"Course adviser. Community College, how can I help? Applicant. I want to enrol in the care assistant course. Adviser. It begins on the fourteenth of September and lasts a fortnight. Classes run from nine thirty until three. Applicant. Is experience a prerequisite? Adviser. No, but applicants must be at least eighteen and proficient in everyday English. The fee is two hundred and forty pounds, including a first-aid bandage kit. Applicant. Can I pay later? Adviser. A sixty-pound deposit is due on Friday. If you withdraw after the course begins, you forfeit it. Please bring photo identification and your completed health form to reception.",
106:"Before using any pesticide, read the label and confirm that your training remains valid. Store chemicals in the locked inorganic-material cabinet, never beside animal feed or manure. Wear gloves, a protective apron and eye protection. Do not spray during strong wind, because droplets may diffuse beyond the field and endanger nearby homes. Meteorology updates are posted at seven each morning. If a container ruptures, keep people away, place absorbent material around the puddle and call the supervisor. Never inhale fumes or wash residue into a drain. Record the product, quantity, location and time meticulously before leaving.",
107:"Tutor. Your project asks whether simpler council letters improve comprehension. Hana. We will compare the current letter, which contains legal jargon, with a lucid version. Omar. Participants read one version and summarize the action required. Tutor. Good, but do not equate literacy with intelligence. Include adults with varied education and record whether English is their first language. Hana. We can add subtitles to the video instructions. Tutor. Yes, and test whether those subtitles help rather than assuming they do. Omar. We plan sixty participants. Tutor. That is manageable, but a homogeneous sample would mislead you. Recruit through several community groups and explain that the task measures the document, not personal aptitude.",
108:"Coastal wetlands encompass mudflats, salt marshes and shallow inlets. They nurture fish, birds and marine mammals, while vegetation can hamper waves before they injure homes. Yet many wetlands have been degraded by drainage, pesticide runoff and stagnant channels. Restoration may dismantle obsolete barriers, enlarge tidal passages and allow sediment to accumulate naturally. Its intangible benefits include recreation and cultural identity, but claims require meticulous appraisal. A serene new landscape does not prove ecological recovery. Researchers correlate water quality, plant diversity and animal return over many years. They also examine livelihoods. The most fruitful plans involve residents early, compensate genuine loss and refine management when evidence changes. Long-term benefits can outweigh disruption, but only when restoration strengthens both ecological and social cohesion."
}
async def main():
 out=Path(__file__).resolve().parents[1]/"public"/"audio";out.mkdir(parents=True,exist_ok=True)
 for n,t in TEXTS.items():
  p=out/f"l{n}.mp3"
  if p.exists() and p.stat().st_size>100000: print("skip",p.name);continue
  await edge_tts.Communicate(t,"en-GB-SoniaNeural",rate="-8%").save(str(p));print(p.name,p.stat().st_size)
asyncio.run(main())
