import { IconArrowRight, IconCheck, IconTargetArrow } from "@tabler/icons-react";
import rawVocabularyCalibration from "./content/vocabulary-calibration-current.json";
import rawReadingDifficulty from "./content/reading-course-difficulty-v1.json";
import { curriculum, type CourseLesson } from "./content/course-bank";
import { masteryStats } from "./learning-engine.mjs";
import type { LearningState } from "./product-types";
import { assessmentTrend, gtReadingReadiness, measurementStatus, vocabularyLevel, weakestReadingCategories } from "./ability-profile.mjs";
import "./ability-profile.css";

type DifficultyRecord={lessonId:string;internalLevel:string;longestSentence:{words:number};keyVocabulary:{headword:string;band:string}[]};
const difficultyById=new Map((rawReadingDifficulty.records as DifficultyRecord[]).map(item=>[item.lessonId,item]));
const levelNumber=(value:string)=>Number(value.replace("L",""))||3;

function targetLevel(state:LearningState){
  const reading=state.readingAssessments.at(-1);if(reading)return levelNumber(reading.internalLevel);
  const value=state.vocabularyTests.at(-1)?.vocabulary?.value;if(value)return value<2000?1:value<3000?2:value<4000?3:value<5000?4:value<8000?5:6;
  return Math.max(1,Math.min(6,Math.round(state.skill.reading)));
}

export function AbilityProfile({state,onOpenReading}:{state:LearningState;onOpenReading:()=>void}){
  const stats=masteryStats(state.lexiconProgress);const accuracy=state.attempts?Math.round(state.correct/state.attempts*100):0;
  const latestVocabulary=state.vocabularyTests.at(-1);const latestReading=state.readingAssessments.at(-1);const vocabulary=latestVocabulary?.vocabulary;const vocabularyStage=vocabularyLevel(vocabulary?.value);
  const vocabularyTrend=assessmentTrend(state.vocabularyTests.filter(item=>item.vocabulary).map(item=>({...item,trendValue:item.vocabulary!.value})),"trendValue");
  const readingTrend=assessmentTrend(state.readingAssessments,"internalReadingValue");const readiness=gtReadingReadiness(latestReading);const measurement=measurementStatus(state.measurementSessions,rawVocabularyCalibration);const weaknesses=weakestReadingCategories(latestReading?.weaknessProfile,3);const target=targetLevel(state);const completed=new Set(state.completedLessons);
  const recommendations=curriculum.filter(lesson=>lesson.skill==="reading").map(lesson=>{const profile=difficultyById.get(lesson.id);if(!profile)return null;const level=levelNumber(profile.internalLevel);if(Math.abs(level-target)>1)return null;const primary=weaknesses[0]?.category;let score=(completed.has(lesson.id)?-4:3)-Math.abs(level-target)*4+(level===target+1?2:0);if((primary==="mainIdea"||primary==="inference")&&lesson.section.includes("3"))score+=5;if(primary==="locating"&&(lesson.section.includes("1")||lesson.section.includes("2")))score+=5;if(primary==="vocabulary"&&profile.keyVocabulary.length)score+=4;if(primary==="sentence"&&profile.longestSentence.words>=24)score+=4;return{lesson,profile,score,reason:level===target+1?"略高一级，用于挑战":level===target?"与你当前能力相近":"相邻难度，用于巩固"};}).filter(Boolean).sort((a,b)=>b!.score-a!.score).slice(0,6) as {lesson:CourseLesson;profile:DifficultyRecord;score:number;reason:string}[];
  const history=[...state.vocabularyTests.map(item=>({date:item.completedAt,type:"词汇 CAT",result:item.vocabulary?`约 ${item.vocabulary.value.toLocaleString("zh-CN")} 词族`:item.broadBand??"宽层级",interval:item.vocabulary?`${item.vocabulary.low.toLocaleString("zh-CN")}–${item.vocabulary.high.toLocaleString("zh-CN")}`:item.interval?`${item.interval.lowBand}–${item.interval.highBand}`:"未形成区间",confidence:item.confidence?.label??"未标注",coverage:`${item.sampleSize} 题`})),...state.readingAssessments.map(item=>({date:item.completedAt,type:"阅读 CAT",result:`${item.internalReadingValue}L · ${item.internalLevel}`,interval:`${item.interval.low}L–${item.interval.high}L`,confidence:item.confidence.label,coverage:`${item.passageCount} 篇 · ${item.sampleSize} 题`}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,12);
  return <section className="lesson-content progress-page ability-profile-page"><div className="lesson-kicker">综合能力结果 · 测评、诊断和学习回流</div><h1>能力结果</h1><p className="ability-intro">这里把词汇接受性、阅读实验分层和 IELTS General Training 阅读准备趋势放在一起。所有结论只来自你的真实作答。</p>
    <div className="ability-axis-grid"><article className="ability-axis"><span>接受性词汇</span><strong>{vocabulary?`约 ${vocabulary.value.toLocaleString("zh-CN")} 词族`:latestVocabulary?.broadBand??"尚未精测"}</strong><em>{vocabularyStage?.label??"完成词汇 CAT 后建立基线"}</em><small>{vocabulary?`90% 区间 ${vocabulary.low.toLocaleString("zh-CN")}–${vocabulary.high.toLocaleString("zh-CN")}`:"不使用中文快测或 Yes/No 路由计分"}</small><div className="trend">{vocabularyTrend.label}{vocabularyTrend.delta?` ${vocabularyTrend.delta>0?"+":""}${vocabularyTrend.delta.toLocaleString("zh-CN")}`:""}</div></article><article className="ability-axis"><span>阅读能力</span><strong>{latestReading?`${latestReading.internalReadingValue}L · ${latestReading.internalLevel}`:"尚未测量"}</strong><em>{latestReading?`90% 区间 ${latestReading.interval.low}L–${latestReading.interval.high}L`:"完成阅读 CAT 后建立基线"}</em><small>{latestReading?`${latestReading.passageCount} 篇、${latestReading.sampleSize} 题，可信度 ${latestReading.confidence.label}`:"由原创功能短文和连续篇章测量"}</small><div className="trend">{readingTrend.label}{readingTrend.delta?` ${readingTrend.delta>0?"+":""}${readingTrend.delta}L`:""}</div></article><article className="ability-axis"><span>IELTS GT 阅读训练趋势</span><strong>{readiness.label}</strong><em>{readiness.detail}</em><small>这是训练准备度，不是 IELTS 官方分数，也不把词汇量直接换算成 Band。</small><div className="trend">目标：稳定处理生活、工作和 Section 3 长文</div></article></div>
    <p className="ability-disclaimer">内部 L 值和 L1–L6 均为本产品实验指标，不是 MetaMetrics 认证；IELTS GT 准备度是学习路线提示，不是官方成绩预测。</p>
    <section className="ability-section"><div className="ability-section-heading"><h2>当前阅读弱点</h2><span>错题已进入错因档案并生成训练方向</span></div>{weaknesses.length?<div className="weakness-grid">{weaknesses.map(item=><article className="weakness-card" key={item.category}><span>错 {item.wrong}/{item.total}</span><strong>{item.label}</strong><p>{item.training}</p></article>)}</div>:<div className="empty-state"><IconCheck/><strong>{latestReading?"本轮没有形成集中弱点":"完成阅读 CAT 后生成五类错因"}</strong></div>}</section>
    <section className="ability-section"><div className="ability-section-heading"><h2>接下来读什么</h2><span>优先当前水平与略高一级，避开长期过易或过难</span></div><div className="recommendation-grid">{recommendations.map(({lesson,profile,reason})=><article className="recommendation-card" key={lesson.id}><span>{lesson.section} · 实验 {profile.internalLevel}</span><strong>{lesson.title}</strong><em>{reason}</em><p>{lesson.focus}{weaknesses[0]?` · 针对 ${weaknesses[0].label}`:""}</p></article>)}</div><div className="recommendation-actions"><button className="primary-button" onClick={onOpenReading}>进入推荐阅读课程<IconArrowRight/></button></div></section>
    <section className="ability-section"><div className="ability-section-heading"><h2>测评历史</h2><span>只展示区间、可信度和覆盖，不使用伪精确进度</span></div>{history.length?<div className="history-table">{history.map((item,index)=><div className="history-row" key={`${item.type}-${item.date}-${index}`}><span>{new Date(item.date).toLocaleDateString("zh-CN")}</span><strong>{item.type}</strong><strong>{item.result}</strong><span>{item.interval} · {item.confidence} · {item.coverage}</span></div>)}</div>:<div className="empty-state"><IconTargetArrow/><strong>尚无正式测评历史</strong></div>}</section>
    <section className="ability-section"><div className="ability-section-heading"><h2>真实数据与模型</h2><span>样本门禁决定是否启用实证 2PL</span></div><div className="measurement-status-card"><div><span>当前模型</span><strong>{measurement.model}</strong><small>{measurement.note}</small></div><div><span>词汇测评</span><strong>{measurement.vocabularySessions} 次</strong><small>完成后自动记录逐题响应</small></div><div><span>阅读测评</span><strong>{measurement.readingSessions} 次</strong><small>保留题目版本和反应时间</small></div><div><span>原始响应</span><strong>{measurement.responses} 条</strong><small>不含姓名、邮箱、录音或答案文本</small></div></div></section>
    <section className="ability-section"><div className="ability-section-heading"><h2>日常学习基线</h2><span>训练数据，不混入标准化测评</span></div><div className="metrics expanded"><div><span>词库已接触</span><strong>{stats.introduced} 条</strong></div><div><span>综合掌握</span><strong>{stats.average}%</strong></div><div><span>回忆正确率</span><strong>{accuracy}%</strong></div><div><span>课程完成</span><strong>{state.completedLessons.length}/{curriculum.length}</strong></div></div></section>
  </section>;
}
