import { useEffect, useMemo, useState } from "react";
import { IconArrowLeft,IconArrowRight,IconBook2,IconBrain,IconCalendarEvent,IconCheck,IconClipboardText,IconFlask2,IconHeadphones,IconLanguage,IconLibrary,IconMicrophone,IconPlayerPlay,IconRefresh,IconRobot,IconSearch,IconTargetArrow,IconVolume,IconWriting,IconX } from "@tabler/icons-react";
import { newWords, reviewWords, sentenceChallenge } from "./data";
import { curriculum, skillMeta, type CourseLesson } from "./curriculum";
import rawLexicon from "./content/lexicon.json";
import { scoreRecall } from "./learning-core.mjs";
import { freshState, loadLearningState, saveLearningState } from "./storage";
import type { LearningState, LexiconItem, View } from "./types";

const lexicon = rawLexicon as LexiconItem[];
const steps=[
 {title:"复习旧词",subtitle:"巩固记忆，打好基础",minutes:8,icon:IconBook2,view:"review" as View},
 {title:"新词与词块",subtitle:"理解核心义，搭配运用",minutes:10,icon:IconLanguage,view:"words" as View},
 {title:"句型实验室",subtitle:"看清主干，灵活造句",minutes:10,icon:IconFlask2,view:"sentence" as View},
 {title:"开口任务",subtitle:"真实表达，不怕说错",minutes:10,icon:IconMicrophone,view:"speak" as View}
];
const today=new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",weekday:"short"}).format(new Date());

let activeFixedAudio:HTMLAudioElement|null=null;
function playFixedAudio(path:string,fallback:string){if(activeFixedAudio)activeFixedAudio.pause();const audio=new Audio(path);activeFixedAudio=audio;audio.play().catch(()=>speakEnglish(fallback));}

function speakEnglish(text:string){
 const utterance=new SpeechSynthesisUtterance(text);utterance.lang="en-GB";utterance.rate=.86;utterance.pitch=1;
 const voices=speechSynthesis.getVoices();
 const voice=voices.find(v=>v.lang.toLowerCase()==="en-gb"&&/sonia|libby|ryan|serena|daniel|google uk/i.test(v.name))??voices.find(v=>v.lang.toLowerCase()==="en-gb")??voices.find(v=>v.lang.toLowerCase().startsWith("en"));
 if(voice)utterance.voice=voice;speechSynthesis.cancel();speechSynthesis.speak(utterance);
}

function coachPrompt(view:View,state:LearningState){return `你是我的耐心英语教练。我懂中文、蒙古文和日文，英语基础薄弱，目标是 IELTS General Training 6 分。我正在使用“破壁 IELTS 6”的${view}训练。请先问我卡在哪里，每次只给一级提示；引用我的原句，并把问题分为“影响理解”“影响6分”“只是润色”。当前客观题正确率 ${state.attempts?Math.round(state.correct/state.attempts*100):0}%。`;}

export function App(){
 const [view,setView]=useState<View>("home"); const [state,setState]=useState<LearningState>(freshState()); const [ready,setReady]=useState(false); const [toast,setToast]=useState("");
 useEffect(()=>{loadLearningState().then(s=>{setState(s);setReady(true);});},[]); useEffect(()=>{if(ready)saveLearningState(state);},[state,ready]);
 const update=(next:Partial<LearningState>)=>setState(s=>({...s,...next}));
 const completeStep=(n:number,next:View="home")=>{update({completedSteps:[...new Set([...state.completedSteps,n])],lastStudied:new Date().toISOString()});setView(next);};
 const openChat=async()=>{window.open("https://chatgpt.com/","_blank","noopener,noreferrer");try{await navigator.clipboard.writeText(coachPrompt(view,state));setToast("学习上下文已复制，请在 ChatGPT 中粘贴");}catch{setToast("ChatGPT 已打开；浏览器未允许自动复制");}setTimeout(()=>setToast(""),3500);};
 return <div className="app-shell">{toast&&<div className="toast" role="status">{toast}</div>}{view==="home"?<Home state={state} onOpen={setView} onChat={openChat} onReset={()=>setState(freshState())}/>:<Shell view={view} back={()=>setView("home")} chat={openChat}>
  {view==="review"&&<Review state={state} update={update} done={()=>completeStep(0,"words")}/>} {view==="words"&&<WordLab state={state} update={update} done={()=>completeStep(1,"sentence")}/>} {view==="sentence"&&<SentenceLab done={()=>completeStep(2,"speak")}/>} {view==="speak"&&<QuickSpeak done={()=>completeStep(3)}/>} {view==="courses"&&<CourseHub state={state} update={update}/>} {view==="library"&&<Library/>} {view==="progress"&&<Progress state={state}/>} {view==="errors"&&<Errors state={state}/>}</Shell>}</div>;
}

function Home({state,onOpen,onChat,onReset}:{state:LearningState;onOpen:(v:View)=>void;onChat:()=>void;onReset:()=>void}){
 const p=state.completedSteps.length/4, completed=state.completedLessons.length;
 return <main className="home"><header className="brand-row"><button className="brand"><span className="brand-mark"><IconBook2 size={28}/></span><span><strong>破壁 IELTS 6</strong><small>IELTS GENERAL TRAINING</small></span></button><div className="header-actions"><button className="text-button library-header-link" onClick={()=>onOpen("library")}><IconLibrary size={19}/>词库 1,000 条</button><button className="text-button" onClick={onChat}><IconRobot size={19}/>向 ChatGPT 提问</button><span className="date"><IconCalendarEvent size={19}/>{today}</span></div></header>
 <section className="hero-grid"><div className="intro"><p className="eyebrow">每日 30–45 分钟 · 本地保存 · 稳步提升</p><h1>今天学什么</h1><div className="motto">英语难不倒我</div></div><div className="score-panel"><div className="score-copy"><span>当前水平<strong>4.0</strong></span><IconArrowRight/><span>目标分数<strong className="target">6.0</strong></span></div><div className="score-track"><span style={{width:`${Math.max(26,p*100)}%`}}/></div><p>{p?`今天已完成 ${state.completedSteps.length}/4 步`:"你的进步，正在发生"}</p></div></section>
 <section className="path-section"><div className="section-heading"><h2>今天的学习路径</h2><span>预计 38 分钟</span></div><div className="learning-path">{steps.map((s,i)=>{const I=s.icon,d=state.completedSteps.includes(i);return <button key={s.title} className={`path-step ${d?"done":""}`} onClick={()=>onOpen(s.view)}><span className="step-number">{d?<IconCheck size={16}/>:i+1}</span><span className="step-icon"><I size={31}/></span><span className="step-copy"><strong>{s.title}</strong><small>{s.subtitle}</small><em>{s.minutes} 分钟</em></span></button>;})}</div><button className="primary-cta" onClick={()=>onOpen(steps.find((_,i)=>!state.completedSteps.includes(i))?.view??"review")}>{state.completedSteps.length===4?"再练一轮":"开始今天训练"}<IconArrowRight/></button><p className="cta-note">系统会根据回答调整难度，不要求一次完美</p></section>
 <section className="course-overview"><div className="section-heading"><h2>General Training 四项课程</h2><span>22 课 · 全部原创练习</span></div><div className="skill-cards">{Object.entries(skillMeta).map(([key,m])=>{const icons={listening:IconHeadphones,reading:IconBook2,writing:IconWriting,speaking:IconMicrophone};const I=icons[key as keyof typeof icons];const done=state.completedLessons.filter(id=>id.startsWith(key[0])).length;return <button key={key} onClick={()=>onOpen("courses")}><I/><strong>{m.label}</strong><span>{m.description}</span><em>{done}/{m.count} 课完成</em></button>;})}</div><div className="course-actions"><button className="outline-button" onClick={()=>onOpen("library")}><IconLibrary/>打开 1,000 词库</button><button className="primary-button" onClick={()=>onOpen("courses")}>进入四项课程<IconArrowRight/></button></div></section>
 <section className="review-strip"><div className="review-count"><IconClipboardText/><span>待复习<strong>{state.dueReviews}</strong>个</span></div><div><strong>及时复习，记得更牢。</strong><p>错词会回来，不用死记硬背。</p></div><button className="outline-button" onClick={()=>onOpen("review")}>去复习<IconArrowRight/></button></section>
 <footer className="home-footer"><button onClick={()=>onOpen("progress")}><IconTargetArrow/>能力进度</button><button onClick={()=>onOpen("errors")}><IconBrain/>错因档案</button><button onClick={onReset}><IconRefresh/>重置本地进度</button></footer></main>;
}

function Shell({view,back,chat,children}:{view:View;back:()=>void;chat:()=>void;children:React.ReactNode}){const labels:Record<View,string>={home:"今日训练",review:"主动回忆",words:"词义实验室",sentence:"句型实验室",speak:"开口任务",courses:"四项课程",library:"1,000 词库",progress:"能力进度",errors:"错因档案"};return <main className="lesson-page"><header className="lesson-header"><button className="icon-button" onClick={back} aria-label="返回首页"><IconArrowLeft/></button><div><small>破壁 IELTS 6</small><strong>{labels[view]}</strong></div><button className="text-button" onClick={chat}><IconRobot/>问 ChatGPT</button></header><div className="lesson-progress"><span className="active-2"/></div>{children}</main>;}

function Review({state,update,done}:{state:LearningState;update:(n:Partial<LearningState>)=>void;done:()=>void}){const index=Math.min(state.reviewIndex,reviewWords.length-1),item=reviewWords[index];const [answer,setAnswer]=useState(""),[hint,setHint]=useState(0),[feedback,setFeedback]=useState<{correct:boolean;label:string}|null>(null);const submit=()=>{const r=scoreRecall(answer,item.word,hint);setFeedback(r);update({attempts:state.attempts+1,correct:state.correct+(r.correct?1:0),dueReviews:Math.max(0,state.dueReviews-(r.correct?1:0)),errorLog:r.correct?state.errorLog:[...state.errorLog,{id:crypto.randomUUID(),prompt:item.cue,answer,expected:item.word,createdAt:new Date().toISOString()}]});};const next=()=>{if(index>=4)return done();update({reviewIndex:index+1});setAnswer("");setHint(0);setFeedback(null);};return <section className="lesson-content recall-card"><div className="lesson-kicker">第 {index+1} / 5 题 · 先从记忆里找</div><h1>{item.cue}</h1><p>写出最合适的英语单词</p><label className="answer-field"><span>你的答案</span><input autoFocus value={answer} onChange={e=>setAnswer(e.target.value)} disabled={!!feedback}/></label>{!feedback?<div className="answer-actions"><button className="hint-button" onClick={()=>setHint(Math.min(2,hint+1))}>给一点提示</button><button className="primary-button" disabled={!answer.trim()} onClick={submit}>检查答案</button></div>:<div className={`feedback ${feedback.correct?"success":"error"}`}>{feedback.correct?<IconCheck/>:<IconX/>}<div><strong>{feedback.label}</strong><p>答案：<b>{item.word}</b> {item.phonetic} · {item.meaning}</p><p>{item.example}</p></div><button className="primary-button" onClick={next}>下一题<IconArrowRight/></button></div>}{hint>0&&!feedback&&<div className="hint-box">{hint===1?`首字母是 ${item.word[0].toUpperCase()}`:`常见搭配：${item.collocation}`}</div>}</section>;}

function WordLab({state,update,done}:{state:LearningState;update:(n:Partial<LearningState>)=>void;done:()=>void}){const index=Math.min(state.wordIndex,newWords.length-1),item=newWords[index];const [shown,setShown]=useState(false);const next=()=>{if(index===newWords.length-1)return done();update({wordIndex:index+1});setShown(false);};return <section className="lesson-content word-lab"><div className="lesson-kicker">新词 {index+1} / {newWords.length} · 先理解，再记忆</div><div className="word-heading"><div><h1>{item.word}</h1><p>{item.phonetic} · {item.part}</p></div><button className="round-button" onClick={()=>speakEnglish(`${item.word}. ${item.example}`)}><IconVolume/></button></div><div className="meaning-block"><span>核心概念</span><strong>{item.meaning}</strong><p>{item.example}</p></div><div className="word-grid"><div><span>常见搭配</span><strong>{item.collocation}</strong></div><div><span>可靠联想</span><strong>{item.japanese??"先用中文建立概念"}</strong></div></div><div className="recall-check"><p>遮住解释：你能说出例句中的意思吗？</p>{!shown?<button className="outline-button" onClick={()=>setShown(true)}>想过了，揭晓</button>:<div className="reveal"><IconCheck/>眼熟不算会，明天还要独立想起。</div>}</div><button className="primary-button wide" disabled={!shown} onClick={next}>下一个<IconArrowRight/></button></section>;}

function SentenceLab({done}:{done:()=>void}){const [choice,setChoice]=useState("");const ok=choice===sentenceChallenge.correct;return <section className="lesson-content sentence-lab"><div className="lesson-kicker">看懂结构，不做逐词翻译</div><h1>一句话是怎样站起来的？</h1><div className="sentence-parts">{sentenceChallenge.segments.map((p,i)=><div key={p.text} className={`part part-${i}`}><span>{p.role}</span><strong>{p.text}</strong></div>)}</div><div className="challenge"><p>{sentenceChallenge.prompt}</p><div className="choice-row">{sentenceChallenge.options.map(o=><button className={choice===o?"selected":""} key={o} onClick={()=>setChoice(o)}>{o}</button>)}</div>{choice&&<div className={`feedback-line ${ok?"success":"error"}`}>{ok?<IconCheck/>:<IconX/>}<span>{ok?sentenceChallenge.explanation:"名词 appointment 前需要哪一种词？"}</span></div>}</div><button className="primary-button wide" disabled={!ok} onClick={done}>进入开口任务<IconArrowRight/></button></section>;}

function QuickSpeak({done}:{done:()=>void}){const prompt="I would like to confirm my appointment for tomorrow.";const [text,setText]=useState(""),[listening,setListening]=useState(false);const score=useMemo(()=>["confirm","appointment","tomorrow"].filter(w=>text.toLowerCase().includes(w)).length,[text]);const record=()=>{const R=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!R)return;const r=new R();r.lang="en-GB";r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onresult=(e:any)=>setText(e.results[0][0].transcript);r.start();};const supported="webkitSpeechRecognition" in window||"SpeechRecognition" in window;return <section className="lesson-content speak-lab"><div className="lesson-kicker">今天至少开口一次</div><h1>确认明天的预约</h1><button className="listen-line" onClick={()=>playFixedAudio("./audio/quick-speak.mp3",prompt)}><IconPlayerPlay/><span>{prompt}</span></button>{supported?<button className={`record-button ${listening?"recording":""}`} onClick={record}><IconMicrophone/><span>{listening?"正在听…":"按下开始说"}</span></button>:<label className="answer-field"><span>输入你说的话</span><input value={text} onChange={e=>setText(e.target.value)}/></label>}{text&&<div className="transcript"><span>我听到</span><strong>“{text}”</strong><p>关键词 {score}/3</p></div>}<button className="primary-button wide" disabled={score<2} onClick={done}>完成今天训练<IconCheck/></button></section>;}

function CourseHub({state,update}:{state:LearningState;update:(n:Partial<LearningState>)=>void}){const [skill,setSkill]=useState<CourseLesson["skill"]>("listening"),[selected,setSelected]=useState<CourseLesson|null>(null);if(selected)return <CoursePlayer lesson={selected} done={()=>{update({completedLessons:[...new Set([...state.completedLessons,selected.id])],lastStudied:new Date().toISOString()});setSelected(null);}} back={()=>setSelected(null)}/>;return <section className="lesson-content course-hub"><div className="lesson-kicker">严格按 General Training 结构 · 题目为原创训练内容</div><h1>听说读写课程</h1><div className="skill-tabs">{Object.entries(skillMeta).map(([k,m])=><button key={k} className={skill===k?"selected":""} onClick={()=>setSkill(k as CourseLesson["skill"])}>{m.label}<span>{m.count} 课</span></button>)}</div><div className="lesson-list">{curriculum.filter(x=>x.skill===skill).map((l,i)=><button key={l.id} onClick={()=>setSelected(l)}><span className="lesson-index">{state.completedLessons.includes(l.id)?<IconCheck/>:i+1}</span><span><em>{l.section} · {l.level}</em><strong>{l.title}</strong><small>{l.focus}</small></span><b>{l.minutes} 分钟<IconArrowRight/></b></button>)}</div></section>;}

function CoursePlayer({lesson,done,back}:{lesson:CourseLesson;done:()=>void;back:()=>void}){const [question,setQuestion]=useState(0),[choice,setChoice]=useState(""),[draft,setDraft]=useState(""),[spoken,setSpoken]=useState(""),[listen,setListen]=useState(false),[audioError,setAudioError]=useState(false);const current=lesson.questions?.[question];const correct=choice===current?.answer;const fallbackAudio=()=>{if(lesson.text)speakEnglish(lesson.text);};const record=()=>{const R=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!R)return;const r=new R();r.lang="en-GB";r.continuous=true;r.onstart=()=>setListen(true);r.onend=()=>setListen(false);r.onresult=(e:any)=>setSpoken(Array.from(e.results).map((x:any)=>x[0].transcript).join(" "));r.start();};return <section className="lesson-content course-player"><button className="back-inline" onClick={back}><IconArrowLeft/>返回课程目录</button><div className="lesson-kicker">{lesson.section} · {lesson.minutes} 分钟 · {lesson.focus}</div><h1>{lesson.title}</h1>
 {lesson.skill==="listening"&&<><div className="audio-card"><div><IconHeadphones/><span><strong>标准英式录音</strong><small>女声 Sonia · 男声 Ryan · 语速 -8%</small></span></div><audio controls preload="metadata" src={`./audio/${lesson.id}.mp3`} onCanPlay={()=>setAudioError(false)} onError={()=>setAudioError(true)}>你的浏览器不支持音频播放。</audio>{audioError&&<div className="audio-error"><IconX/><span>固定录音加载失败，请检查网络或刷新页面。</span><button onClick={fallbackAudio}>临时备用朗读</button></div>}</div><details><summary>练完后查看听力原文</summary><p className="source-text">{lesson.text}</p></details></>}
 {lesson.skill==="reading"&&<article className="reading-passage">{lesson.text?.split("\n\n").map(p=><p key={p}>{p}</p>)}</article>}
 {current&&<div className="question-card"><span>第 {question+1}/{lesson.questions?.length} 题</span><h2>{current.prompt}</h2><div className="option-list">{current.options.map(o=><button key={o} className={choice===o?(correct?"correct":"wrong"):""} onClick={()=>setChoice(o)} disabled={!!choice}>{o}</button>)}</div>{choice&&<div className={`feedback-line ${correct?"success":"error"}`}>{correct?<IconCheck/>:<IconX/>}<span>{correct?"答对了。":`正确答案：${current.answer}。`} {current.explanation}</span></div>}<button className="primary-button wide" disabled={!choice} onClick={()=>{if(question<(lesson.questions?.length??1)-1){setQuestion(question+1);setChoice("");}else done();}}>{question<(lesson.questions?.length??1)-1?"下一题":"完成本课"}<IconArrowRight/></button></div>}
 {lesson.skill==="writing"&&<><div className="writing-task"><strong>{lesson.task}</strong><ul>{lesson.bullets?.map(x=><li key={x}>{x}</li>)}</ul></div><label className="writing-area"><span>在这里写作 · 当前 {draft.trim()?draft.trim().split(/\s+/).length:0} 词</span><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Start writing here..."/></label><Checklist items={lesson.checklist??[]}/><button className="primary-button wide" disabled={draft.trim().split(/\s+/).length<30} onClick={done}>保存草稿并完成</button></>}
 {lesson.skill==="speaking"&&<><div className="speaking-prompts">{lesson.task&&<h2>{lesson.task}</h2>}<ul>{lesson.bullets?.map(x=><li key={x}>{x}</li>)}</ul>{lesson.prompts?.map(p=><p key={p}>{p}</p>)}</div>{"webkitSpeechRecognition" in window||"SpeechRecognition" in window?<button className={`record-button ${listen?"recording":""}`} onClick={record}><IconMicrophone/><span>{listen?"正在记录，完成后停顿…":"开始回答"}</span></button>:<label className="answer-field"><span>浏览器不支持识别，请输入回答</span><input value={spoken} onChange={e=>setSpoken(e.target.value)}/></label>}{spoken&&<div className="transcript"><span>转写</span><strong>{spoken}</strong><p>说出了 {spoken.trim().split(/\s+/).length} 词。先保证意思清楚，再追求漂亮。</p></div>}<button className="primary-button wide" disabled={spoken.trim().split(/\s+/).length<5} onClick={done}>完成本课</button></>}
 </section>;}

function Checklist({items}:{items:string[]}){const [checked,setChecked]=useState<string[]>([]);return <div className="checklist"><strong>6 分自检</strong>{items.map(x=><label key={x}><input type="checkbox" checked={checked.includes(x)} onChange={()=>setChecked(c=>c.includes(x)?c.filter(v=>v!==x):[...c,x])}/>{x}</label>)}</div>;}

function Library(){
 const PAGE_SIZE=50;
 const [query,setQuery]=useState(""),[kind,setKind]=useState("all"),[page,setPage]=useState(1);
 const filtered=useMemo(()=>lexicon.filter(x=>(kind==="all"||x.kind===kind)&&(!query||`${x.term}${x.meaning}`.toLowerCase().includes(query.toLowerCase()))),[query,kind]);
 const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)),current=Math.min(page,pages);
 const list=filtered.slice((current-1)*PAGE_SIZE,current*PAGE_SIZE);
 const changeQuery=(value:string)=>{setQuery(value);setPage(1);};
 const changeKind=(value:string)=>{setKind(value);setPage(1);};
 const go=(next:number)=>{setPage(next);window.scrollTo({top:0,behavior:"smooth"});};
 return <section className="lesson-content library-page">
  <div className="library-total" aria-label="词库总数"><strong>{lexicon.length.toLocaleString()}</strong><span>条离线词库</span><small>120 个词块 + 880 个单词</small></div>
  <div className="lesson-kicker">可以逐页浏览全部内容，不再只显示前 80 条</div><h1>1,000 个单词与词块</h1>
  <div className="library-tools"><label><IconSearch/><input value={query} onChange={e=>changeQuery(e.target.value)} placeholder="搜英文或中文"/></label><select value={kind} onChange={e=>changeKind(e.target.value)}><option value="all">全部 1,000</option><option value="chunk">词块 120</option><option value="word">单词 880</option></select></div>
  <p className="result-count">找到 {filtered.length} 条 · 第 {current}/{pages} 页 · 本页 {list.length} 条</p>
  <div className="lexicon-grid">{list.map((x,index)=><article key={x.id}><div><em>#{(current-1)*PAGE_SIZE+index+1} · {x.kind==="chunk"?"词块":"单词"}</em><button onClick={()=>speakEnglish(x.term)}><IconVolume/></button></div><h2>{x.term}</h2><small>{x.phonetic}</small><p>{x.meaning}</p>{x.example&&<blockquote>{x.example}</blockquote>}</article>)}</div>
  <nav className="library-pagination" aria-label="词库分页"><button disabled={current===1} onClick={()=>go(current-1)}><IconArrowLeft/>上一页</button><span>第 <strong>{current}</strong> 页，共 {pages} 页</span><button disabled={current===pages} onClick={()=>go(current+1)}>下一页<IconArrowRight/></button></nav>
 </section>;
}

function Progress({state}:{state:LearningState}){const a=state.attempts?Math.round(state.correct/state.attempts*100):0;return <section className="lesson-content progress-page"><div className="lesson-kicker">能力地图 · 真实训练数据</div><h1>离 6 分还有多远？</h1><div className="skill-list">{Object.entries(state.skill).map(([n,v])=><div key={n}><span>{({listening:"听力",reading:"阅读",writing:"写作",speaking:"口语"} as any)[n]}</span><progress max="6" value={v}/><strong>{v.toFixed(1)}</strong></div>)}</div><div className="metrics"><div><span>回忆正确率</span><strong>{a}%</strong></div><div><span>课程完成</span><strong>{state.completedLessons.length}/22</strong></div><div><span>待复习</span><strong>{state.dueReviews}</strong></div></div></section>;}
function Errors({state}:{state:LearningState}){return <section className="lesson-content errors-page"><div className="lesson-kicker">错误不是污点，是下一步路线</div><h1>错因档案</h1>{state.errorLog.length===0?<div className="empty-state"><IconBrain/><strong>暂时没有错题记录</strong><p>错误会自动回到复习队列。</p></div>:<div className="error-list">{state.errorLog.slice().reverse().map(e=><div key={e.id}><span>{e.prompt}</span><p>你的答案：{e.answer||"未作答"}</p><strong>正确答案：{e.expected}</strong></div>)}</div>}</section>;}
