export type ChoiceQuestion = { prompt: string; options: string[]; answer: string; explanation: string };
export type CourseLesson = {
  id: string; skill: "listening" | "reading" | "writing" | "speaking"; section: string;
  title: string; level: string; minutes: number; focus: string; text?: string;
  questions?: ChoiceQuestion[]; task?: string; bullets?: string[]; checklist?: string[];
  prompts?: string[]; keywords?: string[];
};

const q = (prompt: string, options: string[], answer: string, explanation: string): ChoiceQuestion => ({ prompt, options, answer, explanation });

export const curriculum: CourseLesson[] = [
  { id:"l1",skill:"listening",section:"Part 1",title:"电话预约社区诊所",level:"基础",minutes:12,focus:"姓名、日期、时间、拼写",
    text:"Receptionist: Good morning, Green Street Clinic. How can I help? Caller: I'd like to make an appointment with a doctor. Receptionist: Certainly. Could I take your name? Caller: Yes, it's Naran Bat — N-A-R-A-N, B-A-T. Receptionist: Thank you. Dr Evans is available on Thursday the eighteenth at ten thirty, or Friday at two fifteen. Caller: Thursday morning, please. Receptionist: Fine. Please arrive ten minutes early and bring photo identification.",
    questions:[q("预约是哪一天？",["周四 18 日","周五 18 日","周四 28 日"],"周四 18 日","先抓星期，再核对日期。"),q("预约时间是？",["10:13","10:30","2:15"],"10:30","thirty 是 30，不是 thirteen。"),q("需要携带什么？",["保险单","照片身份证件","现金"],"照片身份证件","结尾的 bring photo identification 是直接答案。")] },
  { id:"l2",skill:"listening",section:"Part 2",title:"图书馆欢迎介绍",level:"基础",minutes:14,focus:"地点、规则、时间表",
    text:"Welcome to Westfield Library. The ground floor has returns and new books. Computers are on the first floor, beside the study room. Members may use a computer for one hour. The children's area closes at six, but the main library remains open until eight from Monday to Thursday. On Friday, the whole building closes at five thirty.",
    questions:[q("电脑在哪里？",["底层入口旁","一楼自习室旁","儿童区内"],"一楼自习室旁","beside the study room 给出位置。"),q("周一主馆几点关闭？",["5:30","6:00","8:00"],"8:00","注意 children's area 和 main library 的对比。"),q("每次可用电脑多久？",["30 分钟","1 小时","2 小时"],"1 小时","one hour 是时长。")] },
  { id:"l3",skill:"listening",section:"Part 3",title:"两人讨论职业培训",level:"进阶",minutes:16,focus:"观点、决定、转折",
    text:"Mina: I first chose the customer service course because it was cheaper. Ken: But it clashes with your Friday shift. Mina: Exactly. So I've changed to workplace communication on Tuesday evenings. It costs twenty pounds more, but my manager says the company may pay half. Ken: That sounds useful. Are you still doing the online safety module? Mina: Yes. It's compulsory, and I must finish it before the end of May.",
    questions:[q("Mina 最终选择什么课？",["客户服务","职场沟通","在线安全"],"职场沟通","changed to 表示最终决定。"),q("公司可能支付多少？",["全部","一半","20 英镑"],"一半","pay half 是比例，不是价格。"),q("在线安全模块为什么要完成？",["最便宜","经理推荐","它是必修"],"它是必修","compulsory 表示强制／必修。 ")] },
  { id:"l4",skill:"listening",section:"Part 4",title:"社区花园讲座",level:"进阶",minutes:18,focus:"笔记填空、因果与例子",
    text:"Community gardens do more than produce food. First, they turn unused land into shared space. Second, regular gardening can reduce stress and provide gentle exercise. Our survey found that most new members joined to meet neighbours, not to save money. However, water use remains a concern. The project therefore collects rainwater from the community hall roof and uses wood chips to keep moisture in the soil.",
    questions:[q("多数新成员参加的主要原因？",["省钱","认识邻居","获得食物"],"认识邻居","not to save money 排除干扰项。"),q("项目如何收集水？",["从屋顶收集雨水","从河流抽水","购买瓶装水"],"从屋顶收集雨水","therefore 后面给解决办法。"),q("木屑有什么作用？",["吸引昆虫","保持土壤水分","标记道路"],"保持土壤水分","keep moisture 是保持水分。 ")] },

  { id:"r1",skill:"reading",section:"Section 1",title:"公交临时通知",level:"基础",minutes:10,focus:"公告中的时间与例外",
    text:"ROUTE 18 WEEKEND CHANGE — From Saturday 6 April, Route 18 will not stop at Market Square because of road repairs. Passengers should use King Street, a four-minute walk away. Weekday services are unchanged. The normal route returns on Monday 22 April.",
    questions:[q("变化从何时开始？",["4 月 6 日星期六","4 月 18 日星期一","4 月 22 日星期六"],"4 月 6 日星期六","From 后面是开始时间。"),q("乘客应去哪一站？",["Market Square","King Street","Road Repairs"],"King Street","should use 指示替代站。"),q("哪类服务不受影响？",["周末","工作日","夜间"],"工作日","unchanged 表示没有变化。")] },
  { id:"r2",skill:"reading",section:"Section 1",title:"公寓租赁广告",level:"基础",minutes:12,focus:"筛选条件、费用、限制",
    text:"BRIGHT ROOM IN SHARED FLAT — £620 per month, including water and internet. Electricity is separate. Ten minutes by bus from the city centre. Available from 1 September. The room is furnished. No smoking. A deposit equal to one month's rent is required. Minimum stay: six months.",
    questions:[q("房租包含什么？",["电费和水费","水费和网络","所有账单"],"水费和网络","including 后列出已包含项目。"),q("押金是多少？",["£310","£620","£1,240"],"£620","equal to one month's rent。"),q("最短租期？",["1 个月","6 个月","12 个月"],"6 个月","minimum stay 是最短停留期。 ")] },
  { id:"r3",skill:"reading",section:"Section 2",title:"新员工安全手册",level:"基础",minutes:14,focus:"义务、禁止与流程",
    text:"All new warehouse employees must attend safety training before starting independent work. Protective shoes are required in storage areas and are provided by the company. Report damaged equipment to the shift supervisor immediately; do not attempt repairs yourself. In an emergency, leave by the nearest marked exit and meet beside the north car park. Do not return until a manager gives permission.",
    questions:[q("何时必须完成安全培训？",["独立工作之前","工作一月后","设备损坏后"],"独立工作之前","before starting independent work 是期限。"),q("谁提供防护鞋？",["员工","公司","主管个人"],"公司","provided by the company 是被动结构。"),q("发现设备损坏应怎么做？",["自己修理","立即报告主管","放到停车场"],"立即报告主管","分号后的 do not 排除自行修理。 ")] },
  { id:"r4",skill:"reading",section:"Section 2",title:"弹性工作申请政策",level:"进阶",minutes:16,focus:"条件、审批与申诉",
    text:"Employees who have completed 26 weeks of service may request a change to their working hours. Requests must be submitted in writing and should explain how the proposed change might affect the team. A manager will normally respond within 21 days. A request may be refused for a clear business reason, such as an inability to reorganise work. Employees may appeal within seven days of receiving the decision.",
    questions:[q("申请前需工作多久？",["7 周","21 周","26 周"],"26 周","completed 26 weeks 是资格条件。"),q("申请必须采用什么形式？",["书面","电话","面对面"],"书面","submitted in writing。"),q("收到决定后多久内可申诉？",["7 天","21 天","26 天"],"7 天","appeal within seven days。 ")] },
  { id:"r5",skill:"reading",section:"Section 3",title:"通勤方式如何影响城市",level:"进阶",minutes:20,focus:"段落主旨、指代、作者立场",
    text:"When cities try to reduce traffic, they often begin by adding public transport. More buses and trains are important, but availability alone does not change behaviour. People also consider reliability, safety and the distance between a stop and their home. A cheap service that arrives unpredictably may still lose passengers to cars.\n\nSome employers have found that small workplace changes can help. Secure bicycle parking, showers and flexible start times remove practical barriers to cycling. These measures cost less than building roads, although they are not suitable for every worker.\n\nThe most successful plans combine choices rather than presenting one solution as perfect. They make driving less necessary while ensuring that people with limited mobility are not excluded. In this way, transport policy becomes a question of access, not simply a campaign against cars.",
    questions:[q("第一段的主要观点？",["廉价服务一定成功","只有增加班次即可","可用性之外还有其他因素"],"可用性之外还有其他因素","alone does not change behaviour 是中心转折。"),q("these measures 指什么？",["修路","单位提供的骑行支持","购买汽车"],"单位提供的骑行支持","回指前一句的停车、淋浴和弹性时间。"),q("作者支持哪种方案？",["全面禁车","只建铁路","组合多种选择并保障可达性"],"组合多种选择并保障可达性","最后一段明确说 combine choices。 ")] },
  { id:"r6",skill:"reading",section:"Section 3",title:"成年人如何形成学习习惯",level:"进阶",minutes:20,focus:"推断、原因、信息匹配",
    text:"Adult learners often blame a lack of willpower when a study plan fails. Yet the plan itself may be the problem. A goal such as 'improve my English' gives no clear starting action. A smaller instruction — review ten cards after breakfast — links study to an existing routine.\n\nMemory also benefits from effort. Re-reading feels comfortable, but trying to recall an answer before checking it produces a stronger learning signal. Errors during this attempt are useful when correction follows quickly.\n\nFinally, a plan must survive busy days. A ten-minute minimum session keeps the routine alive, while longer sessions can remain optional. Consistency does not mean doing the same amount every day; it means returning before the gap becomes a new habit.",
    questions:[q("模糊目标的问题是什么？",["太容易","没有明确起始动作","需要付费"],"没有明确起始动作","no clear starting action 是直接解释。"),q("哪种方法产生更强学习信号？",["反复阅读","先尝试回忆再核对","跳过错误"],"先尝试回忆再核对","第二段用 but 对比两种方法。"),q("作者怎样理解坚持？",["每天时长完全一样","永远不休息","间隔变成习惯前重新开始"],"间隔变成习惯前重新开始","末句给出作者定义。 ")] },

  { id:"w1",skill:"writing",section:"Task 1 · 正式信",title:"投诉租住房屋供暖",level:"基础",minutes:20,focus:"目的明确、覆盖三点、正式语气",task:"你租住的公寓供暖已坏一周。写信给房屋中介。至少 150 词。",bullets:["说明问题及持续时间","解释它怎样影响你的生活","要求中介采取具体行动"],checklist:["开头直接说明写信目的","三项任务点各有具体信息","使用正式称呼与结尾","检查时态、单复数和拼写"] },
  { id:"w2",skill:"writing",section:"Task 1 · 半正式信",title:"向经理申请调班",level:"基础",minutes:20,focus:"解释原因、提出替代方案",task:"你下月需要改变一个工作班次。写信给经理。至少 150 词。",bullets:["说明需要改变哪个班次","解释原因","建议怎样补回工作时间"],checklist:["语气礼貌但直接","日期和时间清楚","给出可执行方案","结尾请求确认"] },
  { id:"w3",skill:"writing",section:"Task 1 · 私人信",title:"邀请朋友来家乡",level:"基础",minutes:20,focus:"自然语气、活动安排",task:"朋友计划访问你的家乡。写信邀请其住在你家。至少 150 词。",bullets:["说明住宿安排","推荐两项活动","告诉朋友应该带什么"],checklist:["使用自然友好语气","覆盖全部三点","加入具体细节","分段清楚"] },
  { id:"w4",skill:"writing",section:"Task 2 · 观点",title:"公共交通是否应免费",level:"进阶",minutes:40,focus:"明确立场、解释与例子",task:"Some people think public transport should be free for everyone. To what extent do you agree or disagree? 至少 250 词。",bullets:["引言中明确立场","两个主体段各讲一个理由","用具体例子支持","结论重申而不新增观点"],checklist:["回应题目程度词","段落中心句清楚","连接词不过量","检查主谓一致"] },
  { id:"w5",skill:"writing",section:"Task 2 · 双边讨论",title:"独居还是与家人同住",level:"进阶",minutes:40,focus:"讨论双方并给个人观点",task:"Some adults prefer to live alone, while others prefer to live with family. Discuss both views and give your own opinion. 至少 250 词。",bullets:["解释独居的好处","解释同住的好处","给出并论证自己的观点"],checklist:["双方篇幅基本平衡","观点不自相矛盾","每段有解释和例子","结论回答完整"] },
  { id:"w6",skill:"writing",section:"Task 2 · 问题解决",title:"城市生活压力",level:"进阶",minutes:40,focus:"原因与解决方案",task:"Many people living in large cities experience high levels of stress. What are the causes, and what solutions can you suggest? 至少 250 词。",bullets:["分析至少两个原因","提出对应且现实的方案","说明方案为何有效"],checklist:["原因和方案一一对应","避免只列清单","使用准确因果表达","保留 3 分钟检查"] },

  { id:"s1",skill:"speaking",section:"Part 1",title:"家与居住地",level:"基础",minutes:8,focus:"直接回答并补一个细节",prompts:["Where do you live now?","What do you like about your neighbourhood?","Is there anything you would change about your home?","Do you think you will live there for a long time?"],keywords:["because","usually","near","would"] },
  { id:"s2",skill:"speaking",section:"Part 1",title:"工作与日常安排",level:"基础",minutes:8,focus:"现在时、频率、理由",prompts:["What kind of work do you do?","What is a typical working day like for you?","Which part of your day do you enjoy most?","Would you like to change your working hours?"],keywords:["work","day","enjoy","change"] },
  { id:"s3",skill:"speaking",section:"Part 2",title:"描述一次有帮助的谈话",level:"进阶",minutes:12,focus:"1 分钟准备、连续说 2 分钟",task:"Describe a conversation that helped you make a decision.",bullets:["who you spoke with","when and where it happened","what you discussed","why the conversation was helpful"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["spoke","discussed","decided","helpful"] },
  { id:"s4",skill:"speaking",section:"Part 2",title:"描述一项想学的技能",level:"进阶",minutes:12,focus:"过去、现在和未来时态切换",task:"Describe a skill you would like to learn.",bullets:["what the skill is","why you want to learn it","how you would learn it","how it might help you"],prompts:["You have one minute to prepare. Then speak for up to two minutes."],keywords:["learn","because","plan","help"] },
  { id:"s5",skill:"speaking",section:"Part 3",title:"成年人学习",level:"进阶",minutes:14,focus:"观点—原因—例子—回扣",prompts:["Why do some adults stop learning new skills?","Should employers give workers time for training?","How has technology changed adult education?","Are online courses suitable for everyone?"],keywords:["reason","example","however","therefore"] },
  { id:"s6",skill:"speaking",section:"Part 3",title:"城市交通与公平",level:"进阶",minutes:14,focus:"比较、让步、抽象讨论",prompts:["Why do people choose cars even when public transport is available?","How can cities encourage people to walk or cycle?","Should elderly people receive cheaper transport?","What might city transport look like in twenty years?"],keywords:["compared","although","access","future"] }
];

export const skillMeta = {
  listening:{label:"听力",description:"4 部分 · 对话、独白、观点与讲座",count:4},
  reading:{label:"阅读",description:"3 区域 · 生活、工作、长文",count:6},
  writing:{label:"写作",description:"Task 1 书信 · Task 2 议论文",count:6},
  speaking:{label:"口语",description:"Part 1、2、3 完整覆盖",count:6}
} as const;
