import { useMemo, useState } from "react";
import { IconArrowLeft, IconArrowRight, IconCheck, IconRefresh, IconTargetArrow } from "@tabler/icons-react";
import { readingAssessmentPassages, readingAssessmentStats, type ReadingPassage } from "./content/reading-assessment-bank-final";
import { createSessionSeed, shuffleWithSeed } from "./assessment-session-engine.mjs";
import { buildReadingCatResult, estimateReadingAbility, READING_CAT_LIMITS, selectNextReadingPassage, shouldFinishReadingCat } from "./reading-cat-engine-v1.mjs";
import type { LearningState, ReadingAssessmentAnswer, ReadingAssessmentDraft, ReadingAssessmentResult } from "./product-types";
import { classifyReadingQuestion, weakestReadingCategories } from "./ability-profile.mjs";
import { completeReadingAssessment } from "./reading-assessment-completion";
import "./reading-assessment.css";


const passageById=new Map(readingAssessmentPassages.map(passage=>[passage.id,passage]));
const initialThetaFromVocabulary=(state:LearningState)=>{const value=state.vocabularyTests.at(-1)?.vocabulary?.value;if(!value)return 0;if(value<2000)return-1.8;if(value<3500)return-.8;if(value<5000)return.1;if(value<8000)return.9;if(value<12000)return 1.55;return 2.1;};

export function ReadingAssessmentCat({state,update,onBack}:{state:LearningState;update:(next:Partial<LearningState>|((state:LearningState)=>LearningState))=>void;onBack:()=>void}){
  const draft=state.readingAssessmentDraft;
  const results=state.readingAssessments;
  const [showResult,setShowResult]=useState(Boolean(!draft&&results.length));
  const current=draft?passageById.get(draft.currentPassageId):undefined;
  const question=current?.questions[draft?.questionIndex??0];
  const estimate=useMemo(()=>estimateReadingAbility(draft?.answers??[],draft?.initialTheta??0),[draft]);
  const save=(nextDraft:ReadingAssessmentDraft|null,nextResults=results)=>update((currentState:LearningState)=>({...currentState,readingAssessmentDraft:nextDraft,readingAssessments:nextResults}));
  const start=()=>{const seed=createSessionSeed();const initialTheta=initialThetaFromVocabulary(state);const passage=selectNextReadingPassage(readingAssessmentPassages,[],initialTheta,seed,results.flatMap(result=>result.sampledPassageIds).slice(-18));if(!passage)return;const now=new Date().toISOString();save({mode:"reading-cat-v1",currentPassageId:passage.id,questionIndex:0,answers:[],initialTheta,startedAt:now,presentedAt:now,seed});setShowResult(false);};
  const finish=(completedAnswers:ReadingAssessmentAnswer[],activeDraft:ReadingAssessmentDraft)=>{const completedAt=new Date().toISOString();const result=buildReadingCatResult(completedAnswers,activeDraft.startedAt,completedAt,activeDraft.initialTheta);update((currentState:LearningState)=>completeReadingAssessment(currentState,completedAnswers,result));setShowResult(true);};
  const answer=(selectedOption:string)=>{if(!draft||!current||!question)return;const now=new Date();const answers=[...draft.answers,{questionId:question.id,passageId:current.id,kind:current.kind,level:current.level,weaknessCategory:classifyReadingQuestion(question.id,current.kind),selectedOption,correct:selectedOption===question.answer,difficulty:question.difficulty,discrimination:question.discrimination,optionCount:question.options.length,responseMs:Math.max(0,now.getTime()-new Date(draft.presentedAt).getTime())}];if(draft.questionIndex+1<current.questions.length){save({...draft,questionIndex:draft.questionIndex+1,answers,presentedAt:now.toISOString()});return;}const nextEstimate=estimateReadingAbility(answers,draft.initialTheta);const elapsed=now.getTime()-new Date(draft.startedAt).getTime();const next=selectNextReadingPassage(readingAssessmentPassages,answers,nextEstimate.theta,draft.seed+answers.length,results.flatMap(result=>result.sampledPassageIds).slice(-18));if(shouldFinishReadingCat(answers,nextEstimate,elapsed)||!next||(answers.length>=READING_CAT_LIMITS.minimumQuestions&&answers.length+next.questions.length>READING_CAT_LIMITS.maximumQuestions)){finish(answers,draft);return;}save({...draft,currentPassageId:next.id,questionIndex:0,answers,presentedAt:now.toISOString()});};
  const latest=results.at(-1);

  if(showResult&&latest)return <section className="lesson-content reading-cat-page"><div className="lesson-kicker">测试中心 · 阅读能力测评结果</div><h1>内部模拟阅读值</h1><div className="reading-result"><div className="reading-result-value"><span>实验值 · 非官方蓝思认证</span><strong>{latest.internalReadingValue}L</strong><em>{latest.internalLevel}</em><small>90%区间 {latest.interval.low}L–{latest.interval.high}L</small></div><div className="estimate-grid pilot"><div><span>客观题</span><strong>{latest.correctCount}/{latest.sampleSize}</strong><small>{latest.passageCount}篇独立文章</small></div><div><span>功能短文</span><strong>{latest.profile.functional.correct}/{latest.profile.functional.total}</strong><small>通知、规则和服务信息</small></div><div><span>连续篇章</span><strong>{latest.profile.continuous.correct}/{latest.profile.continuous.total}</strong><small>主旨、证据、推断和态度</small></div><div><span>可信度</span><strong>{latest.confidence.label}</strong><small>{latest.confidence.reasons.join("；")}</small></div></div><div className="reading-weakness-summary">{weakestReadingCategories(latest.weaknessProfile,3).map(item=><div key={item.category}><span>{item.label} · 错 {item.wrong}/{item.total}</span><small>{item.training}</small></div>)}</div><p className="reading-disclaimer">这是本产品根据原创文章题、1PL/Rasch兼容模型和自适应选文产生的内部实验值，只用于个人学习定位；不是MetaMetrics官方Lexile认证，也不直接换算IELTS分数。</p><div className="test-result-actions"><button className="primary-button" onClick={start}>重新测评<IconRefresh/></button><button className="outline-button" onClick={onBack}>返回测试中心<IconArrowLeft/></button></div></div></section>;

  if(!draft||!current||!question)return <section className="lesson-content reading-cat-page"><div className="lesson-kicker">独立阅读CAT · 原创内容</div><h1>阅读能力测评</h1><article className="test-intro compact reading-cat-intro"><IconTargetArrow/><h2>按整篇文章自适应选文</h2><p>系统会在完成一篇后重新估计能力，再选择最接近你的下一篇。测试约38–48题、6–8篇、20–30分钟。</p><div className="reading-bank-summary"><span><strong>{readingAssessmentStats.passages}</strong>篇独立文章</span><span><strong>{readingAssessmentStats.questions}</strong>道客观题</span><span><strong>6</strong>个难度层</span></div><p className="reading-disclaimer">结果显示内部模拟阅读值并明确标注实验性质，不冒充官方蓝思认证。</p><button className="primary-button" onClick={start}>开始阅读CAT<IconArrowRight/></button><button className="outline-button" onClick={onBack}>返回测试中心</button></article></section>;

  const options=shuffleWithSeed(question.options,draft.seed+draft.answers.length*97);
  const usedPassages=new Set(draft.answers.map(item=>item.passageId));
  const passageNumber=usedPassages.has(current.id)?usedPassages.size:usedPassages.size+1;
  return <section className="lesson-content reading-cat-page"><div className="lesson-kicker">阅读CAT · 第{passageNumber}篇 · 已答{draft.answers.length}题 · 自动保存</div><div className="test-progress" role="progressbar" aria-label="阅读能力测评进度" aria-valuemin={0} aria-valuemax={READING_CAT_LIMITS.maximumQuestions} aria-valuenow={draft.answers.length}><span style={{width:`${Math.min(100,draft.answers.length/READING_CAT_LIMITS.maximumQuestions*100)}%`}}/></div><div className="reading-cat-status"><span>{current.kind==="functional"?"功能短文":"连续篇章"}</span><span>内部题目层级 L{current.level}</span><span>当前估计误差 {estimate.standardError.toFixed(2)}</span></div><article className="assessment-passage reading-cat-passage"><h1>{current.title}</h1>{current.text.split("\n\n").map((paragraph,index)=><p key={`${current.id}-${index}`}>{paragraph}</p>)}</article><div className="test-stage"><span className="question-count">本篇第 {draft.questionIndex+1}/{current.questions.length} 题</span><h2>{question.prompt}</h2><div className="test-options english-definitions">{options.map(option=><button key={option} onClick={()=>answer(option)}>{option}</button>)}</div><p className="measurement-note">正式测评不即时显示对错；选择后直接进入下一题。</p></div></section>;
}
